// Most or all contents generated by AI (model glm-5.2).
pub mod test_all;
pub mod test_any;
pub mod test_argmax;
pub mod test_argmin;
pub mod test_count_nonzero;
pub mod test_max;
pub mod test_mean;
pub mod test_min;
pub mod test_nanargmax;
pub mod test_nanargmin;
pub mod test_prod;
pub mod test_std;
pub mod test_sum;
pub mod test_var;

pub static CATEGORY: &str = "reduction";
