// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// Reductions over broadcast (stride-0) inputs; regression for the fixed
// `size_s0` bug in the axes kernels. Ground truth from NumPy:
// b = np.broadcast_to(np.arange(4).reshape(4, 1), (4, 3))
// b.sum() == 18; b.sum(0) == [6, 6, 6]; b.sum(1) == [0, 3, 6, 9];
// b.sum((0, 1)) == 18; b.sum(1, keepdims=True) == [[0], [3], [6], [9]]
mod custom_stride0 {
    use super::*;
    static FUNC: &str = "custom_stride0";

    #[test]
    fn test_broadcast_axes() {
        crate::specify_test!("test_broadcast_axes");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<i64, _> = rt::arange((4, &device)).into_shape([4, 1]).into_dyn();
        let b = rt::broadcast_to(&a, vec![4usize, 3]);

        // whole-array (was already correct)
        assert_eq!(rt::sum(&b), 18);

        // axes reductions over stride-0 summed axis (was silently wrong: [0,4,8,12])
        let s1 = b.sum_axes(1);
        assert_eq!(s1.shape().to_vec(), vec![4]);
        assert_eq!(s1.to_vec(), vec![0, 3, 6, 9]);

        // stride-0 remaining axis (was already correct)
        let s0 = b.sum_axes(0);
        assert_eq!(s0.to_vec(), vec![6, 6, 6]);

        // all axes via the axes list (was panicking: index out of bounds)
        let s01 = b.sum_axes([0, 1]);
        assert_eq!(s01.shape().to_vec(), vec![] as Vec<usize>);
        assert_eq!(s01.to_scalar(), 18);

        // with_args + keepdims over a stride-0 summed axis
        let sk = rt::sum_with_args(&b, (1, true));
        assert_eq!(sk.shape().to_vec(), vec![4, 1]);
        assert_eq!(sk[[2, 0]], 6);

        // larger than the contiguous switch (exercises the branch-1 slice path)
        let a2: Tensor<f64, _> = rt::arange((8.0, &device)).into_shape([8, 1]).into_dyn();
        let b2 = rt::broadcast_to(&a2, vec![8usize, 16]);
        // b2.sum(1) = 16 * i
        let s = b2.sum_axes(1);
        assert_eq!(s.to_vec(), (0..8).map(|i| 16.0 * i as f64).collect::<Vec<_>>());
        // b2.sum(0) = sum(0..8) broadcast = [28; 16]
        let s = b2.sum_axes(0);
        assert_eq!(s.to_vec(), vec![28.0; 16]);
        assert_eq!(b2.sum_axes([0, 1]).to_scalar(), 28.0 * 16.0);
    }

    #[test]
    fn test_broadcast_with_dtype() {
        crate::specify_test!("test_broadcast_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // with_dtype over stride-0 inputs (used to panic on the axes-kernel route)
        let a: Tensor<u8, _> = rt::arange((4u8, &device)).into_shape([4, 1]).into_dyn();
        let b = rt::broadcast_to(&a, vec![4usize, 3]);
        let s = b.sum_with_dtype::<u64>(());
        assert_eq!(s.to_scalar(), 18u64);
        let s = b.sum_with_dtype::<u64>(1);
        assert_eq!(s.to_vec(), vec![0u64, 3, 6, 9]);
        let s = b.sum_with_dtype::<u64>(([0], true));
        assert_eq!(s.shape().to_vec(), vec![1, 3]);
        assert_eq!(s[[0, 2]], 6u64);

        // zero-size input through with_dtype (whole-array kernel: sum = 0)
        let e: Tensor<i64, _> = rt::zeros(([0, 3], &device));
        let s = e.sum_with_dtype::<i64>(());
        assert_eq!(s.to_scalar(), 0i64);
        // mean over empty input: NaN (0 / 0), matching numpy's empty-mean warning path
        let m = e.mean_with_dtype::<f64>(());
        assert!(f64::is_nan(m.to_scalar()));
    }

    #[test]
    fn test_var_std_with_dtype_correction() {
        crate::specify_test!("test_var_std_with_dtype_correction");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // correction carried through with_dtype (was silently ignored):
        // x = np.array([1., 2., 3., 4.]); x.var(ddof=1) = 5/3; x.std(ddof=1) = sqrt(5/3)
        let x: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0, 3.0, 4.0], &device);
        let v = x.var_with_dtype::<f64>(VarArgs { correction: Some(1.0), ..Default::default() });
        assert!((v.to_scalar() - 5.0 / 3.0).abs() < 1e-12);
        let s = x.std_with_dtype::<f64>(VarArgs { correction: Some(1.0), ..Default::default() });
        assert!((s.to_scalar() - (5.0f64 / 3.0).sqrt()).abs() < 1e-12);

        // correction + axes + keepdims together
        // x = np.array([[1., 2.], [3., 4.]]); np.var(x, axis=0, ddof=1) = [2., 2.]
        let z: Tensor<f64, _> = rt::tensor_from_nested!([[1.0, 2.0], [3.0, 4.0]], &device);
        let v = z.var_with_dtype::<f64>(VarArgs { axes: vec![0isize].into(), keepdims: true, correction: Some(1.0) });
        assert_eq!(v.shape().to_vec(), vec![1, 2]);
        assert!((v[[0, 0]] - 2.0).abs() < 1e-12);
        assert!((v[[0, 1]] - 2.0).abs() < 1e-12);

        // M - correction <= 0 -> NaN
        let y: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0], &device);
        let v = y.var_with_dtype::<f64>(VarArgs { correction: Some(2.0), ..Default::default() });
        assert!(f64::is_nan(v.to_scalar()));
    }

    #[test]
    fn test_overload_matrix() {
        crate::specify_test!("test_overload_matrix");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        // ReduceArgs overloads (pre-existing + new Vec-tuple)
        let _: Tensor<i64, _> = rt::sum_with_args(&a, (vec![0isize], true));
        let _: Tensor<i64, _> = rt::sum_with_args(&a, true);
        // VarArgs overloads (new): bool, Option, (Vec, bool), int axis
        // (plain var stays float-only by design; integer input routes through var_with_dtype)
        let af: Tensor<f64, _> = rt::tensor_from_nested!([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);
        let v = rt::var_with_args(&af, true);
        assert_eq!(v.shape().to_vec(), vec![1, 1]);
        let v = rt::var_with_args(&af, Option::<AxesIndex<isize>>::None);
        assert_eq!(v.shape().to_vec(), vec![] as Vec<usize>);
        let v = rt::var_with_args(&af, (vec![0isize], true));
        assert_eq!(v.shape().to_vec(), vec![1, 3]);
        let v = rt::var_with_args(&af, (1i32, false));
        assert_eq!(v.shape().to_vec(), vec![2]);
        // container element types beyond isize (parity with the _axes API)
        let _: Tensor<i64, _> = rt::sum_with_args(&a, vec![0i32, 1]);
        let _: Tensor<i64, _> = rt::sum_with_args(&a, [0u32, 1]);
        let _: Tensor<i64, _> = rt::sum_with_args(&a, (vec![0u64], true));
        let v = rt::var_with_args(&af, (vec![1usize], true));
        assert_eq!(v.shape().to_vec(), vec![2, 1]);

        // out-of-range axis: _f returns Err (does not panic inside From)
        assert!(rt::sum_with_args_f(&a, 5).is_err());
    }
}
