// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_max {
    use super::*;
    static FUNC: &str = "numpy_max";

    #[test]
    fn test_basic() {
        // NumPy v2.5.2, lib/tests/test_function_base.py, TestAmax::test_basic (line 709)
        // np.amax -> rstsr max.
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = [3, 4, 5, 10, -3, -5, 6.0]
        // assert_equal(np.amax(a), 10.0)
        let a = rt::tensor_from_nested!([3.0, 4.0, 5.0, 10.0, -3.0, -5.0, 6.0], &device);
        assert_eq!(a.max_all(), 10.0);

        // b = [[3, 6.0, 9.0], [4, 10.0, 5.0], [8, 3.0, 2.0]]
        // assert_equal(np.amax(b, axis=0), [8.0, 10.0, 9.0])
        // assert_equal(np.amax(b, axis=1), [9.0, 10.0, 8.0])
        let b = rt::tensor_from_nested!([[3.0, 6.0, 9.0], [4.0, 10.0, 5.0], [8.0, 3.0, 2.0]], &device);
        assert_equal(b.max_axes(0), rt::tensor_from_nested!([8.0, 10.0, 9.0], &device), None);
        assert_equal(b.max_axes(1), rt::tensor_from_nested!([9.0, 10.0, 8.0], &device), None);
    }
}

#[cfg(test)]
mod custom_nan_propagation {
    use super::*;
    static FUNC: &str = "custom_nan_propagation";

    #[test]
    fn test_nan() {
        crate::specify_test!("test_nan");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // NaN propagates through the reduction (array-API `max`).
        let a = rt::tensor_from_nested!([1.0, f64::NAN, 3.0], &device);
        assert!(a.max_all().is_nan());

        // per-axis: only the reductions whose slice holds a NaN become NaN
        let b = rt::tensor_from_nested!([[1.0, f64::NAN], [3.0, -2.0]], &device);
        let v0 = b.max_axes(0).to_vec();
        assert_eq!(v0[0], 3.0);
        assert!(v0[1].is_nan());
        let v1 = b.max_axes(1).to_vec();
        assert!(v1[0].is_nan());
        assert_eq!(v1[1], 3.0);

        // integers are unaffected
        let c = rt::tensor_from_nested!([1, 5, 3], &device);
        assert_eq!(c.max_all(), 5);
    }
}
