// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// rstsr-specific custom user reduction (`reduce_all` / `reduce_axes` /
// `reduce_with_args`); expected values cross-checked against the built-in
// reduction families where applicable.
mod custom_reduce {
    use super::*;
    static FUNC: &str = "custom_reduce";

    #[test]
    fn test_reduce_all_parity() {
        crate::specify_test!("test_reduce_all_parity");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // fold-spelled sum equals rt::sum
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let s = rt::reduce_all(&a, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s, rt::sum(&a));
        // finalize may change the output type (i64 accumulator -> f64 mean)
        let m = rt::reduce_all(
            &a,
            || (0_i64, 0_i64),
            |(acc, n), x| (acc + x, n + 1),
            |(acc1, n1), (acc2, n2)| (acc1 + acc2, n1 + n2),
            |(acc, n)| acc as f64 / n as f64,
        );
        assert_eq!(m, 3.5);
    }

    #[test]
    fn test_reduce_axes() {
        crate::specify_test!("test_reduce_axes");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // row-wise sum via fold equals sum_axes
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let s = rt::reduce_axes(&a, 1, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s.to_vec(), vec![6, 15]);
        assert_eq!(rt::sum_axes(&a, 1).to_vec(), vec![6, 15]);
        // negative axis and whole-reduce spelling
        let s = rt::reduce_axes_f(&a, -1, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc).unwrap();
        assert_eq!(s.to_vec(), vec![6, 15]);
        let s = rt::reduce_axes(&a, None, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s.to_scalar(), 21);
        assert_eq!(s.shape().to_vec(), vec![] as Vec<usize>);
    }

    #[test]
    fn test_reduce_with_args_keepdims() {
        crate::specify_test!("test_reduce_with_args_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let s = rt::reduce_with_args(&a, ([0], true), || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s.shape().to_vec(), vec![1, 3]);
        assert_eq!(s[[0, 2]], 9);
        // default args: whole reduction with keepdims
        let s = rt::reduce_with_args(&a, true, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s.shape().to_vec(), vec![1, 1]);
        assert_eq!(s.to_scalar(), 21);
    }

    #[test]
    fn test_fold_lp_norm_parity() {
        crate::specify_test!("test_fold_lp_norm_parity");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // the Lp-norm example from the docstring (3-norm of [1, 2, 2, -3])
        let v = rt::tensor_from_nested!([1.0, 2.0, 2.0, -3.0], &device);
        let p3 = rt::reduce_all(
            &v,
            || 0.0_f64,
            |acc, x: f64| acc + x.abs().powf(3.0),
            |acc1, acc2| acc1 + acc2,
            |acc| acc.powf(1.0 / 3.0),
        );
        assert_eq!(p3, 44.0_f64.cbrt());
    }

    #[test]
    fn test_fold_non_numeric() {
        crate::specify_test!("test_fold_non_numeric");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // boolean accumulator: any element > 4 (parallel-safe: combine = ||)
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let any = rt::reduce_all(&a, || false, |acc, x| acc || x > 4, |acc1, acc2| acc1 || acc2, |acc| acc);
        assert!(any);
        // string-like finalize: map digits to a summary struct
        let (min, max) = rt::reduce_all(
            &a,
            || (i64::MAX, i64::MIN),
            |(lo, hi), x| (lo.min(x), hi.max(x)),
            |(lo1, hi1), (lo2, hi2)| (lo1.min(lo2), hi1.max(hi2)),
            |(lo, hi)| (lo, hi),
        );
        assert_eq!(min, 1);
        assert_eq!(max, 6);
    }

    #[test]
    fn test_zero_size() {
        crate::specify_test!("test_zero_size");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // whole-reduce of empty input returns f_out(f_init())
        let e: Tensor<i64, _> = rt::zeros(([0], &device));
        let s = rt::reduce_all(&e, || 7_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc * 2);
        assert_eq!(s, 14);
        // axes-reduce of empty input drops the axis: (0,) -> 0-D with the init value
        let s = rt::reduce_axes(&e, 0, || 0_i64, |acc, x| acc + x, |acc1, acc2| acc1 + acc2, |acc| acc);
        assert_eq!(s.shape().to_vec(), vec![] as Vec<usize>);
        assert_eq!(s.to_scalar(), 0);
    }
}
