// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// rstsr-specific `*_with_dtype` surface: explicit output dtype, elements cast
// inside the fold (accumulation happens in the target dtype).
mod custom_with_dtype {
    use super::*;
    static FUNC: &str = "custom_with_dtype";

    #[test]
    fn test_sum_with_dtype() {
        crate::specify_test!("test_sum_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.full(300, 200, dtype=np.uint8)
        // a.sum(dtype=np.uint64) -> 60000 (would wrap in uint8 accumulation)
        let a: Tensor<u8, _> = rt::asarray((vec![200u8; 300], &device));
        let s = a.sum_with_dtype::<u64>(());
        assert_eq!(s.to_scalar(), 60000u64);

        // a = np.array([[1, 2, 3], [4, 5, 6]])
        // a.sum(axis=0, dtype=float) -> [5. 7. 9.], keepdims shape (1, 3)
        let b = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let s = b.sum_with_dtype::<f64>(([0], true));
        assert_eq!(s.shape().to_vec(), vec![1, 3]);
        assert_eq!(s[[0, 0]], 5.0);
        assert_eq!(s[[0, 2]], 9.0);

        // method form
        let s = b.sum_with_dtype::<f32>(1);
        assert_eq!(s.to_vec(), vec![6.0f32, 15.0f32]);

        // fallible form
        let s: Tensor<u64, _> = rt::sum_with_dtype_f(&a, ()).unwrap();
        assert_eq!(s.to_scalar(), 60000u64);
    }

    #[test]
    fn test_prod_with_dtype() {
        crate::specify_test!("test_prod_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([2, 3, 4], dtype=np.uint8); a.prod(dtype=np.uint64) -> 24
        let a = rt::tensor_from_nested!([2u8, 3u8, 4u8], &device);
        let p = &a.prod_with_dtype::<u64>(());
        assert_eq!(p.to_scalar(), 24u64);
    }

    #[test]
    fn test_mean_with_dtype() {
        crate::specify_test!("test_mean_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([1, 2, 3, 4]); a.mean(dtype=np.float64) -> 2.5
        let a = rt::tensor_from_nested!([1, 2, 3, 4], &device);
        let m = &a.mean_with_dtype::<f64>(());
        assert_eq!(m.to_scalar(), 2.5);

        // a = np.array([[1, 2], [3, 4]]); a.mean(axis=1, dtype=float) -> [1.5, 3.5]
        let b = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let m = b.mean_with_dtype::<f64>(1);
        assert_eq!(m[[0]], 1.5);
        assert_eq!(m[[1]], 3.5);
    }

    #[test]
    fn test_var_std_with_dtype() {
        crate::specify_test!("test_var_std_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([1, 2, 3, 4])
        // a.var(dtype=np.float64) -> 1.25; a.std(dtype=np.float64) -> 1.118033988749895
        let a = rt::tensor_from_nested!([1, 2, 3, 4], &device);
        let v = &a.var_with_dtype::<f64>(());
        assert!((v.to_scalar() - 1.25).abs() < 1e-12);
        let s = &a.std_with_dtype::<f64>(());
        assert!((s.to_scalar() - 1.118033988749895).abs() < 1e-12);

        // float32 accumulation target: f64 -> f32
        // a = np.array([1.0, 2.0, 3.0, 4.0]); a.var(dtype=np.float32) -> 1.25
        let b = rt::tensor_from_nested!([1.0f64, 2.0, 3.0, 4.0], &device);
        let v = &b.var_with_dtype::<f32>(());
        assert!((v.to_scalar() - 1.25f32).abs() < 1e-6);
    }

    #[test]
    fn test_sum_bool_with_dtype() {
        crate::specify_test!("test_sum_bool_with_dtype");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([True, True, False]); a.sum(dtype=np.float64) -> 2.0
        let a = rt::tensor_from_nested!([true, true, false], &device);
        let s = &a.sum_with_dtype::<f64>(());
        assert_eq!(s.to_scalar(), 2.0);
    }
}
