// Most or all contents generated by AI (model glm-5.3-flash).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// `nanargmin` follows NumPy `np.nanargmin` semantics: NaNs are skipped, and an
// all-NaN slice raises an error ("All-NaN slice encountered"). NumPy
// implements this by replacing NaN with +inf and delegating to plain argmin
// (numpy/lib/_nanfunctions_impl.py, nanargmin at :511, _replace_nan at :70).

#[cfg(test)]
mod custom_nanargmin {
    use super::*;
    static FUNC: &str = "custom_nanargmin";

    #[test]
    fn test_nan_skipped() {
        crate::specify_test!("test_nan_skipped");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // NaNs are skipped; the smallest non-NaN value wins.
        let a = rt::tensor_from_nested!([3.0, f64::NAN, 1.0], &device);
        assert_eq!(rt::nanargmin(&a), 2);

        // NaN at the front does not poison the result.
        let a = rt::tensor_from_nested!([f64::NAN, 3.0, 1.0], &device);
        assert_eq!(rt::nanargmin(&a), 2);

        // Ties keep the first occurrence.
        let a = rt::tensor_from_nested!([5.0, 1.0, 5.0], &device);
        assert_eq!(rt::nanargmin(&a), 1);

        // +-inf are ordinary values; a slice containing only NaN and inf
        // resolves to the first index (NumPy documented caveat).
        let a = rt::tensor_from_nested!([f64::NAN, f64::INFINITY, f64::NEG_INFINITY], &device);
        assert_eq!(rt::nanargmin(&a), 2);

        // f32 support.
        let a = rt::tensor_from_nested!([2.0f32, f32::NAN, 1.0f32], &device);
        assert_eq!(rt::nanargmin(&a), 2);
    }

    #[test]
    fn test_nanargmin_axes_2d() {
        crate::specify_test!("test_nanargmin_axes_2d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // [[nan, 2.0], [1.0, nan]]: column 0 -> 1.0 at row 1; column 1 -> 2.0 at row 0.
        let b = rt::tensor_from_nested!([[f64::NAN, 2.0], [1.0, f64::NAN]], &device);
        assert_eq!(b.nanargmin_axes(0).to_vec(), vec![1, 0]);

        // negative axis counts from the back; here it is axis 1 (rows):
        // row 0 -> 2.0 at col 1; row 1 -> 1.0 at col 0.
        assert_eq!(b.nanargmin_axes(-1).to_vec(), vec![1, 0]);

        // reducing all axes -> 0-D tensor with the flat index of 1.0.
        let s = b.nanargmin_axes(None);
        assert_eq!(s.shape().ndim(), 0);
        assert_equal(&s, rt::asarray((vec![2usize], &device)).into_shape([] as [usize; 0]), None);
    }

    #[test]
    fn test_int_input() {
        crate::specify_test!("test_int_input");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // No NaN in integer types: nanargmin == argmin.
        let a = rt::tensor_from_nested!([3, 1, 2], &device);
        assert_eq!(rt::nanargmin(&a), 1);
    }

    #[test]
    fn test_all_nan_error() {
        crate::specify_test!("test_all_nan_error");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([f64::NAN, f64::NAN], &device);
        let err = rt::nanargmin_f(&a).unwrap_err();
        assert!(format!("{err}").contains("All-NaN slice encountered"));

        // all-NaN along the reduced axis: that output slice errors.
        let b = rt::tensor_from_nested!([[f64::NAN, 1.0], [f64::NAN, 2.0]], &device);
        assert!(rt::nanargmin_axes_f(&b, 0).is_err());
        assert!(b.nanargmin_axes_f(0).is_err());
    }

    #[test]
    #[should_panic(expected = "All-NaN slice encountered")]
    fn test_all_nan_panics() {
        crate::specify_test!("test_all_nan_panics");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([f64::NAN, f64::NAN], &device);
        let _ = rt::nanargmin(&a);
    }
}
