// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// rstsr-specific `*_with_args` surface (ReduceArgs: axes + keepdims);
// expected values cross-checked against NumPy semantics of `keepdims=True`.
mod custom_with_args {
    use super::*;
    static FUNC: &str = "custom_with_args";

    #[test]
    fn test_sum_keepdims() {
        crate::specify_test!("test_sum_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[1, 2, 3], [4, 5, 6]])
        // a.sum(axis=0, keepdims=True) -> [[5, 7, 9]]
        // a.sum(axis=1, keepdims=True) -> [[6], [15]]
        // a.sum(keepdims=True) -> [[21]]
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let s = a.sum_with_args(([0], true));
        assert_eq!(s.shape().to_vec(), vec![1, 3]);
        assert_eq!(s[[0, 0]], 5);
        assert_eq!(s[[0, 2]], 9);
        let s = a.sum_with_args((1, true));
        assert_eq!(s.shape().to_vec(), vec![2, 1]);
        assert_eq!(s[[0, 0]], 6);
        assert_eq!(s[[1, 0]], 15);
        let s = rt::sum_with_args(&a, true);
        assert_eq!(s.shape().to_vec(), vec![1, 1]);
        assert_eq!(s.to_scalar(), 21);
        // no keepdims: same values, reduced axes dropped
        let s = rt::sum_with_args(&a, [0]);
        assert_eq!(s.shape().to_vec(), vec![3]);
        assert_eq!(s.to_vec(), vec![5, 7, 9]);
        // default args: whole reduction to 0-D
        let s = rt::sum_with_args(&a, ());
        assert_eq!(s.shape().to_vec(), vec![] as Vec<usize>);
        assert_eq!(s.to_scalar(), 21);
    }

    #[test]
    fn test_sum_keepdims_3d() {
        crate::specify_test!("test_sum_keepdims_3d");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(24).reshape(2, 3, 4)
        // a.sum(axis=(0, 2), keepdims=True)[0, :, 0] -> [60, 92, 124]
        // a.sum(axis=-1, keepdims=True) -> [[[6], [22], [38]], [[54], [70], [86]]]
        let a: Tensor<i64, _> = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let s = rt::sum_with_args(&a, ([0, 2], true));
        assert_eq!(s.shape().to_vec(), vec![1, 3, 1]);
        assert_eq!(s[[0, 0, 0]], 60);
        assert_eq!(s[[0, 1, 0]], 92);
        assert_eq!(s[[0, 2, 0]], 124);
        let s = rt::sum_with_args(&a, ([-1], true));
        assert_eq!(s.shape().to_vec(), vec![2, 3, 1]);
        assert_eq!(s[[0, 0, 0]], 6);
        assert_eq!(s[[1, 2, 0]], 86);
    }

    #[test]
    fn test_min_max_mean_keepdims() {
        crate::specify_test!("test_min_max_mean_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[1, 2, 3], [4, 5, 6]])
        // a.min(axis=0, keepdims=True) -> [[1, 2, 3]]
        // a.max(axis=1, keepdims=True) -> [[3], [6]]
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let m = rt::min_with_args(&a, ([0], true));
        assert_eq!(m.shape().to_vec(), vec![1, 3]);
        assert_eq!(m[[0, 0]], 1);
        assert_eq!(m[[0, 2]], 3);
        let m = rt::max_with_args(&a, (1, true));
        assert_eq!(m.shape().to_vec(), vec![2, 1]);
        assert_eq!(m[[0, 0]], 3);
        assert_eq!(m[[1, 0]], 6);

        // a.astype(float).mean(axis=0, keepdims=True) -> [[2.5, 3.5, 4.5]]
        let a = rt::tensor_from_nested!([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], &device);
        let m = rt::mean_with_args(&a, ([0], true));
        assert_eq!(m.shape().to_vec(), vec![1, 3]);
        assert_eq!(m[[0, 0]], 2.5);
        assert_eq!(m[[0, 2]], 4.5);
    }

    #[test]
    fn test_argmin_all_any_count_keepdims() {
        crate::specify_test!("test_argmin_all_any_count_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[8, 4, 2], [9, 7, 1]])
        // a.argmin(axis=0, keepdims=True) -> [[0, 0, 1]]
        let a = rt::tensor_from_nested!([[8, 4, 2], [9, 7, 1]], &device);
        let m = rt::argmin_with_args(&a, ([0], true));
        assert_eq!(m.shape().to_vec(), vec![1, 3]);
        assert_eq!(m[[0, 0]], 0);
        assert_eq!(m[[0, 2]], 1);

        // a = np.array([[True, False], [True, True]])
        // a.all(axis=1, keepdims=True) -> [[False], [True]]
        // a.any(axis=0, keepdims=True) -> [[True, True]]
        let b = rt::tensor_from_nested!([[true, false], [true, true]], &device);
        let r = rt::all_with_args(&b, (1, true));
        assert_eq!(r.shape().to_vec(), vec![2, 1]);
        assert!(!r[[0, 0]]);
        assert!(r[[1, 0]]);
        let r = rt::any_with_args(&b, ([0], true));
        assert_eq!(r.shape().to_vec(), vec![1, 2]);
        assert!(r[[0, 0]]);
        assert!(r[[0, 1]]);

        // a = np.array([[1, 2, 3], [4, 5, 6]])
        // np.count_nonzero(a, axis=0, keepdims=True) -> [[2, 2, 2]]
        let c = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let r = rt::count_nonzero_with_args(&c, ([0], true));
        assert_eq!(r.shape().to_vec(), vec![1, 3]);
        assert_eq!(r[[0, 1]], 2);
    }

    #[test]
    fn test_unraveled_argmin_keepdims() {
        crate::specify_test!("test_unraveled_argmin_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[8, 4, 2], [9, 7, 1]])
        // np.unravel_index(a.argmin(), a.shape) per row, keepdims shape (2, 1)
        let a = rt::tensor_from_nested!([[8, 4, 2], [9, 7, 1]], &device);
        let m = rt::unraveled_argmin_with_args(&a, (1, true));
        assert_eq!(m.shape().to_vec(), vec![2, 1]);
        assert_eq!(m.raw(), &vec![vec![2usize], vec![2usize]]);
    }

    #[test]
    fn test_bool_sum_keepdims() {
        crate::specify_test!("test_bool_sum_keepdims");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.array([[True, False], [True, True]])
        // a.sum(axis=1, keepdims=True) -> [[1], [2]]
        let b = rt::tensor_from_nested!([[true, false], [true, true]], &device);
        let s = b.sum_with_args((1, true));
        assert_eq!(s.shape().to_vec(), vec![2, 1]);
        assert_eq!(s[[0, 0]], 1);
        assert_eq!(s[[1, 0]], 2);
    }

    #[test]
    fn test_args_overloads() {
        crate::specify_test!("test_args_overloads");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        // struct literal, Default, bool, int, tuples
        let _: Tensor<i64, _> = rt::sum_with_args(&a, ReduceArgs::default());
        let _: Tensor<i64, _> = rt::sum_with_args(&a, ());
        let _: Tensor<i64, _> = rt::sum_with_args(&a, true);
        let _: Tensor<i64, _> = rt::sum_with_args(&a, 0);
        let _: Tensor<i64, _> = rt::sum_with_args(&a, 0usize);
        let _: Tensor<i64, _> = rt::sum_with_args(&a, (0, false));
        let _: Tensor<i64, _> = rt::sum_with_args(&a, ([0, 1], true));
        let _: Tensor<i64, _> = rt::sum_with_args(&a, ReduceArgs { axes: 1isize.into(), keepdims: true });

        // fallible variant
        let s = rt::sum_with_args_f(&a, (1, true)).unwrap();
        assert_eq!(s[[0, 0]], 6);
        assert_eq!(s[[1, 0]], 15);
    }

    #[test]
    fn test_var_std_correction() {
        crate::specify_test!("test_var_std_correction");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // x = np.array([1., 2., 3., 4.])
        // np.var(x) = 1.25; np.var(x, ddof=1) = 1.6666666...; np.std(x, ddof=1) = 1.2909944...
        let x: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0, 3.0, 4.0], &device);
        let v = rt::var_with_args(&x, VarArgs { axes: 0isize.into(), keepdims: false, correction: Some(0.0) });
        assert!((v.to_scalar() - 1.25).abs() < 1e-12);
        let v = rt::var_with_args_f(&x, VarArgs { correction: Some(1.0), ..Default::default() }).unwrap();
        assert!((v.to_scalar() - 5.0 / 3.0).abs() < 1e-12);
        let s = rt::std_with_args(&x, VarArgs { correction: Some(1.0), ..Default::default() });
        assert!((s.to_scalar() - (5.0f64 / 3.0).sqrt()).abs() < 1e-12);

        // np.var(np.array([1., 2.]), ddof=2) -> nan (M - correction <= 0)
        let y: Tensor<f64, _> = rt::tensor_from_nested!([1.0, 2.0], &device);
        let v = rt::var_with_args(&y, VarArgs { correction: Some(2.0), ..Default::default() });
        assert!(f64::is_nan(v.to_scalar()));
        let s = rt::std_with_args(&y, VarArgs { correction: Some(2.0), ..Default::default() });
        assert!(f64::is_nan(s.to_scalar()));

        // axes + keepdims + correction combined (column-wise ddof=1)
        // x = np.array([[1., 2.], [3., 4.]]); np.var(x, axis=0, ddof=1, keepdims=True)
        // -> [[2., 2.]]
        let z: Tensor<f64, _> = rt::tensor_from_nested!([[1.0, 2.0], [3.0, 4.0]], &device);
        let v = rt::var_with_args(&z, VarArgs { axes: vec![0isize].into(), keepdims: true, correction: Some(1.0) });
        assert_eq!(v.shape().to_vec(), vec![1, 2]);
        assert!((v[[0, 0]] - 2.0).abs() < 1e-12);
        assert!((v[[0, 1]] - 2.0).abs() < 1e-12);
    }
}
