// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_argmax {
    use super::*;
    static FUNC: &str = "numpy_argmax";

    #[test]
    fn test_combinations() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, TestArgmax::test_combinations (line 5538)
        // NumPy parametrizes a large dtype/nan/datetime table; rstsr transfers the 4
        // value cases (usg_data, defined L5441) as i32. Reversed-array rows not ported.
        crate::specify_test!("test_combinations");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // CASE usg_data L5441: [1,1,1,1,1,1,1,1,0,0,0,0,0,0,0] -> argmax 0
        let a = rt::tensor_from_nested!([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0], &device);
        assert_eq!(a.argmax_all(), 0);

        // CASE usg_data L5442: [3,3,3,3,2,2,2,2] -> argmax 0
        let a = rt::tensor_from_nested!([3, 3, 3, 3, 2, 2, 2, 2], &device);
        assert_eq!(a.argmax_all(), 0);

        // CASE usg_data L5443: [0,1,2,3,4,5,6,7] -> argmax 7
        let a = rt::tensor_from_nested!([0, 1, 2, 3, 4, 5, 6, 7], &device);
        assert_eq!(a.argmax_all(), 7);

        // CASE usg_data L5444: [7,6,5,4,3,2,1,0] -> argmax 0
        let a = rt::tensor_from_nested!([7, 6, 5, 4, 3, 2, 1, 0], &device);
        assert_eq!(a.argmax_all(), 0);
    }

    #[test]
    fn test_regression() {
        // NumPy v2.5.2, _core/tests/test_regression.py, TestRegression::test_argmax (line 262)
        // Ticket #119: high-dimensional argmax along each axis should succeed.
        crate::specify_test!("test_regression");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.random.normal(0, 1, (4, 5, 6, 7, 8))
        // for i in range(a.ndim):
        //     a.argmax(i)  # Should succeed
        let a = rt::arange((4 * 5 * 6 * 7 * 8, &device)).into_shape([4, 5, 6, 7, 8]);
        for i in 0..a.ndim() {
            let _ = a.argmax_axes(i as isize); // Should succeed
        }
    }
}

#[cfg(test)]
mod custom_argmax {
    use super::*;
    static FUNC: &str = "custom_argmax";

    #[test]
    fn test_argmax_axes_2d() {
        crate::specify_test!("test_argmax_axes_2d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // b = [[3, 6, 9], [4, 10, 5], [8, 3, 2]]
        // np.argmax(b, axis=0) == [2, 1, 0]  (col max indices)
        // np.argmax(b, axis=1) == [2, 1, 0]  (row max indices)
        let b = rt::tensor_from_nested!([[3, 6, 9], [4, 10, 5], [8, 3, 2]], &device);

        assert_eq!(b.argmax_axes(0).to_vec(), vec![2, 1, 0]);
        assert_eq!(b.argmax_axes(1).to_vec(), vec![2, 1, 0]);
    }
}

#[cfg(test)]
mod custom_argmax_nan {
    use super::*;
    static FUNC: &str = "custom_argmax_nan";

    #[test]
    fn test_nan_skipped() {
        // rstsr's argmax skips mid-stream NaNs (a NaN never wins an update);
        // a NaN at the FIRST scanned position poisons the result to 0. This
        // deliberately diverges from NumPy, where the first NaN at any
        // position wins (np.argmax([1, nan, 3]) == 1); adopting that rule
        // measurably de-vectorizes the arg kernel (see ArgCmp docs in
        // rstsr-native-impl). Use rt::nanargmax for NumPy-nanarg semantics.
        crate::specify_test!("test_nan_skipped");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([1.0, f64::NAN, 3.0], &device);
        assert_eq!(rt::argmax(&a), 2);

        let a = rt::tensor_from_nested!([1.0, 5.0, f64::NAN, 2.0], &device);
        assert_eq!(rt::argmax(&a), 1);

        // NaN at the front poisons the accumulator -> 0 (no error).
        let a = rt::tensor_from_nested!([f64::NAN, 5.0, 3.0], &device);
        assert_eq!(rt::argmax(&a), 0);

        // all-NaN -> 0 (no error).
        let a = rt::tensor_from_nested!([f64::NAN, f64::NAN], &device);
        assert_eq!(rt::argmax(&a), 0);

        // strided (transposed) layout takes the closure-fold fallback and
        // must agree: row-major scan of b.t() is [1, 3, 5, nan] -> 2.
        let b = rt::tensor_from_nested!([[1.0, 5.0], [3.0, f64::NAN]], &device);
        assert_eq!(rt::argmax(&b.t()), 2);

        // integer types have no NaN and are unaffected.
        let a = rt::tensor_from_nested!([1, 3, 2], &device);
        assert_eq!(rt::argmax(&a), 1);
    }
}
