// Most or all contents generated by AI (model glm-5.2).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_arange {
    use super::*;
    static FUNC: &str = "doc_arange";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        println!("{}", rt::arange((5, &device)));
        // [ 0 1 2 3 4]
        println!("{}", rt::arange((2, 10, &device)));
        // [ 2 3 4 5 6 7 8 9]
        println!("{}", rt::arange((10, 0, -3, &device)));
        // [ 10 7 4 1]
        println!("{}", rt::arange(5));
        // [ 0 1 2 3 4]
        assert_eq!(rt::arange((5, &device)).shape()[0], 5);
        assert_eq!(rt::arange((5, &device)).to_vec(), vec![0, 1, 2, 3, 4]);
        assert_eq!(rt::arange((2, 10, &device)).to_vec(), vec![2, 3, 4, 5, 6, 7, 8, 9]);
        assert_eq!(rt::arange((10, 0, -3, &device)).to_vec(), vec![10, 7, 4, 1]);
        assert_eq!(format!("{}", rt::arange((5, &device))), "[ 0 1 2 3 4]");
        assert_eq!(format!("{}", rt::arange((2, 10, &device))), "[ 2 3 4 5 6 7 8 9]");
        assert_eq!(format!("{}", rt::arange((10, 0, -3, &device))), "[ 10 7 4 1]");
        assert_eq!(format!("{}", rt::arange(5)), "[ 0 1 2 3 4]");
    }
}

mod doc_linspace {
    use super::*;
    static FUNC: &str = "doc_linspace";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let y: Tensor<f64, _> = rt::linspace((0.0, 1.0, 5, &device));
        println!("{y}");
        // [ 0 0.25 0.5 0.75 1]
        assert_eq!(y.shape()[0], 5);
        assert_eq!(y.to_vec(), vec![0.0, 0.25, 0.5, 0.75, 1.0]);
        assert_eq!(format!("{y}"), "[ 0 0.25 0.5 0.75 1]");

        let y: Tensor<f64, _> = rt::linspace((0.0, 10.0, 5, false, &device));
        println!("{y}");
        // [ 0 2 4 6 8]
        assert_eq!(y.to_vec(), vec![0.0, 2.0, 4.0, 6.0, 8.0]);
        assert_eq!(format!("{y}"), "[ 0 2 4 6 8]");
    }
}

mod doc_zeros_ones_full {
    use super::*;
    static FUNC: &str = "doc_zeros_ones_full";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let z: Tensor<i32, _> = rt::zeros(([2, 3], &device));
        println!("{z}");
        // [[ 0 0 0]
        //  [ 0 0 0]]
        let o: Tensor<i32, _> = rt::ones(([2, 2], &device));
        println!("{o}");
        // [[ 1 1]
        //  [ 1 1]]
        let f: Tensor<i32, _> = rt::full(([2, 2], 7, &device));
        println!("{f}");
        // [[ 7 7]
        //  [ 7 7]]
        assert_eq!(f.shape(), &[2, 2]);
        crate::test_utils::assert_equal(&z, rt::tensor_from_nested!([[0, 0, 0], [0, 0, 0]], &device), None);
        crate::test_utils::assert_equal(&o, rt::tensor_from_nested!([[1, 1], [1, 1]], &device), None);
        crate::test_utils::assert_equal(&f, rt::tensor_from_nested!([[7, 7], [7, 7]], &device), None);

        // row-major default: C-contiguous result
        println!("{:?}", z.layout());
        // 2-Dim (dyn), contiguous: Cc
        // shape: [2, 3], stride: [3, 1], offset: 0
        assert_eq!(
            format!("{:?}", z.layout()),
            "2-Dim (dyn), contiguous: Cc\nshape: [2, 3], stride: [3, 1], offset: 0"
        );

        // explicit ColMajor: F-contiguous result
        let zf: Tensor<i32, _> = rt::zeros(([2, 3], ColMajor, &device));
        println!("{:?}", zf.layout());
        // 2-Dim (dyn), contiguous: Ff
        // shape: [2, 3], stride: [1, 2], offset: 0
        assert_eq!(
            format!("{:?}", zf.layout()),
            "2-Dim (dyn), contiguous: Ff\nshape: [2, 3], stride: [1, 2], offset: 0"
        );
    }
}

mod doc_eye {
    use super::*;
    static FUNC: &str = "doc_eye";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let e: Tensor<i32, _> = rt::eye((4, &device));
        println!("{e}");
        // [[ 1 0 0 0]
        //  [ 0 1 0 0]
        //  [ 0 0 1 0]
        //  [ 0 0 0 1]]
        assert_eq!(e.shape(), &[4, 4]);
        crate::test_utils::assert_equal(
            &e,
            rt::tensor_from_nested!([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]], &device),
            None,
        );

        // non-square with off-diagonal
        let e: Tensor<i32, _> = rt::eye((3, 5, 1, &device));
        println!("{e}");
        // [[ 0 1 0 0 0]
        //  [ 0 0 1 0 0]
        //  [ 0 0 0 1 0]]
        assert_eq!(e.shape(), &[3, 5]);
        assert_eq!(format!("{e}"), "[[ 0 1 0 0 0]\n [ 0 0 1 0 0]\n [ 0 0 0 1 0]]");

        // column-major default order: same logical content (shape (n_rows,
        // n_cols), ones on the k-th diagonal); only the layout becomes
        // F-contiguous, matching numpy.eye(n, m, k, order='F').
        let mut device_c = TESTCFG.device.clone();
        device_c.set_default_order(ColMajor);
        let e: Tensor<i32, _> = rt::eye((3usize, 5usize, 0isize, &device_c));
        println!("{e}");
        println!("{:?}", e.layout());
        assert_eq!(e.shape(), &[3, 5]);
        assert_eq!(
            format!("{:?}", e.layout()),
            "2-Dim (dyn), contiguous: Ff\nshape: [3, 5], stride: [1, 3], offset: 0"
        );
        assert_eq!(format!("{e}"), "[[ 1 0 0 0 0]\n [ 0 1 0 0 0]\n [ 0 0 1 0 0]]");
        crate::test_utils::assert_equal(
            &e,
            rt::tensor_from_nested!([[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0]], &device_c),
            None,
        );
    }
}

mod doc_tril_triu {
    use super::*;
    static FUNC: &str = "doc_tril_triu";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<i32, _> = rt::ones(([3, 3], &device));
        println!("{}", rt::tril((&a, 0)));
        // [[ 1 0 0]
        //  [ 1 1 0]
        //  [ 1 1 1]]
        println!("{}", rt::triu((&a, 0)));
        // [[ 1 1 1]
        //  [ 0 1 1]
        //  [ 0 0 1]]
        crate::test_utils::assert_equal(
            rt::tril((&a, 0)),
            rt::tensor_from_nested!([[1, 0, 0], [1, 1, 0], [1, 1, 1]], &device),
            None,
        );
        crate::test_utils::assert_equal(
            rt::triu((&a, 0)),
            rt::tensor_from_nested!([[1, 1, 1], [0, 1, 1], [0, 0, 1]], &device),
            None,
        );

        let a: Tensor<i32, _> = rt::arange((1, 10, &device)).into_shape([3, 3]);
        println!("{}", rt::tril((&a, 0)));
        // [[ 1 0 0]
        //  [ 4 5 0]
        //  [ 7 8 9]]
        println!("{}", rt::triu((&a, 1)));
        // [[ 0 2 3]
        //  [ 0 0 6]
        //  [ 0 0 0]]
        assert_eq!(format!("{}", rt::tril((&a, 0))), "[[ 1 0 0]\n [ 4 5 0]\n [ 7 8 9]]");
        assert_eq!(format!("{}", rt::tril((&a, 1))), "[[ 1 2 0]\n [ 4 5 6]\n [ 7 8 9]]");
        assert_eq!(format!("{}", rt::triu((&a, 1))), "[[ 0 2 3]\n [ 0 0 6]\n [ 0 0 0]]");
        crate::test_utils::assert_equal(
            rt::tril((&a, 0)),
            rt::tensor_from_nested!([[1, 0, 0], [4, 5, 0], [7, 8, 9]], &device),
            None,
        );
        crate::test_utils::assert_equal(
            rt::triu((&a, 1)),
            rt::tensor_from_nested!([[0, 2, 3], [0, 0, 6], [0, 0, 0]], &device),
            None,
        );

        // column-major default order: the same logical tensor stored
        // F-contiguously yields identical tril/triu results
        let mut device_c = TESTCFG.device.clone();
        device_c.set_default_order(ColMajor);
        let reshaped = rt::arange((1, 10, &device_c)).into_shape([3, 3]);
        let transposed = reshaped.t();
        let tri_input = transposed.to_contig(ColMajor);
        assert!(tri_input.f_contig());
        println!("{}", rt::tril((&tri_input, 0)));
        assert_eq!(format!("{}", rt::tril((&tri_input, 0))), "[[ 1 0 0]\n [ 4 5 0]\n [ 7 8 9]]");
        assert_eq!(format!("{}", rt::triu((&tri_input, 1))), "[[ 0 2 3]\n [ 0 0 6]\n [ 0 0 0]]");
        crate::test_utils::assert_equal(
            rt::tril((&tri_input, -1)),
            rt::tensor_from_nested!([[0, 0, 0], [4, 0, 0], [7, 8, 0]], &device_c),
            None,
        );
    }
}

mod doc_empty_uninit {
    use super::*;
    static FUNC: &str = "doc_empty_uninit";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // empty: uninitialized memory, then fill by assignment
        let mut a: Tensor<i32, _> = unsafe { rt::empty(([2, 2], &device)) };
        a.fill(0);
        println!("{a}");
        // [[ 0 0]
        //  [ 0 0]]
        assert_eq!(format!("{a}"), "[[ 0 0]\n [ 0 0]]");

        // uninit: uninitialized tensor of MaybeUninit, write, then assume_init
        let mut a: Tensor<core::mem::MaybeUninit<i32>, _> = rt::uninit(([2, 2], &device));
        for (i, x) in a.raw_mut().iter_mut().enumerate() {
            *x = core::mem::MaybeUninit::new(i as i32);
        }
        let a = unsafe { rt::assume_init(a) };
        println!("{a}");
        // [[ 0 1]
        //  [ 2 3]]
        assert_eq!(format!("{a}"), "[[ 0 1]\n [ 2 3]]");
    }
}

mod doc_like_family {
    use super::*;
    static FUNC: &str = "doc_like_family";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((24, &device)).into_shape([2, 3, 4]).into_transpose([2, 0, 1]);
        println!("{:?}", a.layout());
        // 3-Dim (dyn), contiguous: Custom
        // shape: [4, 2, 3], stride: [1, 12, 4], offset: 0

        // default (TensorIterOrder::K): keeps the axis order of the input
        let z = rt::zeros_like(&a);
        println!("{:?}", z.layout());
        assert_eq!(z.shape(), a.shape());
        assert_eq!(
            format!("{:?}", z.layout()),
            "3-Dim (dyn), contiguous: Custom\nshape: [4, 2, 3], stride: [1, 12, 4], offset: 0"
        );

        // explicit row-major (C): C-contiguous result
        let z = rt::zeros_like((&a, TensorIterOrder::C));
        println!("{:?}", z.layout());
        assert_eq!(z.shape(), a.shape());
        assert_eq!(
            format!("{:?}", z.layout()),
            "3-Dim (dyn), contiguous: Cc\nshape: [4, 2, 3], stride: [6, 3, 1], offset: 0"
        );
    }
}
