[package]
name = "rstsr-openblas"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
readme = "readme.md"

[dependencies]
rayon = { workspace = true }
num = { workspace = true }
duplicate = { workspace = true }
rstsr-openblas-ffi = { workspace = true }
rstsr-native-impl = { workspace = true, features = ["rayon"] }
rstsr-core = { workspace = true, features = ["rayon"] }
rstsr-common = { workspace = true, features = ["rayon"] }
rstsr-dtype-traits = { workspace = true, features = ["half"] }
rstsr-blas-traits = { workspace = true }
rstsr-linalg-traits = { workspace = true, optional = true }
rstsr-sci-traits = { workspace = true, optional = true }

[dev-dependencies]
rstsr = { path = "../../rstsr", default-features = false, features = ["openblas", "linalg"] }
rstsr-test-manifest = { workspace = true }

[features]
default = ["linalg", "openmp"]
dynamic_loading = ["rstsr-openblas-ffi/dynamic_loading"]
faer = ["rstsr-core/faer"]
ilp64 = ["rstsr-openblas-ffi/ilp64", "rstsr-blas-traits/ilp64"]
linalg = ["dep:rstsr-linalg-traits"]
sci = ["dep:rstsr-sci-traits"]

# batched GEMM extensions (OpenBLAS >= 0.3.26 for gemm_batch, >= 0.3.34 for gemm_batch_strided)
# not enabled by default: may introduce after OpenBLAS #5979, #5980 fixed (>= 0.3.35).
use_batched_gemm = []
use_batched_gemm_strided = []

# use openmp for linking
openmp = []
# use lapacke instead of lapack for linalg functions
lapacke = ["rstsr-openblas-ffi/lapacke"]
