// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// Basic indexing via `Tensor::i(...)` (NumPy basic indexing: integer + slice +
// newaxis/ellipsis). Advanced (fancy/boolean) indexing is not implemented in rstsr
// except 1-D integer-index gather, which is exercised in `custom_indexing`.

#[cfg(test)]
mod numpy_indexing {
    use super::*;
    static FUNC: &str = "numpy_indexing";

    #[test]
    fn test_single_int_index() {
        // NumPy v2.5.2, _core/tests/test_indexing.py, TestIndexing::test_single_int_index (line
        // 201)
        crate::specify_test!("test_single_int_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(10); assert_equal(a[-1], 9)
        let a = rt::arange((10, &device));
        assert_eq!(a.i(-1).shape(), &[] as &[usize]);
        assert_eq!(a.i(-1).to_scalar(), 9);
    }

    #[test]
    fn test_ellipsis_index() {
        // NumPy v2.5.2, _core/tests/test_indexing.py, TestIndexing::test_ellipsis_index (line 177)
        crate::specify_test!("test_ellipsis_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(24).reshape(2,3,4); a[..., 1] indexes the last axis -> shape (2,3)
        let a = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let out = a.i((Ellipsis, 1));
        assert_eq!(out.shape(), &[2, 3]);
        // a[0, ..., 1] == a[0, :, 1] == [1, 5, 9]
        assert_equal(a.i((0, Ellipsis, 1)), rt::tensor_from_nested!([1, 5, 9], &device), None);
    }
}

#[cfg(test)]
mod custom_indexing {
    use super::*;
    static FUNC: &str = "custom_indexing";

    #[test]
    fn test_integer_and_slice() {
        crate::specify_test!("test_integer_and_slice");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // m = np.arange(12).reshape(3, 4)
        let m = rt::arange((12, &device)).into_shape([3, 4]);

        // m[1] == [4, 5, 6, 7]   (integer index drops the axis)
        assert_equal(m.i(1), rt::tensor_from_nested!([4, 5, 6, 7], &device), None);
        // m[-1] == last row
        assert_equal(m.i(-1), rt::tensor_from_nested!([8, 9, 10, 11], &device), None);
        // m[1, 2] == 6 (0-d scalar view)
        assert_eq!(m.i((1, 2)).to_scalar(), 6);
        // m[:, 1] == column 1
        assert_equal(m.i((.., 1)), rt::tensor_from_nested!([1, 5, 9], &device), None);
        // m[:, 1:3] == columns 1..3
        assert_equal(m.i((.., slice!(1, 3))), rt::tensor_from_nested!([[1, 2], [5, 6], [9, 10]], &device), None);
        // m[::2, :] == every other row
        assert_equal(
            m.i((slice!(None, None, 2), ..)),
            rt::tensor_from_nested!([[0, 1, 2, 3], [8, 9, 10, 11]], &device),
            None,
        );
    }

    #[test]
    fn test_newaxis() {
        crate::specify_test!("test_newaxis");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // v = np.arange(3); v[None] -> shape (1, 3); v[:, None] -> shape (3, 1)
        let v = rt::arange((3, &device));
        assert_eq!(v.i(None).shape(), &[1, 3]);
        assert_eq!(v.i((.., None)).shape(), &[3, 1]);
    }

    #[test]
    fn test_1d_advanced_index() {
        crate::specify_test!("test_1d_advanced_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // 1-D advanced (fancy) indexing: gather elements by an index array.
        // a = np.arange(10); a[[2, 4, 8]] == [2, 4, 8]
        let a = rt::arange((10, &device));
        let out = rt::index_select(&a, 0, [2, 4, 8]);
        assert_equal(&out, rt::tensor_from_nested!([2, 4, 8], &device), None);
    }
}
