// Most or all contents generated by AI (model deepseek-flash).
//! array_index_assign tests: the assignment (setter) form of array indexing —
//! NumPy `__setitem__` parity in [`numpy_array_index_assign`] and
//! rstsr-specific edge cases in [`custom_array_index_assign`].

#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

/// `true` when the error is an `IndexError` — the kind NumPy raises for a bad
/// index (and the kind the rstsr-faer-py shim maps to Python's `IndexError`).
fn is_index_error(err: &rt::Error) -> bool {
    matches!(err.inner, rstsr_core::prelude_dev::RSTSRError::IndexError(_))
}

/// A row-major device from the entry binary's test device.
fn dev() -> DeviceType {
    let mut device = TESTCFG.device.clone();
    device.set_default_order(RowMajor);
    device
}

#[cfg(test)]
mod numpy_array_index_assign {
    use super::*;
    static FUNC: &str = "numpy_array_index_assign";

    #[test]
    fn test_broaderrors_indexing_setitem() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_broaderrors_indexing
        // (L365) `assert_raises(IndexError, a.__setitem__, ([0, 1], [0, 1, 2]), 0)` — the
        // index arrays cannot broadcast.
        crate::specify_test!("test_broaderrors_indexing_setitem");
        let device = dev();

        let mut a: Tensor<f64, _> = rt::zeros(([5, 5], &device));
        let err = a.array_index_assign_f(([0, 1], [0, 1, 2]), rt::full(([1], 0.0f64, &device))).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
    }

    #[test]
    fn test_setitem_rows() {
        // NumPy: `a[[2, 0]] = rows` — a one-dimensional index array selects rows.
        crate::specify_test!("test_setitem_rows");
        let device = dev();

        let mut a = rt::arange((12, &device)).into_shape([3, 4]);
        let rows = rt::tensor_from_nested!([[100, 101, 102, 103], [-1, -2, -3, -4]], &device);
        a.array_index_assign([2, 0], &rows);
        assert_eq!(a.into_shape([-1]).to_vec(), vec![-1, -2, -3, -4, 4, 5, 6, 7, 100, 101, 102, 103]);
    }
}

#[cfg(test)]
mod custom_array_index_assign {
    use super::*;
    static FUNC: &str = "custom_array_index_assign";

    #[test]
    fn test_zipped_and_broadcast() {
        crate::specify_test!("test_zipped_and_broadcast");
        let device = dev();

        // two index arrays zipped into a one-dimensional selection
        let mut a = rt::arange((12, &device)).into_shape([3, 4]);
        a.array_index_assign(([0, 2], [1, 3]), rt::tensor_from_nested!([10, 20], &device));
        assert_eq!(a.into_shape([-1]).to_vec(), vec![0, 10, 2, 3, 4, 5, 6, 7, 8, 9, 10, 20]);

        // the value is broadcast to the selection shape (2, 1) -> (2, 3)
        let mut b: Tensor<f64, _> = rt::zeros(([3, 3], &device));
        b.array_index_assign(([0, 2], ..), rt::tensor_from_nested!([[1.0], [2.0]], &device));
        assert_eq!(b.into_shape([-1]).to_vec(), vec![1., 1., 1., 0., 0., 0., 2., 2., 2.]);
    }

    #[test]
    fn test_cast() {
        crate::specify_test!("test_cast");
        let device = dev();

        // an i32 value into an f64 destination (implicit cast)
        let mut a: Tensor<f64, _> = rt::zeros(([4], &device));
        a.array_index_assign([0, 1, 2, 3], rt::tensor_from_nested!([1i32, 2, 3, 4], &device));
        assert_eq!(a.to_vec(), vec![1., 2., 3., 4.]);
    }

    #[test]
    fn test_mask_and_basic() {
        crate::specify_test!("test_mask_and_basic");
        let device = dev();

        // a boolean mask selects the rows it keeps
        let mut a: Tensor<f64, _> = rt::zeros(([3, 2], &device));
        let mask = rt::asarray((vec![true, false, true], &device));
        a.array_index_assign(&mask, rt::full(([2, 2], 1.5f64, &device)));
        assert_eq!(a.into_shape([-1]).to_vec(), vec![1.5, 1.5, 0.0, 0.0, 1.5, 1.5]);

        // no array indexer: basic slicing assignment (an integer select)
        let mut b = rt::arange((6, &device)).into_shape([2, 3]);
        b.array_index_assign(1, rt::tensor_from_nested!([7, 8, 9], &device));
        assert_eq!(b.into_shape([-1]).to_vec(), vec![0, 1, 2, 7, 8, 9]);
    }

    #[test]
    fn test_duplicate_last_wins() {
        crate::specify_test!("test_duplicate_last_wins");
        let device = dev();

        // duplicate index targets: the last written value wins (row-major order)
        let mut a: Tensor<i64, _> = rt::zeros(([4], &device));
        a.array_index_assign([3, 3, 3], rt::tensor_from_nested!([1i64, 2, 3], &device));
        assert_eq!(a.to_vec(), vec![0, 0, 0, 3]);
    }

    #[test]
    fn test_errors() {
        crate::specify_test!("test_errors");
        let device = dev();

        let mut a: Tensor<f64, _> = rt::zeros(([3, 3], &device));
        // index out of range
        let err = a.array_index_assign_f([9], rt::tensor_from_nested!([1.0], &device)).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // value cannot broadcast to the selection shape (2, 2) vs (3, 3)
        let err =
            a.array_index_assign_f([0, 1, 2], rt::tensor_from_nested!([[1.0, 2.0], [3.0, 4.0]], &device)).unwrap_err();
        assert!(!is_index_error(&err), "a broadcast mismatch is not an IndexError: {err}");
    }
}
