// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// Basic indexing via `Tensor::i(...)` (NumPy basic indexing: integer + slice +
// newaxis/ellipsis). Advanced indexing has its own entry points: array indexing
// (`rt::array_index`, `test_array_index.rs`), boolean masks (`rt::mask_select` /
// `rt::bool_select`) and one-axis gathers (`rt::index_select` / `rt::take`).

#[cfg(test)]
mod numpy_indexing {
    use super::*;
    static FUNC: &str = "numpy_indexing";

    #[test]
    fn test_single_int_index() {
        // NumPy v2.5.2, _core/tests/test_indexing.py, TestIndexing::test_single_int_index (line
        // 201)
        crate::specify_test!("test_single_int_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(10); assert_equal(a[-1], 9)
        let a = rt::arange((10, &device));
        assert_eq!(a.i(-1).shape(), &[] as &[usize]);
        assert_eq!(a.i(-1).to_scalar(), 9);
    }

    #[test]
    fn test_ellipsis_index() {
        // NumPy v2.5.2, _core/tests/test_indexing.py, TestIndexing::test_ellipsis_index (line 177)
        crate::specify_test!("test_ellipsis_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(24).reshape(2,3,4); a[..., 1] indexes the last axis -> shape (2,3)
        let a = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let out = a.i((Ellipsis, 1));
        assert_eq!(out.shape(), &[2, 3]);
        // a[0, ..., 1] == a[0, :, 1] == [1, 5, 9]
        assert_equal(a.i((0, Ellipsis, 1)), rt::tensor_from_nested!([1, 5, 9], &device), None);
    }
}

#[cfg(test)]
mod custom_indexing {
    use super::*;
    static FUNC: &str = "custom_indexing";

    #[test]
    fn test_integer_and_slice() {
        crate::specify_test!("test_integer_and_slice");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // m = np.arange(12).reshape(3, 4)
        let m = rt::arange((12, &device)).into_shape([3, 4]);

        // m[1] == [4, 5, 6, 7]   (integer index drops the axis)
        assert_equal(m.i(1), rt::tensor_from_nested!([4, 5, 6, 7], &device), None);
        // m[-1] == last row
        assert_equal(m.i(-1), rt::tensor_from_nested!([8, 9, 10, 11], &device), None);
        // m[1, 2] == 6 (0-d scalar view)
        assert_eq!(m.i((1, 2)).to_scalar(), 6);
        // m[:, 1] == column 1
        assert_equal(m.i((.., 1)), rt::tensor_from_nested!([1, 5, 9], &device), None);
        // m[:, 1:3] == columns 1..3
        assert_equal(m.i((.., slice!(1, 3))), rt::tensor_from_nested!([[1, 2], [5, 6], [9, 10]], &device), None);
        // m[::2, :] == every other row
        assert_equal(
            m.i((slice!(None, None, 2), ..)),
            rt::tensor_from_nested!([[0, 1, 2, 3], [8, 9, 10, 11]], &device),
            None,
        );
    }

    #[test]
    fn test_newaxis() {
        crate::specify_test!("test_newaxis");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // v = np.arange(3); v[None] -> shape (1, 3); v[:, None] -> shape (3, 1)
        let v = rt::arange((3, &device));
        assert_eq!(v.i(None).shape(), &[1, 3]);
        assert_eq!(v.i((.., None)).shape(), &[3, 1]);
    }

    /// Regression (2026-10-08, surfaced by the array-indexing differential
    /// harness): negative-step and empty slices must follow Python's slicing
    /// rules — an empty result must not keep a `start` that drives the offset
    /// out of the buffer when the axis stride is negative.
    #[test]
    fn test_negative_step_and_empty_slices() {
        crate::specify_test!("test_negative_step_and_empty_slices");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.arange(5)
        let a = rt::arange((5, &device));
        // a[::-1] == [4, 3, 2, 1, 0]
        assert_equal(a.i(slice!(None, None, -1)), rt::tensor_from_nested!([4, 3, 2, 1, 0], &device), None);
        // a[4:-1:-1] == [] and a[-6::-1] == []: an explicit negative bound
        // counts from the back (it is not the "reverse to the start" default)
        assert_eq!(a.i(slice!(4, -1, -1)).shape(), &[0]);
        assert_eq!(a.i(slice!(-6, None, -1)).shape(), &[0]);
        // a[-4::-1] == [1, 0]
        assert_equal(a.i(slice!(-4, None, -1)), rt::tensor_from_nested!([1, 0], &device), None);
        // a[2:2] == []
        assert_eq!(a.i(slice!(2, 2)).shape(), &[0]);

        // empty slices on a negative-stride axis keep a valid offset (a stale
        // `start` used to underflow it); `2:5` on a size-2 axis is empty too —
        // emptiness is only known after the stop is clamped
        let m = rt::arange((6, &device)).into_shape([2, 3]);
        let rev = m.i((slice!(None, None, -1), ..));
        assert_eq!(rev.i((slice!(2, 2), ..)).shape(), &[0, 3]);
        assert_eq!(rev.i((slice!(2, 5), ..)).shape(), &[0, 3]);
        assert_eq!(rev.i((slice!(3, 5), ..)).shape(), &[0, 3]);
        // the offset of an empty view stays inside the buffer (it used to
        // underflow to a huge `usize` on the negative-stride axis)
        assert_eq!(rev.i((slice!(2, 5), ..)).offset(), 3);
        let idx = rt::asarray((vec![0_isize, 1], &device));
        assert_eq!(rev.array_index_f((slice!(2, 2), &idx)).unwrap().shape(), &[0, 2]);
        assert_eq!(rev.array_index_f((slice!(2, 5), &idx)).unwrap().shape(), &[0, 2]);
        // m[::-1][1:2] == [m[0]]
        assert_equal(rev.i((slice!(1, 2), ..)), rt::tensor_from_nested!([[0, 1, 2]], &device), None);
    }

    #[test]
    fn test_1d_advanced_index() {
        crate::specify_test!("test_1d_advanced_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // 1-D advanced (fancy) indexing: gather elements by an index array.
        // a = np.arange(10); a[[2, 4, 8]] == [2, 4, 8]
        let a = rt::arange((10, &device));
        let out = rt::index_select(&a, 0, [2, 4, 8]);
        assert_equal(&out, rt::tensor_from_nested!([2, 4, 8], &device), None);
    }
}

#[cfg(test)]
mod custom_indexing_take {
    use super::*;
    static FUNC: &str = "custom_indexing_take";

    #[test]
    fn test_take_empty_indices() {
        crate::specify_test!("test_take_empty_indices");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // Regression (rstsr-faer-py review, 2026-10-06): the max() sentinel
        // tested 0 against an empty axis; NumPy returns the empty selection.
        let a: Tensor<f64, _> = rt::zeros(([0], &device));
        let b = rt::take_f(&a, Vec::<isize>::new(), 0).unwrap();
        assert_eq!(b.shape(), &[0]);

        let a: Tensor<f64, _> = rt::zeros(([3, 0], &device));
        let b = rt::take_f(&a, Vec::<isize>::new(), 1).unwrap();
        assert_eq!(b.shape(), &[3, 0]);

        // non-empty indices are still bounds-checked
        let a: Tensor<f64, _> = rt::zeros(([3], &device));
        assert!(rt::take_f(&a, vec![5isize], 0).is_err());
    }
}
