// Most or all contents generated by AI (model deepseek-flash).
//! array_index tests: NumPy-cited array-indexing (fancy indexing) contract,
//! placement-rule cases from the NumPy indexing guide, and a NumPy-generated
//! differential set inlined as [`NUMPY_CASES`].

#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

/// Parse the index spec of a generated case: tokens separated by `|`, each of
/// `I<n>` (integer), `S<a>:<b>:<c>` (slice), `A<d0>x..:<v..>` (index array),
/// `N` (new axis) or `E` (ellipsis).
fn parse_indexers(device: &DeviceType, spec: &str) -> ArrayIndexArgs<DeviceType> {
    let parse_opt = |s: &str| -> Option<isize> {
        if s.is_empty() {
            None
        } else {
            Some(s.parse().unwrap())
        }
    };
    let mut indexers: Vec<ArrayIndexer<DeviceType>> = Vec::new();
    for token in spec.split('|') {
        if token.is_empty() {
            continue;
        }
        match &token[..1] {
            "I" => indexers.push(ArrayIndexer::Basic(Indexer::Select(token[1..].parse().unwrap()))),
            "S" => {
                let parts = token[1..].split(':').collect::<Vec<_>>();
                let slice = SliceI::new(
                    parse_opt(parts.first().copied().unwrap_or("")),
                    parse_opt(parts.get(1).copied().unwrap_or("")),
                    parse_opt(parts.get(2).copied().unwrap_or("")),
                );
                indexers.push(ArrayIndexer::Basic(Indexer::Slice(slice)));
            },
            "A" => {
                let (shape_txt, values_txt) = token[1..].split_once(':').unwrap();
                let shape = shape_txt.split('x').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
                let values = values_txt.split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>();
                let index = rt::asarray((values, device)).into_shape(shape);
                indexers.push(ArrayIndexer::ArrayIndex(index));
            },
            "N" => indexers.push(ArrayIndexer::Basic(Indexer::Insert)),
            "E" => indexers.push(ArrayIndexer::Basic(Indexer::Ellipsis)),
            other => panic!("invalid index token `{other}` in case spec `{spec}`"),
        }
    }
    ArrayIndexArgs::new(indexers)
}

/// `true` when the error is an `IndexError` — the kind NumPy raises for a bad
/// index (and the kind the rstsr-faer-py shim maps to Python's `IndexError`).
fn is_index_error(err: &rt::Error) -> bool {
    matches!(err.inner, rstsr_core::prelude_dev::RSTSRError::IndexError(_))
}

#[cfg(test)]
mod numpy_array_index {
    use super::*;
    static FUNC: &str = "numpy_array_index";

    #[test]
    fn test_empty_fancy_index() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_empty_fancy_index (L127)
        crate::specify_test!("test_empty_fancy_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((3, &device));
        let empty = rt::asarray((Vec::<isize>::new(), &device));
        // `assert_equal(a[[]], [])` — an empty index array gives an empty result
        let b = a.array_index(&empty);
        assert_eq!(b.shape(), &vec![0]);
        assert_eq!(b.into_shape([-1]).to_vec(), Vec::<i32>::new());
        // `assert_equal(a[[]].dtype, a.dtype)` — dtype preservation is
        // structural in rstsr: the result element type is the input's `T`.
        // `b = np.array([]); assert_raises(IndexError, a.__getitem__, b)` is
        // type-level N/A: rstsr index tensors are typed `isize`.

        // an empty index array on a higher-rank tensor keeps the trailing axes
        let c = rt::arange((12, &device)).into_shape([3, 4]);
        let d = c.array_index((&empty,));
        assert_eq!(d.shape(), &vec![0, 4]);
    }

    #[test]
    fn test_broaderrors_indexing() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_broaderrors_indexing
        // (L365)
        crate::specify_test!("test_broaderrors_indexing");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<f64, _> = rt::zeros(([5, 5], &device));
        // `assert_raises(IndexError, a.__getitem__, ([0, 1], [0, 1, 2]))`
        let err = a.array_index_f(([0, 1], [0, 1, 2])).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // `assert_raises(IndexError, a.__setitem__, ([0, 1], [0, 1, 2]), 0)` is
        // N/A: advanced-key assignment is not implemented yet (registered).
    }

    #[test]
    fn test_nontuple_ndindex() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_nontuple_ndindex (L612)
        // A bare list indexes the first axis (`a[[0,1]]` is a row list), while
        // a tuple zips index arrays. The `a[[slice(None)]]` IndexError case is
        // N/A: Rust has no list-of-slice literal (a host list is a single
        // one-dimensional index array).
        crate::specify_test!("test_nontuple_ndindex");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((25, &device)).into_shape([5, 5]);
        // `assert_equal(a[[0, 1]], np.array([a[0], a[1]]))`
        assert_equal(a.array_index([0, 1]), a.slice((0..2, ..)), None);
        // `assert_equal(a[[0, 1], [0, 1]], np.array([0, 6]))`
        assert_eq!(a.array_index(([0, 1], [0, 1])).into_shape([-1]).to_vec(), vec![0, 6]);
    }
}

/// NumPy-solved array-indexing cases: `(tensor shape, index spec, out shape, out values)`.
///
/// Generated 2026-10-08 from NumPy v2.5.2 by the generator kept with the task
/// record (rstsr-improve-trajectory/2026-10-08-array-indexing/case-generator/):
/// 130 rows,
/// covering mixed basic + array indexers, mutual broadcasting, negative and
/// duplicated entries, empty index arrays, new axes and both full-width and
/// zero-width ellipses. The spec format is documented on [`parse_indexers`].
#[rustfmt::skip]
static NUMPY_CASES: &[(&str, &str, &str, &str)] = &[
    ("1", "A2x1:-1,-1", "2,1", "0,0"),
    ("1", "I-1", "", "0"),
    ("1", "I0", "", "0"),
    ("1", "S0:1:-1", "0", ""),
    ("1,1", "A1:-1|S0:0:1|E|N", "1,0,1", ""),
    ("1,1,5", "E|S1:0:2|N", "1,1,0,1", ""),
    ("1,2", "E|A2:0,0|S2:2:2", "2,0", ""),
    ("1,2", "S0:1:1|I-1", "1", "1"),
    ("1,2,5", "E|S1:0:2", "1,2,0", ""),
    ("1,3,1", "I-1|N|E|I-1|I-1", "1", "2"),
    ("1,3,4", "I-1|S2:0:2|I-1|E", "0", ""),
    ("1,3,5", "S-1:-1:-1|E|N", "0,3,5,1", ""),
    ("1,4,1", "A1x1:0|S0:2:1|A2:0,0|N", "1,2,2,1", "0,1,0,1"),
    ("1,4,1", "S-1:1:-2|S1:1:2|E|I-1", "0,0", ""),
    ("1,4,2,5", "I-1|E", "4,2,5", "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39"),
    ("1,4,3", "S1:1:1|E", "0,4,3", ""),
    ("1,5", "A2x2:0,0,0,0|I-2|E", "2,2", "3,3,3,3"),
    ("1,5", "A3x1:0,0,0|S2:2:1|N", "3,1,0,1", ""),
    ("1,5", "S1:0:1|A1:0|E", "0,1", ""),
    ("1,5,4,4", "E|I-1|I-3|S1:1:1|S1:1:1", "0,0", ""),
    ("1,5,5,4", "I-1|A2:0,3|S5:0:1|I-4|E", "2,0", ""),
    ("2", "A1:1", "1", "1"),
    ("2", "A1x3:1,0,0", "1,3", "1,0,0"),
    ("2", "I1", "", "1"),
    ("2", "S0:2:1", "2", "0,1"),
    ("2", "S2:0:1", "0", ""),
    ("2,1", "E|A2:1,1|S-1:-2:-2", "2,1", "1,1"),
    ("2,1", "E|S-1:-2:-1|N", "2,1,1", "0,1"),
    ("2,1", "I-2|E|N", "1,1", "0"),
    ("2,1,1", "E|I0|I-1|N", "2,1", "0,1"),
    ("2,1,2,5", "E|I1|I0", "2,1", "5,15"),
    ("2,1,3", "S2:1:2|A3:-1,-1,-1|E|I-1", "3,0", ""),
    ("2,1,5,1", "S-1:2:-2|I-1|E", "0,5,1", ""),
    ("2,1,5,3", "A2x3:-1,-2,-1,-1,-1,-1|N|I0|I-4|S1:3:1", "2,3,1,2", "19,20,4,5,19,20,19,20,19,20,19,20"),
    ("2,2,1,4", "A1:-1|I-1|N|I-1|E", "1,1,4", "12,13,14,15"),
    ("2,3", "E|S-1:-2:-2|I-1", "1", "5"),
    ("2,3", "S1:1:1|E|I-2", "0", ""),
    ("2,3,1,1", "S0:0:2|I-1|E|I0|I-1", "0", ""),
    ("2,3,2", "I1|E|A2:2,2|A2x1:0,1", "2,2", "10,10,11,11"),
    ("2,3,5,3", "I-1|A3:-1,-2,-2|E|A1:0", "3,5", "75,78,81,84,87,60,63,66,69,72,60,63,66,69,72"),
    ("2,4", "A1:1|I3", "1", "7"),
    ("2,4,1,4", "S2:1:2|E|S3:0:1|A2x1:-1,-1|N", "0,4,0,2,1,1", ""),
    ("2,4,4", "I-1|N|A3:-3,-3,-4|S0:0:-1", "3,1,0", ""),
    ("2,4,4", "I1|E", "4,4", "16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31"),
    ("2,4,4,3", "E|S2:0:1|I-2", "2,4,0", ""),
    ("2,5", "S2:0:2|E|A1:-2", "0,1", ""),
    ("2,5,2,1", "A1x2:1,1|E|I0|A1x1:0|N", "1,2,5,1", "10,12,14,16,18,10,12,14,16,18"),
    ("2,5,2,1", "A3x2:-2,-1,-1,-2,-1,-2|S4:-5:-2|N|I-2|E|N", "3,2,2,1,1,1", "8,4,18,14,18,14,8,4,18,14,8,4"),
    ("2,5,4", "A3:0,0,0|E", "3,5,4", "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19"),
    ("3", "A3x3:-1,-3,-3,-2,-1,-2,-2,-2,-1|N", "3,3,1", "2,0,0,1,2,1,1,1,2"),
    ("3", "I-2", "", "1"),
    ("3", "I1", "", "1"),
    ("3", "S2:0:1|N", "0,1", ""),
    ("3", "S3:1:1", "0", ""),
    ("3,1", "I-1|N|I-1", "1", "2"),
    ("3,1,3", "A2:1,2|I0|I-3", "2", "3,6"),
    ("3,1,4,2", "I1|S0:1:1|E|N", "1,4,2,1", "8,9,10,11,12,13,14,15"),
    ("3,2,2", "E|S0:2:1|N|A3x2:0,1,1,1,0,0", "3,2,1,3,2", "0,1,1,1,0,0,2,3,3,3,2,2,4,5,5,5,4,4,6,7,7,7,6,6,8,9,9,9,8,8,10,11,11,11,10,10"),
    ("3,2,2", "I1|E|I0", "2", "4,6"),
    ("3,2,3,2", "I2|S0:2:-1|A2x3:-3,-1,-2,-1,-2,-3|I-2", "2,3,0", ""),
    ("3,2,3,5", "A2x1:1,2|A2x1:-1,-1|N|S2:0:1|I-4|N", "2,1,1,0,1", ""),
    ("3,2,5", "A1:2|S1:0:1|E", "1,0,5", ""),
    ("3,3", "A3x3:0,1,1,2,0,1,2,2,1|E|S1:1:1", "3,3,0", ""),
    ("3,3", "I0|E", "3", "0,1,2"),
    ("3,3", "S0:2:1|S2:2:1|E", "2,0", ""),
    ("3,3,2,2", "I-2|S2:-3:-1|A2x2:-2,-1,-1,-2|I1", "2,2,2", "21,17,23,19,23,19,21,17"),
    ("3,4", "A2:-1,-1|A2:1,3", "2", "9,11"),
    ("3,4", "A2:1,1|E|A1x1:3", "1,2", "7,7"),
    ("3,4", "S0:2:1|A2:2,2", "2,2", "2,2,6,6"),
    ("3,4,1", "A1:-3|I-1|A3:0,0,0", "3", "3,3,3"),
    ("3,4,1,4", "S-1:1:-2|A1:3|N|S0:-2:-1|S0:0:-2", "1,1,1,1,0", ""),
    ("3,4,2,3", "S3:0:1|A2x1:1,0|S0:2:2|I-3", "2,1,0,1", ""),
    ("3,5", "A1x2:-2,-3|E|I0", "1,2", "5,0"),
    ("3,5", "A2:2,0|E", "2,5", "10,11,12,13,14,0,1,2,3,4"),
    ("3,5", "E|A1x3:0,0,0|I-5", "1,3", "0,0,0"),
    ("3,5", "S3:3:2|A2x1:3,0", "0,2,1", ""),
    ("3,5,1", "A2:2,0|E|S4:3:1|S1:1:2", "2,0,0", ""),
    ("4", "I-2", "", "2"),
    ("4", "I3", "", "3"),
    ("4", "S-2:2:-1|N", "0,1", ""),
    ("4,1,3", "S1:3:1|S0:0:1|S3:1:1|N", "2,0,0,1", ""),
    ("4,2", "A1x3:0,3,1|E|N|S1:2:1", "1,3,1,1", "1,7,3"),
    ("4,2", "E|I-1", "4", "1,3,5,7"),
    ("4,2", "I-3|I-1|E", "", "3"),
    ("4,2,3,3", "E|A2:0,2|S0:0:1|I-3|I-1", "2,0", ""),
    ("4,2,4,5", "I-2|I-2|I-2|N|I-5", "1", "90"),
    ("4,2,5,4", "S3:3:1|I0|E", "0,5,4", ""),
    ("4,2,5,5", "A1x2:0,3|S0:0:1|A1:3|E", "1,2,0,5", ""),
    ("4,3", "E|A3x3:1,1,0,3,2,1,0,3,3|I-3", "3,3", "3,3,0,9,6,3,0,9,9"),
    ("4,3", "E|S3:-2:-1|S2:0:1", "1,0", ""),
    ("4,3", "I-4|E|N", "3,1", "0,1,2"),
    ("4,3", "I1|E|N", "3,1", "3,4,5"),
    ("4,3,4,2", "A2:1,1|I0|E|S0:0:1", "2,4,0", ""),
    ("4,4", "A1:-2|I3|E", "1", "11"),
    ("4,4", "I3|E", "4", "12,13,14,15"),
    ("4,4", "I3|I3", "", "15"),
    ("4,4,1,2", "I-2|E|S3:1:1|I-1|S2:2:2", "0,0", ""),
    ("4,4,1,3", "A3x2:-2,-3,-2,-4,-4,-1|E", "3,2,4,1,3", "24,25,26,27,28,29,30,31,32,33,34,35,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,0,1,2,3,4,5,6,7,8,9,10,11,0,1,2,3,4,5,6,7,8,9,10,11,36,37,38,39,40,41,42,43,44,45,46,47"),
    ("4,4,2,5", "I-4|A2:3,2|A1x2:-1,-1|E|N", "1,2,5,1", "35,36,37,38,39,25,26,27,28,29"),
    ("4,5", "E|S3:1:1", "4,0", ""),
    ("4,5,1", "S2:3:1|A3:-3,-2,-1|A3x1:0,0,0", "1,3,3", "12,13,14,12,13,14,12,13,14"),
    ("4,5,2", "A3x3:-1,-2,-4,-4,-3,-3,-2,-2,-1|E", "3,3,5,2", "30,31,32,33,34,35,36,37,38,39,20,21,22,23,24,25,26,27,28,29,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39"),
    ("5", "S4:5:1", "1", "4"),
    ("5,1", "A2:3,2|E", "2,1", "3,2"),
    ("5,1", "E|S4:2:1", "5,0", ""),
    ("5,1", "S5:4:1|N|E", "0,1,1", ""),
    ("5,1,1,3", "S3:5:1|E|I0|A1x3:-1,-1,-1|I-1", "2,1,3", "11,11,11,14,14,14"),
    ("5,1,2,2", "E|I-1", "5,1,2", "1,3,5,7,9,11,13,15,17,19"),
    ("5,1,3", "A1x3:0,0,2|I-1|A3:2,0,1|E", "1,3", "2,0,7"),
    ("5,1,3,2", "I-1|N|I-1|E", "1,3,2", "24,25,26,27,28,29"),
    ("5,1,4,2", "A2x1:-4,-3|E", "2,1,1,4,2", "8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"),
    ("5,2", "E|S3:3:2", "5,0", ""),
    ("5,2", "S4:1:2|A1x2:0,0", "0,1,2", ""),
    ("5,2,1,2", "E|I-5|A2x3:0,0,1,0,0,1|S1:1:1|S0:0:2", "2,3,0,0", ""),
    ("5,2,4", "A2:0,3|E|N|I0", "2,2,1", "0,4,24,28"),
    ("5,2,4", "S0:2:2|N|I0|S0:2:1", "1,1,2", "0,1"),
    ("5,2,4", "S3:3:-2|E|S0:1:2|I1", "0,1", ""),
    ("5,2,5", "I3|E|S1:1:1|I-4", "0", ""),
    ("5,3", "I-5|S1:1:1", "0", ""),
    ("5,3", "I1|E|N", "3,1", "3,4,5"),
    ("5,3", "S0:2:1|E", "2,3", "0,1,2,3,4,5"),
    ("5,3,1,3", "S5:1:1|S2:3:1|N|E|A1:0", "0,1,1,1,1", ""),
    ("5,3,5", "I-5|A1:-2|E", "1,5", "5,6,7,8,9"),
    ("5,4", "A1x2:4,4|E", "1,2,4", "16,17,18,19,16,17,18,19"),
    ("5,4", "S2:3:2|E", "1,4", "8,9,10,11"),
    ("5,4,3", "S0:1:1|E|I2", "1,4", "2,5,8,11"),
    ("5,4,3,1", "A2x1:2,0|I0|N|I-1|I0", "2,1,1", "26,2"),
    ("5,5", "I2|E", "5", "10,11,12,13,14"),
    ("5,5", "I3|N|I-5", "1", "15"),
    ("5,5,2", "A3x3:0,2,3,1,4,0,2,3,2|I1|I-2", "3,3", "2,22,32,12,42,2,22,32,22"),
];

#[cfg(test)]
mod custom_array_index {
    use super::*;
    static FUNC: &str = "custom_array_index";

    #[test]
    fn test_placement_rule_examples() {
        crate::specify_test!("test_placement_rule_examples");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // the examples of NumPy's indexing guide ("Advanced Indexing"): one
        // contiguous advanced run broadcasts in place, separated index arrays
        // move the broadcast dimensions to the front
        let x = rt::arange((10 * 20 * 30, &device)).into_shape([10, 20, 30]);
        let ind = rt::asarray(((0..10_isize).collect::<Vec<_>>(), &device));

        // `x[:, ind, ind]`: contiguous advanced run -> in place
        let z = x.array_index((.., &ind, &ind));
        assert_eq!(z.shape(), &vec![10, 10]);
        assert_eq!(z.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 31, 62]);

        // `x[ind, :, ind]`: the advanced run is separated by a slice -> front
        let y = x.array_index((&ind, .., &ind));
        assert_eq!(y.shape(), &vec![10, 20]);
        assert_eq!(y.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 30, 60]);
    }

    #[test]
    fn test_placement_rule_4d() {
        crate::specify_test!("test_placement_rule_4d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let f = rt::arange((2 * 3 * 4 * 5, &device)).into_shape([2, 3, 4, 5]);
        let i01 = rt::asarray((vec![1_isize, 0], &device));
        let i43 = rt::asarray((vec![4_isize, 3], &device));

        // `f[[1,0], :, :, [4,3]]`: arrays separated by two slices -> front
        assert_eq!(f.array_index((&i01, Ellipsis, &i43)).shape(), &vec![2, 3, 4]);
        // `f[:, [1,0], :, [4,3]]`: separated -> front (after nothing)
        assert_eq!(f.array_index((.., &i01, .., &i43)).shape(), &vec![2, 2, 4]);
        // `f[[1,0], :, 1, :]`: integer counts as advanced for the grouping
        assert_eq!(f.array_index((&i01, .., 1, ..)).shape(), &vec![2, 3, 5]);
        // `f[:, [1,0], 1, :]`: a single contiguous advanced run -> in place
        assert_eq!(f.array_index((.., &i01, 1, ..)).shape(), &vec![2, 2, 5]);
    }

    /// A zero-width ellipsis (every axis consumed explicitly) selects nothing,
    /// but still separates the advanced indexers around it, so the broadcast
    /// dimensions move to the front (NumPy parity; regression 2026-10-08).
    #[test]
    fn test_zero_width_ellipsis() {
        crate::specify_test!("test_zero_width_ellipsis");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x = rt::arange((20, &device)).into_shape([4, 5]);
        let a = x.array_index((None, [0, 1, 2], Ellipsis, 2));
        assert_eq!(a.shape(), &vec![3, 1]);
        assert_eq!(a.into_shape([-1]).to_vec(), vec![2, 7, 12]);

        let t = rt::arange((60, &device)).into_shape([3, 4, 5]);
        let b = t.array_index((0..2, [0, 1], Ellipsis, [3, 2]));
        assert_eq!(b.shape(), &vec![2, 2]);
        assert_eq!(b.into_shape([-1]).to_vec(), vec![3, 23, 7, 27]);

        let y = rt::arange((18, &device)).into_shape([2, 3, 3]);
        let c = y.array_index((.., [0], Ellipsis, [1]));
        assert_eq!(c.shape(), &vec![1, 2]);
        assert_eq!(c.into_shape([-1]).to_vec(), vec![1, 10]);
    }

    #[test]
    fn test_edges() {
        crate::specify_test!("test_edges");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);

        // negative indices count from the back; duplicates are allowed
        assert_eq!(a.array_index([-1]).into_shape([-1]).to_vec(), vec![8, 9, 10, 11]);
        assert_eq!(a.array_index(([0, 0],)).shape(), &vec![2, 4]);

        // a zero-dimensional integer array is a scalar index (and gives a view)
        let idx0d_owner = rt::asarray((vec![2_isize], &device));
        let idx0d = idx0d_owner.i(0);
        let b = a.array_index((&idx0d,));
        assert_eq!(b.shape(), &vec![4]);
        assert!(!b.is_owned());

        // mixed basic + array indexers with a new axis
        let c = a.array_index((.., &rt::asarray((vec![0_isize, 2], &device))));
        assert_eq!(c.shape(), &vec![3, 2]);

        // an empty broadcast never touches the index arrays, so an entry that
        // is out of range but never gathered does not raise (NumPy parity)
        let big = rt::asarray(((0..24_isize).collect::<Vec<_>>(), &device)).into_shape([2, 3, 4]);
        let empty = rt::asarray((Vec::<isize>::new(), &device));
        assert_eq!(big.array_index((&empty, [99])).shape(), &vec![0, 4]);
        // ... whereas the same entry in a non-empty broadcast does raise
        assert!(is_index_error(&big.array_index_f(([0], [99])).unwrap_err()));

        // out of range / too many indexers
        let err = a.array_index_f([3]).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // too many indexers is also an IndexError (the Python exception kind)
        let err = a.array_index_f((1, 2, 3)).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
    }

    /// Non-contiguous and offset sources and index arrays (the kernel claims
    /// every layout may be strided; DECISIONS.md's test plan lists them).
    #[test]
    fn test_strided_sources_and_index_arrays() {
        crate::specify_test!("test_strided_sources_and_index_arrays");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let base = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let idx = rt::asarray((vec![3_isize, 0], &device));

        // a negative-stride source axis: flipped[..., [3, 0]] reads through the
        // reversed stride
        let flipped = base.i((.., slice!(None, None, -1), ..));
        assert_eq!(flipped.array_index((.., .., &idx)).into_shape([-1]).to_vec(), vec![
            11, 8, 7, 4, 3, 0, 23, 20, 19, 16, 15, 12
        ]);

        // a strided index array (reversed view): base[..., idx[::-1]] == base[..., [0, 3]]
        let idx_rev = idx.i(slice!(None, None, -1));
        assert_eq!(base.array_index((.., .., &idx_rev)).into_shape([-1]).to_vec(), vec![
            0, 3, 4, 7, 8, 11, 12, 15, 16, 19, 20, 23
        ]);

        // an offset (sliced) source on the indexed axis: cut[0, :, [2, 0]] == base[0, :, [3, 1]]
        let cut = base.i((.., .., 1..4));
        assert_equal(cut.array_index((0, .., [2, 0])), base.array_index((0, .., [3, 1])), None);

        // a transposed (non-monotonic-stride) source: tr[2] == base[:, :, 2].transpose()
        let tr = rt::permute_dims(&base, [2, 1, 0]);
        assert_eq!(tr.array_index((2, .., ..)).into_shape([-1]).to_vec(), vec![2, 14, 6, 18, 10, 22]);

        // the same index array in two memory representations (row-major and
        // column-major) gathers the same elements: a device reads the entries
        // through their layout, never assuming a row-major buffer
        let idx_2d = rt::asarray((vec![0_isize, 3, 1, 2], &device)).into_shape([2, 2]);
        let idx_2d_f =
            rt::change_contig(rt::asarray((vec![0_isize, 3, 1, 2], &device)).into_shape([2, 2]), ColMajor).into_owned();
        assert_ne!(idx_2d.stride(), idx_2d_f.stride());
        assert_equal(base.array_index((.., .., &idx_2d)), base.array_index((.., .., &idx_2d_f)), None);
    }

    /// The empty index `()` is the identity (and still a view); `None` is the
    /// per-axis new-axis indexer, not an alias of `()`.
    #[test]
    fn test_empty_and_none_index() {
        crate::specify_test!("test_empty_and_none_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);
        let identity = a.array_index(());
        assert_eq!(identity.shape(), &vec![3, 4]);
        assert!(!identity.is_owned());

        // `None` inserts an axis (as in basic slicing)
        assert_eq!(a.array_index(None).shape(), &vec![1, 3, 4]);
        // `Some(n)` is rejected instead of panicking inside `Indexer::from`
        let err = a.array_index_f(Some(2_usize)).unwrap_err();
        assert!(format!("{err}").contains("InvalidValue"), "expected an InvalidValue error, got {err}");
        // an integer selects (not inserts)
        assert_eq!(a.array_index(2).shape(), &vec![4]);
    }

    /// Differential check against NumPy.
    ///
    /// Every row of [`NUMPY_CASES`] is a case solved by NumPy (v2.5.2) with the
    /// generator that accompanies the task record
    /// (`rstsr-improve-trajectory/2026-10-08-array-indexing/case-generator/`);
    /// the rows are inlined here so that the core test tree stays free of
    /// external fixtures and Python regeneration steps.
    #[test]
    fn test_numpy_generated_diff() {
        crate::specify_test!("test_numpy_generated_diff");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        for (shape, spec, out_shape, values) in NUMPY_CASES {
            let shape = shape.split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
            let out_shape = if out_shape.is_empty() {
                vec![]
            } else {
                out_shape.split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>()
            };
            let values = if values.is_empty() {
                vec![]
            } else {
                values.split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>()
            };
            let case = format!("{shape:?};{spec}");
            let size = shape.iter().product::<usize>();
            let a = rt::asarray(((0..size as isize).collect::<Vec<_>>(), &device)).into_shape(shape);
            let out = a.array_index(parse_indexers(&device, spec));
            assert_eq!(out.shape(), &out_shape, "shape mismatch for case: {case}");
            assert_eq!(out.into_shape([-1]).to_vec(), values, "value mismatch for case: {case}");
        }
        assert!(NUMPY_CASES.len() >= 100, "expected a substantial case set, got {}", NUMPY_CASES.len());
    }
}
