// Most or all contents generated by AI (model deepseek-flash).
//! Derived array-indexing setters: `put_along_axis` (the inverse of
//! `take_along_axis`), `index_put` (the inverse of `index_select`) and
//! `mask_assign` (array-valued `x[mask] = value`).

#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

/// A row-major device from the entry binary's test device.
fn dev() -> DeviceType {
    let mut device = TESTCFG.device.clone();
    device.set_default_order(RowMajor);
    device
}

#[cfg(test)]
mod numpy_put_along_axis {
    use super::*;
    static FUNC: &str = "numpy_put_along_axis";

    #[test]
    fn test_put_along_axis() {
        // NumPy: `np.put_along_axis(arr, indices, values, axis)`.
        crate::specify_test!("test_put_along_axis");
        let device = dev();

        let mut a: Tensor<i32, _> = rt::zeros(([2, 3], &device));
        let idx = rt::tensor_from_nested!([[2isize, 0], [1, 1]], &device);
        let vals = rt::tensor_from_nested!([[10, 20], [30, 40]], &device);
        a.put_along_axis(&idx, &vals, -1);
        assert_eq!(a.into_shape([-1]).to_vec(), vec![20, 0, 10, 0, 40, 0]);

        // the values broadcast to the indices' shape
        let mut b: Tensor<i32, _> = rt::zeros(([2, 3], &device));
        b.put_along_axis(&idx, rt::tensor_from_nested!([[5], [6]], &device), 1);
        assert_eq!(b.into_shape([-1]).to_vec(), vec![5, 0, 5, 0, 6, 0]);
    }
}

#[cfg(test)]
mod custom_scatter {
    use super::*;
    static FUNC: &str = "custom_scatter";

    #[test]
    fn test_index_put() {
        crate::specify_test!("test_index_put");
        let device = dev();

        let mut a = rt::arange((6, &device)).into_shape([3, 2]);
        a.index_put(0, [0, 1], rt::tensor_from_nested!([[10, 11], [12, 13]], &device));
        assert_eq!(a.into_shape([-1]).to_vec(), vec![10, 11, 12, 13, 4, 5]);

        // duplicate indices: the last write wins
        let mut b = rt::arange((6, &device)).into_shape([3, 2]);
        b.index_put(0, [2, 2], rt::tensor_from_nested!([[1, 2], [3, 4]], &device));
        assert_eq!(b.into_shape([-1]).to_vec(), vec![0, 1, 2, 3, 3, 4]);

        // a broadcast column value
        let mut c: Tensor<f64, _> = rt::zeros(([3, 2], &device));
        c.index_put(1, [0, 1], rt::full(([3, 1], 5.0f64, &device)));
        assert_eq!(c.into_shape([-1]).to_vec(), vec![5., 5., 5., 5., 5., 5.]);
    }

    #[test]
    fn test_mask_assign() {
        crate::specify_test!("test_mask_assign");
        let device = dev();

        let mut a: Tensor<f64, _> = rt::zeros(([3, 2], &device));
        let mask = rt::asarray((vec![true, false, true], &device));
        a.mask_assign(&mask, rt::full(([2, 2], 1.5f64, &device)));
        assert_eq!(a.into_shape([-1]).to_vec(), vec![1.5, 1.5, 0.0, 0.0, 1.5, 1.5]);
    }

    #[test]
    fn test_errors() {
        crate::specify_test!("test_errors");
        let device = dev();

        // put_along_axis: index out of range (a is 2x3, index 9 on axis 1)
        let mut a: Tensor<i32, _> = rt::zeros(([2, 3], &device));
        let bad = rt::tensor_from_nested!([[9isize, 0], [1, 1]], &device);
        let vals: Tensor<i32, _> = rt::zeros(([2, 2], &device));
        assert!(a.put_along_axis_f(&bad, &vals, 1).is_err());
        // put_along_axis: indices must match the tensor outside the axis
        // (a's axis 0 is 2, the indices' axis 0 is 3)
        let wrong: Tensor<isize, _> = rt::zeros(([3, 2], &device));
        let wvals: Tensor<i32, _> = rt::zeros(([3, 2], &device));
        assert!(a.put_along_axis_f(&wrong, &wvals, 1).is_err());
    }
}
