// Most or all contents generated by AI (model deepseek-flash).
//! array_index tests: NumPy-cited array-indexing (fancy indexing) contract,
//! placement-rule cases from the NumPy indexing guide, a NumPy-generated
//! differential set inlined as [`NUMPY_CASES`], and the device-order behavior
//! of the placement rule in [`device_order`].

#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

/// Parse the index spec of a generated case: tokens separated by `|`, each of
/// `I<n>` (integer), `S<a>:<b>:<c>` (slice), `A<d0>x..:<v..>` (index array),
/// `N` (new axis) or `E` (ellipsis).
fn parse_indexers(device: &DeviceType, spec: &str) -> ArrayIndexArgs<DeviceType> {
    let parse_opt = |s: &str| -> Option<isize> {
        if s.is_empty() {
            None
        } else {
            Some(s.parse().unwrap())
        }
    };
    let mut indexers: Vec<ArrayIndexer<DeviceType>> = Vec::new();
    for token in spec.split('|') {
        if token.is_empty() {
            continue;
        }
        match &token[..1] {
            "I" => indexers.push(ArrayIndexer::Basic(Indexer::Select(token[1..].parse().unwrap()))),
            "S" => {
                let parts = token[1..].split(':').collect::<Vec<_>>();
                let slice = SliceI::new(
                    parse_opt(parts.first().copied().unwrap_or("")),
                    parse_opt(parts.get(1).copied().unwrap_or("")),
                    parse_opt(parts.get(2).copied().unwrap_or("")),
                );
                indexers.push(ArrayIndexer::Basic(Indexer::Slice(slice)));
            },
            "A" => {
                let (shape_txt, values_txt) = token[1..].split_once(':').unwrap();
                let shape = shape_txt.split('x').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
                let values = values_txt.split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>();
                let index = rt::asarray((values, device)).into_shape(shape);
                indexers.push(ArrayIndexer::ArrayIndex(index));
            },
            "N" => indexers.push(ArrayIndexer::Basic(Indexer::Insert)),
            "E" => indexers.push(ArrayIndexer::Basic(Indexer::Ellipsis)),
            other => panic!("invalid index token `{other}` in case spec `{spec}`"),
        }
    }
    ArrayIndexArgs::new(indexers)
}

/// `true` when the error is an `IndexError` — the kind NumPy raises for a bad
/// index (and the kind the rstsr-faer-py shim maps to Python's `IndexError`).
fn is_index_error(err: &rt::Error) -> bool {
    matches!(err.inner, rstsr_core::prelude_dev::RSTSRError::IndexError(_))
}

#[cfg(test)]
mod numpy_array_index {
    use super::*;
    static FUNC: &str = "numpy_array_index";

    #[test]
    fn test_empty_fancy_index() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_empty_fancy_index (L127)
        crate::specify_test!("test_empty_fancy_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((3, &device));
        let empty = rt::asarray((Vec::<isize>::new(), &device));
        // `assert_equal(a[[]], [])` — an empty index array gives an empty result
        let b = a.array_index(&empty);
        assert_eq!(b.shape(), &vec![0]);
        assert_eq!(b.into_shape([-1]).to_vec(), Vec::<i32>::new());
        // `assert_equal(a[[]].dtype, a.dtype)` — dtype preservation is
        // structural in rstsr: the result element type is the input's `T`.
        // `b = np.array([]); assert_raises(IndexError, a.__getitem__, b)` is
        // type-level N/A: rstsr index tensors are typed `isize`.

        // an empty index array on a higher-rank tensor keeps the trailing axes
        let c = rt::arange((12, &device)).into_shape([3, 4]);
        let d = c.array_index((&empty,));
        assert_eq!(d.shape(), &vec![0, 4]);
    }

    #[test]
    fn test_broaderrors_indexing() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_broaderrors_indexing
        // (L365)
        crate::specify_test!("test_broaderrors_indexing");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<f64, _> = rt::zeros(([5, 5], &device));
        // `assert_raises(IndexError, a.__getitem__, ([0, 1], [0, 1, 2]))`
        let err = a.array_index_f(([0, 1], [0, 1, 2])).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // `assert_raises(IndexError, a.__setitem__, ([0, 1], [0, 1, 2]), 0)` is
        // covered by `test_array_index_assign::numpy_array_index_assign::
        // test_broaderrors_indexing_setitem`.
    }

    #[test]
    fn test_nontuple_ndindex() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_nontuple_ndindex (L612)
        // A bare list indexes the first axis (`a[[0,1]]` is a row list), while
        // a tuple zips index arrays. The `a[[slice(None)]]` IndexError case is
        // N/A: Rust has no list-of-slice literal (a host list is a single
        // one-dimensional index array).
        crate::specify_test!("test_nontuple_ndindex");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((25, &device)).into_shape([5, 5]);
        // `assert_equal(a[[0, 1]], np.array([a[0], a[1]]))`
        assert_equal(a.array_index([0, 1]), a.slice((0..2, ..)), None);
        // `assert_equal(a[[0, 1], [0, 1]], np.array([0, 6]))`
        assert_eq!(a.array_index(([0, 1], [0, 1])).into_shape([-1]).to_vec(), vec![0, 6]);
    }
}

/// NumPy-solved array-indexing cases: `(tensor shape, index spec, out shape, out values)`.
///
/// Generated 2026-10-08 from NumPy v2.5.2 by the generator kept with the task
/// record (rstsr-improve-trajectory/2026-10-08-array-indexing/case-generator/):
/// 130 rows,
/// covering mixed basic + array indexers, mutual broadcasting, negative and
/// duplicated entries, empty index arrays, new axes and both full-width and
/// zero-width ellipses. The spec format is documented on [`parse_indexers`].
#[rustfmt::skip]
static NUMPY_CASES: &[(&str, &str, &str, &str)] = &[
    ("1", "A2x1:-1,-1", "2,1", "0,0"),
    ("1", "I-1", "", "0"),
    ("1", "I0", "", "0"),
    ("1", "S0:1:-1", "0", ""),
    ("1,1", "A1:-1|S0:0:1|E|N", "1,0,1", ""),
    ("1,1,5", "E|S1:0:2|N", "1,1,0,1", ""),
    ("1,2", "E|A2:0,0|S2:2:2", "2,0", ""),
    ("1,2", "S0:1:1|I-1", "1", "1"),
    ("1,2,5", "E|S1:0:2", "1,2,0", ""),
    ("1,3,1", "I-1|N|E|I-1|I-1", "1", "2"),
    ("1,3,4", "I-1|S2:0:2|I-1|E", "0", ""),
    ("1,3,5", "S-1:-1:-1|E|N", "0,3,5,1", ""),
    ("1,4,1", "A1x1:0|S0:2:1|A2:0,0|N", "1,2,2,1", "0,1,0,1"),
    ("1,4,1", "S-1:1:-2|S1:1:2|E|I-1", "0,0", ""),
    ("1,4,2,5", "I-1|E", "4,2,5", "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39"),
    ("1,4,3", "S1:1:1|E", "0,4,3", ""),
    ("1,5", "A2x2:0,0,0,0|I-2|E", "2,2", "3,3,3,3"),
    ("1,5", "A3x1:0,0,0|S2:2:1|N", "3,1,0,1", ""),
    ("1,5", "S1:0:1|A1:0|E", "0,1", ""),
    ("1,5,4,4", "E|I-1|I-3|S1:1:1|S1:1:1", "0,0", ""),
    ("1,5,5,4", "I-1|A2:0,3|S5:0:1|I-4|E", "2,0", ""),
    ("2", "A1:1", "1", "1"),
    ("2", "A1x3:1,0,0", "1,3", "1,0,0"),
    ("2", "I1", "", "1"),
    ("2", "S0:2:1", "2", "0,1"),
    ("2", "S2:0:1", "0", ""),
    ("2,1", "E|A2:1,1|S-1:-2:-2", "2,1", "1,1"),
    ("2,1", "E|S-1:-2:-1|N", "2,1,1", "0,1"),
    ("2,1", "I-2|E|N", "1,1", "0"),
    ("2,1,1", "E|I0|I-1|N", "2,1", "0,1"),
    ("2,1,2,5", "E|I1|I0", "2,1", "5,15"),
    ("2,1,3", "S2:1:2|A3:-1,-1,-1|E|I-1", "3,0", ""),
    ("2,1,5,1", "S-1:2:-2|I-1|E", "0,5,1", ""),
    ("2,1,5,3", "A2x3:-1,-2,-1,-1,-1,-1|N|I0|I-4|S1:3:1", "2,3,1,2", "19,20,4,5,19,20,19,20,19,20,19,20"),
    ("2,2,1,4", "A1:-1|I-1|N|I-1|E", "1,1,4", "12,13,14,15"),
    ("2,3", "E|S-1:-2:-2|I-1", "1", "5"),
    ("2,3", "S1:1:1|E|I-2", "0", ""),
    ("2,3,1,1", "S0:0:2|I-1|E|I0|I-1", "0", ""),
    ("2,3,2", "I1|E|A2:2,2|A2x1:0,1", "2,2", "10,10,11,11"),
    ("2,3,5,3", "I-1|A3:-1,-2,-2|E|A1:0", "3,5", "75,78,81,84,87,60,63,66,69,72,60,63,66,69,72"),
    ("2,4", "A1:1|I3", "1", "7"),
    ("2,4,1,4", "S2:1:2|E|S3:0:1|A2x1:-1,-1|N", "0,4,0,2,1,1", ""),
    ("2,4,4", "I-1|N|A3:-3,-3,-4|S0:0:-1", "3,1,0", ""),
    ("2,4,4", "I1|E", "4,4", "16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31"),
    ("2,4,4,3", "E|S2:0:1|I-2", "2,4,0", ""),
    ("2,5", "S2:0:2|E|A1:-2", "0,1", ""),
    ("2,5,2,1", "A1x2:1,1|E|I0|A1x1:0|N", "1,2,5,1", "10,12,14,16,18,10,12,14,16,18"),
    ("2,5,2,1", "A3x2:-2,-1,-1,-2,-1,-2|S4:-5:-2|N|I-2|E|N", "3,2,2,1,1,1", "8,4,18,14,18,14,8,4,18,14,8,4"),
    ("2,5,4", "A3:0,0,0|E", "3,5,4", "0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19"),
    ("3", "A3x3:-1,-3,-3,-2,-1,-2,-2,-2,-1|N", "3,3,1", "2,0,0,1,2,1,1,1,2"),
    ("3", "I-2", "", "1"),
    ("3", "I1", "", "1"),
    ("3", "S2:0:1|N", "0,1", ""),
    ("3", "S3:1:1", "0", ""),
    ("3,1", "I-1|N|I-1", "1", "2"),
    ("3,1,3", "A2:1,2|I0|I-3", "2", "3,6"),
    ("3,1,4,2", "I1|S0:1:1|E|N", "1,4,2,1", "8,9,10,11,12,13,14,15"),
    ("3,2,2", "E|S0:2:1|N|A3x2:0,1,1,1,0,0", "3,2,1,3,2", "0,1,1,1,0,0,2,3,3,3,2,2,4,5,5,5,4,4,6,7,7,7,6,6,8,9,9,9,8,8,10,11,11,11,10,10"),
    ("3,2,2", "I1|E|I0", "2", "4,6"),
    ("3,2,3,2", "I2|S0:2:-1|A2x3:-3,-1,-2,-1,-2,-3|I-2", "2,3,0", ""),
    ("3,2,3,5", "A2x1:1,2|A2x1:-1,-1|N|S2:0:1|I-4|N", "2,1,1,0,1", ""),
    ("3,2,5", "A1:2|S1:0:1|E", "1,0,5", ""),
    ("3,3", "A3x3:0,1,1,2,0,1,2,2,1|E|S1:1:1", "3,3,0", ""),
    ("3,3", "I0|E", "3", "0,1,2"),
    ("3,3", "S0:2:1|S2:2:1|E", "2,0", ""),
    ("3,3,2,2", "I-2|S2:-3:-1|A2x2:-2,-1,-1,-2|I1", "2,2,2", "21,17,23,19,23,19,21,17"),
    ("3,4", "A2:-1,-1|A2:1,3", "2", "9,11"),
    ("3,4", "A2:1,1|E|A1x1:3", "1,2", "7,7"),
    ("3,4", "S0:2:1|A2:2,2", "2,2", "2,2,6,6"),
    ("3,4,1", "A1:-3|I-1|A3:0,0,0", "3", "3,3,3"),
    ("3,4,1,4", "S-1:1:-2|A1:3|N|S0:-2:-1|S0:0:-2", "1,1,1,1,0", ""),
    ("3,4,2,3", "S3:0:1|A2x1:1,0|S0:2:2|I-3", "2,1,0,1", ""),
    ("3,5", "A1x2:-2,-3|E|I0", "1,2", "5,0"),
    ("3,5", "A2:2,0|E", "2,5", "10,11,12,13,14,0,1,2,3,4"),
    ("3,5", "E|A1x3:0,0,0|I-5", "1,3", "0,0,0"),
    ("3,5", "S3:3:2|A2x1:3,0", "0,2,1", ""),
    ("3,5,1", "A2:2,0|E|S4:3:1|S1:1:2", "2,0,0", ""),
    ("4", "I-2", "", "2"),
    ("4", "I3", "", "3"),
    ("4", "S-2:2:-1|N", "0,1", ""),
    ("4,1,3", "S1:3:1|S0:0:1|S3:1:1|N", "2,0,0,1", ""),
    ("4,2", "A1x3:0,3,1|E|N|S1:2:1", "1,3,1,1", "1,7,3"),
    ("4,2", "E|I-1", "4", "1,3,5,7"),
    ("4,2", "I-3|I-1|E", "", "3"),
    ("4,2,3,3", "E|A2:0,2|S0:0:1|I-3|I-1", "2,0", ""),
    ("4,2,4,5", "I-2|I-2|I-2|N|I-5", "1", "90"),
    ("4,2,5,4", "S3:3:1|I0|E", "0,5,4", ""),
    ("4,2,5,5", "A1x2:0,3|S0:0:1|A1:3|E", "1,2,0,5", ""),
    ("4,3", "E|A3x3:1,1,0,3,2,1,0,3,3|I-3", "3,3", "3,3,0,9,6,3,0,9,9"),
    ("4,3", "E|S3:-2:-1|S2:0:1", "1,0", ""),
    ("4,3", "I-4|E|N", "3,1", "0,1,2"),
    ("4,3", "I1|E|N", "3,1", "3,4,5"),
    ("4,3,4,2", "A2:1,1|I0|E|S0:0:1", "2,4,0", ""),
    ("4,4", "A1:-2|I3|E", "1", "11"),
    ("4,4", "I3|E", "4", "12,13,14,15"),
    ("4,4", "I3|I3", "", "15"),
    ("4,4,1,2", "I-2|E|S3:1:1|I-1|S2:2:2", "0,0", ""),
    ("4,4,1,3", "A3x2:-2,-3,-2,-4,-4,-1|E", "3,2,4,1,3", "24,25,26,27,28,29,30,31,32,33,34,35,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,0,1,2,3,4,5,6,7,8,9,10,11,0,1,2,3,4,5,6,7,8,9,10,11,36,37,38,39,40,41,42,43,44,45,46,47"),
    ("4,4,2,5", "I-4|A2:3,2|A1x2:-1,-1|E|N", "1,2,5,1", "35,36,37,38,39,25,26,27,28,29"),
    ("4,5", "E|S3:1:1", "4,0", ""),
    ("4,5,1", "S2:3:1|A3:-3,-2,-1|A3x1:0,0,0", "1,3,3", "12,13,14,12,13,14,12,13,14"),
    ("4,5,2", "A3x3:-1,-2,-4,-4,-3,-3,-2,-2,-1|E", "3,3,5,2", "30,31,32,33,34,35,36,37,38,39,20,21,22,23,24,25,26,27,28,29,0,1,2,3,4,5,6,7,8,9,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39"),
    ("5", "S4:5:1", "1", "4"),
    ("5,1", "A2:3,2|E", "2,1", "3,2"),
    ("5,1", "E|S4:2:1", "5,0", ""),
    ("5,1", "S5:4:1|N|E", "0,1,1", ""),
    ("5,1,1,3", "S3:5:1|E|I0|A1x3:-1,-1,-1|I-1", "2,1,3", "11,11,11,14,14,14"),
    ("5,1,2,2", "E|I-1", "5,1,2", "1,3,5,7,9,11,13,15,17,19"),
    ("5,1,3", "A1x3:0,0,2|I-1|A3:2,0,1|E", "1,3", "2,0,7"),
    ("5,1,3,2", "I-1|N|I-1|E", "1,3,2", "24,25,26,27,28,29"),
    ("5,1,4,2", "A2x1:-4,-3|E", "2,1,1,4,2", "8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23"),
    ("5,2", "E|S3:3:2", "5,0", ""),
    ("5,2", "S4:1:2|A1x2:0,0", "0,1,2", ""),
    ("5,2,1,2", "E|I-5|A2x3:0,0,1,0,0,1|S1:1:1|S0:0:2", "2,3,0,0", ""),
    ("5,2,4", "A2:0,3|E|N|I0", "2,2,1", "0,4,24,28"),
    ("5,2,4", "S0:2:2|N|I0|S0:2:1", "1,1,2", "0,1"),
    ("5,2,4", "S3:3:-2|E|S0:1:2|I1", "0,1", ""),
    ("5,2,5", "I3|E|S1:1:1|I-4", "0", ""),
    ("5,3", "I-5|S1:1:1", "0", ""),
    ("5,3", "I1|E|N", "3,1", "3,4,5"),
    ("5,3", "S0:2:1|E", "2,3", "0,1,2,3,4,5"),
    ("5,3,1,3", "S5:1:1|S2:3:1|N|E|A1:0", "0,1,1,1,1", ""),
    ("5,3,5", "I-5|A1:-2|E", "1,5", "5,6,7,8,9"),
    ("5,4", "A1x2:4,4|E", "1,2,4", "16,17,18,19,16,17,18,19"),
    ("5,4", "S2:3:2|E", "1,4", "8,9,10,11"),
    ("5,4,3", "S0:1:1|E|I2", "1,4", "2,5,8,11"),
    ("5,4,3,1", "A2x1:2,0|I0|N|I-1|I0", "2,1,1", "26,2"),
    ("5,5", "I2|E", "5", "10,11,12,13,14"),
    ("5,5", "I3|N|I-5", "1", "15"),
    ("5,5,2", "A3x3:0,2,3,1,4,0,2,3,2|I1|I-2", "3,3", "2,22,32,12,42,2,22,32,22"),
];

#[cfg(test)]
mod custom_array_index {
    use super::*;
    static FUNC: &str = "custom_array_index";

    #[test]
    fn test_placement_rule_examples() {
        crate::specify_test!("test_placement_rule_examples");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // the examples of NumPy's indexing guide ("Advanced Indexing"): one
        // contiguous advanced run broadcasts in place, separated index arrays
        // move the broadcast dimensions to the front
        let x = rt::arange((10 * 20 * 30, &device)).into_shape([10, 20, 30]);
        let ind = rt::asarray(((0..10_isize).collect::<Vec<_>>(), &device));

        // `x[:, ind, ind]`: contiguous advanced run -> in place
        let z = x.array_index((.., &ind, &ind));
        assert_eq!(z.shape(), &vec![10, 10]);
        assert_eq!(z.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 31, 62]);

        // `x[ind, :, ind]`: the advanced run is separated by a slice -> front
        let y = x.array_index((&ind, .., &ind));
        assert_eq!(y.shape(), &vec![10, 20]);
        assert_eq!(y.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 30, 60]);
    }

    #[test]
    fn test_placement_rule_4d() {
        crate::specify_test!("test_placement_rule_4d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let f = rt::arange((2 * 3 * 4 * 5, &device)).into_shape([2, 3, 4, 5]);
        let i01 = rt::asarray((vec![1_isize, 0], &device));
        let i43 = rt::asarray((vec![4_isize, 3], &device));

        // `f[[1,0], :, :, [4,3]]`: arrays separated by two slices -> front
        assert_eq!(f.array_index((&i01, Ellipsis, &i43)).shape(), &vec![2, 3, 4]);
        // `f[:, [1,0], :, [4,3]]`: separated -> front (after nothing)
        assert_eq!(f.array_index((.., &i01, .., &i43)).shape(), &vec![2, 2, 4]);
        // `f[[1,0], :, 1, :]`: integer counts as advanced for the grouping
        assert_eq!(f.array_index((&i01, .., 1, ..)).shape(), &vec![2, 3, 5]);
        // `f[:, [1,0], 1, :]`: a single contiguous advanced run -> in place
        assert_eq!(f.array_index((.., &i01, 1, ..)).shape(), &vec![2, 2, 5]);
    }

    /// A zero-width ellipsis (every axis consumed explicitly) selects nothing,
    /// but still separates the advanced indexers around it, so the broadcast
    /// dimensions move to the front (NumPy parity; regression 2026-10-08).
    #[test]
    fn test_zero_width_ellipsis() {
        crate::specify_test!("test_zero_width_ellipsis");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x = rt::arange((20, &device)).into_shape([4, 5]);
        let a = x.array_index((None, [0, 1, 2], Ellipsis, 2));
        assert_eq!(a.shape(), &vec![3, 1]);
        assert_eq!(a.into_shape([-1]).to_vec(), vec![2, 7, 12]);

        let t = rt::arange((60, &device)).into_shape([3, 4, 5]);
        let b = t.array_index((0..2, [0, 1], Ellipsis, [3, 2]));
        assert_eq!(b.shape(), &vec![2, 2]);
        assert_eq!(b.into_shape([-1]).to_vec(), vec![3, 23, 7, 27]);

        let y = rt::arange((18, &device)).into_shape([2, 3, 3]);
        let c = y.array_index((.., [0], Ellipsis, [1]));
        assert_eq!(c.shape(), &vec![1, 2]);
        assert_eq!(c.into_shape([-1]).to_vec(), vec![1, 10]);
    }

    #[test]
    fn test_edges() {
        crate::specify_test!("test_edges");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);

        // negative indices count from the back; duplicates are allowed
        assert_eq!(a.array_index([-1]).into_shape([-1]).to_vec(), vec![8, 9, 10, 11]);
        assert_eq!(a.array_index(([0, 0],)).shape(), &vec![2, 4]);

        // a zero-dimensional integer array is a scalar index (and gives a view)
        let idx0d_owner = rt::asarray((vec![2_isize], &device));
        let idx0d = idx0d_owner.i(0);
        let b = a.array_index((&idx0d,));
        assert_eq!(b.shape(), &vec![4]);
        assert!(!b.is_owned());

        // mixed basic + array indexers with a new axis
        let c = a.array_index((.., &rt::asarray((vec![0_isize, 2], &device))));
        assert_eq!(c.shape(), &vec![3, 2]);

        // an empty broadcast never touches the index arrays, so an entry that
        // is out of range but never gathered does not raise (NumPy parity)
        let big = rt::asarray(((0..24_isize).collect::<Vec<_>>(), &device)).into_shape([2, 3, 4]);
        let empty = rt::asarray((Vec::<isize>::new(), &device));
        assert_eq!(big.array_index((&empty, [99])).shape(), &vec![0, 4]);
        // ... whereas the same entry in a non-empty broadcast does raise
        assert!(is_index_error(&big.array_index_f(([0], [99])).unwrap_err()));

        // out of range / too many indexers
        let err = a.array_index_f([3]).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // the most negative index stays an IndexError, not an arithmetic overflow
        let err = a.array_index_f([isize::MIN]).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
        // too many indexers is also an IndexError (the Python exception kind)
        let err = a.array_index_f((1, 2, 3)).unwrap_err();
        assert!(is_index_error(&err), "expected an IndexError, got {err}");
    }

    /// Non-contiguous and offset sources and index arrays (the kernel claims
    /// every layout may be strided; DECISIONS.md's test plan lists them).
    #[test]
    fn test_strided_sources_and_index_arrays() {
        crate::specify_test!("test_strided_sources_and_index_arrays");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let base = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let idx = rt::asarray((vec![3_isize, 0], &device));

        // a negative-stride source axis: flipped[..., [3, 0]] reads through the
        // reversed stride
        let flipped = base.i((.., slice!(None, None, -1), ..));
        assert_eq!(flipped.array_index((.., .., &idx)).into_shape([-1]).to_vec(), vec![
            11, 8, 7, 4, 3, 0, 23, 20, 19, 16, 15, 12
        ]);

        // a strided index array (reversed view): base[..., idx[::-1]] == base[..., [0, 3]]
        let idx_rev = idx.i(slice!(None, None, -1));
        assert_eq!(base.array_index((.., .., &idx_rev)).into_shape([-1]).to_vec(), vec![
            0, 3, 4, 7, 8, 11, 12, 15, 16, 19, 20, 23
        ]);

        // an offset (sliced) source on the indexed axis: cut[0, :, [2, 0]] == base[0, :, [3, 1]]
        let cut = base.i((.., .., 1..4));
        assert_equal(cut.array_index((0, .., [2, 0])), base.array_index((0, .., [3, 1])), None);

        // a transposed (non-monotonic-stride) source: tr[2] == base[:, :, 2].transpose()
        let tr = rt::permute_dims(&base, [2, 1, 0]);
        assert_eq!(tr.array_index((2, .., ..)).into_shape([-1]).to_vec(), vec![2, 14, 6, 18, 10, 22]);

        // the same index array in two memory representations (row-major and
        // column-major) gathers the same elements: a device reads the entries
        // through their layout, never assuming a row-major buffer
        let idx_2d = rt::asarray((vec![0_isize, 3, 1, 2], &device)).into_shape([2, 2]);
        let idx_2d_f =
            rt::change_contig(rt::asarray((vec![0_isize, 3, 1, 2], &device)).into_shape([2, 2]), ColMajor).into_owned();
        assert_ne!(idx_2d.stride(), idx_2d_f.stride());
        assert_equal(base.array_index((.., .., &idx_2d)), base.array_index((.., .., &idx_2d_f)), None);
    }

    /// The empty index `()` is the identity (and still a view); `None` is the
    /// per-axis new-axis indexer, not an alias of `()`.
    #[test]
    fn test_empty_and_none_index() {
        crate::specify_test!("test_empty_and_none_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);
        let identity = a.array_index(());
        assert_eq!(identity.shape(), &vec![3, 4]);
        assert!(!identity.is_owned());

        // `None` inserts an axis (as in basic slicing)
        assert_eq!(a.array_index(None).shape(), &vec![1, 3, 4]);
        // `Some(n)` is rejected instead of panicking inside `Indexer::from`
        let err = a.array_index_f(Some(2_usize)).unwrap_err();
        assert!(format!("{err}").contains("InvalidValue"), "expected an InvalidValue error, got {err}");
        // an integer selects (not inserts)
        assert_eq!(a.array_index(2).shape(), &vec![4]);
    }

    /// Boolean index arrays in a tuple: a mask is exactly its `nonzero`
    /// coordinates — it consumes `ndim(mask)` axes and contributes one
    /// `(count,)` block, so the placement rule and the mutual broadcast apply
    /// to it as to an integer index array of the same coordinates. A
    /// zero-dimensional boolean is declined.
    ///
    /// NumPy 2.5.1 cross-checked.
    #[test]
    fn test_boolean_index_arrays() {
        crate::specify_test!("test_boolean_index_arrays");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // `a[1:3, [True, False, False, True, False]]` -> (2, 2, 5)
        // `a[1:3, [True, False, False, True, False],
        //       [False, True, False, True, False]]` -> [[26, 43], [51, 68]]
        let a = rt::arange((75, &device)).into_shape([3, 5, 5]);
        let m1 = rt::asarray((vec![true, false, false, true, false], &device));
        let m2 = rt::asarray((vec![false, true, false, true, false], &device));

        let b = a.array_index((1..3, &m1));
        assert_eq!(b.shape(), &vec![2, 2, 5]);
        assert_eq!(b.into_shape([-1]).to_vec(), vec![
            25, 26, 27, 28, 29, 40, 41, 42, 43, 44, 50, 51, 52, 53, 54, 65, 66, 67, 68, 69
        ]);
        // the same as the integer nonzero coordinates
        assert_equal(a.array_index((1..3, [0, 3])), a.array_index((1..3, &m1)), None);

        let c = a.array_index((1..3, &m1, &m2));
        assert_eq!(c.shape(), &vec![2, 2]);
        assert_eq!(c.into_shape([-1]).to_vec(), vec![26, 43, 51, 68]);
        assert_equal(a.array_index((1..3, [0, 3], [1, 3])), a.array_index((1..3, &m1, &m2)), None);

        // `a[[True, False, True], :, 0]` -> (2, 5): a mask and a plain integer
        // across a slice are apart, so the block moves to the front
        let m0 = rt::asarray((vec![true, false, true], &device));
        let d = a.array_index((&m0, .., 0));
        assert_eq!(d.shape(), &vec![2, 5]);
        assert_eq!(d.into_shape([-1]).to_vec(), vec![0, 5, 10, 15, 20, 50, 55, 60, 65, 70]);

        // an n-dimensional mask consumes `ndim(mask)` axes and contributes one
        // (count,) block: `b3[mask2d]` -> (2, 4), the mask's two true entries
        let b3 = rt::arange((100, &device)).into_shape([5, 5, 4]);
        let mut mask_data = vec![false; 25];
        mask_data[3] = true; // (0, 3)
        mask_data[17] = true; // (3, 2)
        let mask2d = rt::asarray((mask_data, &device)).into_shape([5, 5]);
        let e = b3.array_index((&mask2d,));
        assert_eq!(e.shape(), &vec![2, 4]);
        assert_eq!(e.into_shape([-1]).to_vec(), vec![12, 13, 14, 15, 68, 69, 70, 71]);
        // the mask is its `nonzero` coordinates (host-listed here)
        let nz = rt::nonzero(&mask2d);
        let i0: Vec<isize> = nz[0].to_vec().into_iter().map(|v| v as isize).collect();
        let i1: Vec<isize> = nz[1].to_vec().into_iter().map(|v| v as isize).collect();
        assert_equal(b3.array_index((&i0, &i1)), b3.array_index((&mask2d,)), None);
        // ... and slices around it keep the mask in place: `c4[:, mask2d]`
        // -> (3, 2, 4)
        let c4 = rt::arange((300, &device)).into_shape([3, 5, 5, 4]);
        assert_eq!(c4.array_index((.., &mask2d)).shape(), &vec![3, 2, 4]);

        // a mask after an ellipsis, and one displaced from a plain integer:
        // the placement rule is unchanged
        // NumPy: `x[..., m]` -> (2, 3, 2); `x[0, ..., m]` -> (2, 3)
        let x = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let mx = rt::asarray((vec![true, false, true, false], &device));
        let f = x.array_index((.., .., &mx));
        assert_eq!(f.shape(), &vec![2, 3, 2]);
        assert_eq!(f.into_shape([-1]).to_vec(), vec![0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22]);
        let g = x.array_index((0, .., &mx));
        assert_eq!(g.shape(), &vec![2, 3]);
        assert_eq!(g.into_shape([-1]).to_vec(), vec![0, 4, 8, 2, 6, 10]);

        // `a[:, [True, False, False, True, False], 0]` -> (3, 2): the mask and
        // the plain integer are consecutive, so the block stays in place
        let h = a.array_index((.., &m1, 0));
        assert_eq!(h.shape(), &vec![3, 2]);
        assert_eq!(h.into_shape([-1]).to_vec(), vec![0, 15, 25, 40, 50, 65]);

        // the mask's count joins the mutual broadcast as a (count,) array: a
        // single true broadcasts against (2, 2) index arrays
        // NumPy: `x[[True, False], [[1, 2], [0, 1]], [[3, 0], [2, 1]]]` -> (2, 2)
        let m0x = rt::asarray((vec![true, false], &device));
        let i1 = rt::asarray((vec![1_isize, 2, 0, 1], &device)).into_shape([2, 2]);
        let i2 = rt::asarray((vec![3_isize, 0, 2, 1], &device)).into_shape([2, 2]);
        let j = x.array_index((&m0x, &i1, &i2));
        assert_eq!(j.shape(), &vec![2, 2]);
        assert_eq!(j.into_shape([-1]).to_vec(), vec![7, 8, 2, 5]);
        assert_equal(x.array_index(([0], &i1, &i2)), x.array_index((&m0x, &i1, &i2)), None);

        // the mask axes must match the indexed axes exactly (no broadcasting)
        let short = rt::asarray((vec![true, false, false, true], &device));
        assert!(is_index_error(&a.array_index_f((1..3, &short)).unwrap_err()));
        // a zero-size mask axis is allowed and selects nothing (NumPy)
        let none = rt::asarray((Vec::<bool>::new(), &device));
        assert_eq!(a.array_index((1..3, &none)).shape(), &vec![2, 0, 5]);

        // a zero-dimensional boolean would add a {0,1}-sized block without
        // consuming an axis; declined here
        let scalar_owner = rt::asarray((vec![true], &device));
        let scalar = scalar_owner.i(0);
        assert!(a.array_index_f((1..3, &scalar)).is_err());
    }

    /// Differential check against NumPy.
    ///
    /// Every row of [`NUMPY_CASES`] is a case solved by NumPy (v2.5.2) with the
    /// generator that accompanies the task record
    /// (`rstsr-improve-trajectory/2026-10-08-array-indexing/case-generator/`);
    /// the rows are inlined here so that the core test tree stays free of
    /// external fixtures and Python regeneration steps.
    #[test]
    fn test_numpy_generated_diff() {
        crate::specify_test!("test_numpy_generated_diff");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        for (shape, spec, out_shape, values) in NUMPY_CASES {
            let shape = shape.split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
            let out_shape = if out_shape.is_empty() {
                vec![]
            } else {
                out_shape.split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>()
            };
            let values = if values.is_empty() {
                vec![]
            } else {
                values.split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>()
            };
            let case = format!("{shape:?};{spec}");
            let size = shape.iter().product::<usize>();
            let a = rt::asarray(((0..size as isize).collect::<Vec<_>>(), &device)).into_shape(shape);
            let out = a.array_index(parse_indexers(&device, spec));
            assert_eq!(out.shape(), &out_shape, "shape mismatch for case: {case}");
            assert_eq!(out.into_shape([-1]).to_vec(), values, "value mismatch for case: {case}");
        }
        assert!(NUMPY_CASES.len() >= 100, "expected a substantial case set, got {}", NUMPY_CASES.len());
    }
}

/// Device-order behavior of `array_index` — rstsr's own convention, recorded
/// as the `col-major-transfer` entry of `tracking/numpy_differences.md`, not
/// NumPy parity (NumPy is C-order). The row-major column of every table below
/// matches NumPy; the column-major column is the registered divergence.
#[cfg(test)]
mod device_order {
    use super::*;
    static FUNC: &str = "device_order";

    /// Column-major reading of a row-major flat sequence of the given shape.
    fn f_order(c_seq: &[i32], shape: &[usize]) -> Vec<i32> {
        let mut out = Vec::with_capacity(c_seq.len());
        let mut multi = vec![0_usize; shape.len()];
        for _ in 0..c_seq.len() {
            let mut off = 0_usize;
            let mut stride = 1_usize;
            for d in (0..shape.len()).rev() {
                off += multi[d] * stride;
                stride *= shape[d];
            }
            out.push(c_seq[off]);
            // first axis fastest (column-major reading)
            for d in 0..shape.len() {
                multi[d] += 1;
                if multi[d] < shape[d] {
                    break;
                }
                multi[d] = 0;
            }
        }
        out
    }

    /// `a[i, j, k] = 12*i + 4*j + k` on `device`, built by broadcasting so that
    /// every device holds the *same* logical tensor whatever its order.
    fn build_input_2x3x4(device: &DeviceType) -> Tensor<i32, DeviceType, IxD> {
        let i = rt::arange((2, device)).into_shape([2, 1, 1]);
        let j = rt::arange((3, device)).into_shape([1, 3, 1]);
        let k = rt::arange((4, device)).into_shape([1, 1, 4]);
        i * 12 + j * 4 + k
    }

    /// `a[i, j, k, l] = 16*i + 8*j + 4*k + l` on `device` (broadcast build).
    fn build_input_3x2x2x4(device: &DeviceType) -> Tensor<i32, DeviceType, IxD> {
        let i = rt::arange((3, device)).into_shape([3, 1, 1, 1]);
        let j = rt::arange((2, device)).into_shape([1, 2, 1, 1]);
        let k = rt::arange((2, device)).into_shape([1, 1, 2, 1]);
        let l = rt::arange((4, device)).into_shape([1, 1, 1, 4]);
        i * 16 + j * 8 + k * 4 + l
    }

    /// `arange(2520).reshape(3, 4, 5, 6, 7)` on `device`, i.e.
    /// `a[i, j, k, l, m] = ((i*4 + j)*5 + k)*6 + l)*7 + m` (broadcast build).
    fn build_input_3x4x5x6x7(device: &DeviceType) -> Tensor<i32, DeviceType, IxD> {
        let i = rt::arange((3, device)).into_shape([3, 1, 1, 1, 1]);
        let j = rt::arange((4, device)).into_shape([1, 4, 1, 1, 1]);
        let k = rt::arange((5, device)).into_shape([1, 1, 5, 1, 1]);
        let l = rt::arange((6, device)).into_shape([1, 1, 1, 6, 1]);
        let m = rt::arange((7, device)).into_shape([1, 1, 1, 1, 7]);
        (((i * 4 + j) * 5 + k) * 6 + l) * 7 + m
    }

    /// `a[i, j, k] = 25*i + 5*j + k` on `device` (broadcast build).
    fn build_input_3x5x5(device: &DeviceType) -> Tensor<i32, DeviceType, IxD> {
        let i = rt::arange((3, device)).into_shape([3, 1, 1]);
        let j = rt::arange((5, device)).into_shape([1, 5, 1]);
        let k = rt::arange((5, device)).into_shape([1, 1, 5]);
        i * 25 + j * 5 + k
    }

    /// `a[i, j, k] = 20*i + 4*j + k` on `device` (broadcast build).
    fn build_input_5x5x4(device: &DeviceType) -> Tensor<i32, DeviceType, IxD> {
        let i = rt::arange((5, device)).into_shape([5, 1, 1]);
        let j = rt::arange((5, device)).into_shape([1, 5, 1]);
        let k = rt::arange((4, device)).into_shape([1, 1, 4]);
        i * 20 + j * 4 + k
    }

    /// Row-major logical order of a 2-D result, read through the public API so
    /// that the comparison does not depend on the memory arrangement.
    fn grid(x: &TensorCow<'_, i32, DeviceType, IxD>, n: usize, m: usize) -> Vec<i32> {
        let mut out = Vec::with_capacity(n * m);
        for i in 0..n {
            for j in 0..m {
                out.push(x.i((i, j)).to_scalar());
            }
        }
        out
    }

    /// The order-invariant half of the story: for a run of advanced indexers
    /// that stays *together*, and for a 1-D result, the two device orders gather
    /// the same logical result — the same shape and the same value at every
    /// position, whatever the arrangement. A *displaced* run (advanced indexers
    /// apart) is the documented exception and lives in the sibling
    /// [`test_array_index_order_arrangement`].
    ///
    /// The comparisons here are deliberately arrangement-blind: element reads
    /// (`grid`) for 2-D results and the flattened sequence for 1-D ones (a
    /// single axis has a single order), so that equal values under unequal
    /// arrangements cannot pass by accident.
    #[test]
    fn test_array_index_order_invariance() {
        crate::specify_test!("test_array_index_order_invariance");

        let mut dev_row = TESTCFG.device.clone();
        dev_row.set_default_order(RowMajor);
        let mut dev_col = TESTCFG.device.clone();
        dev_col.set_default_order(ColMajor);
        let a_row = build_input_2x3x4(&dev_row);
        let a_col = build_input_2x3x4(&dev_col);

        // every axis consumed by an integer and 1-D index arrays: a 1-D result
        // NumPy: `a[1, [0, 1, 2], [2, 0, 1]]`
        let b_row = a_row.array_index((1, [0, 1, 2], [2, 0, 1]));
        let b_col = a_col.array_index((1, [0, 1, 2], [2, 0, 1]));
        assert_eq!(b_row.shape(), &vec![3]);
        assert_eq!(b_col.shape(), &vec![3]);
        assert_eq!(b_row.into_shape([-1]).to_vec(), vec![14, 16, 21]);
        assert_eq!(b_col.into_shape([-1]).to_vec(), vec![14, 16, 21]);

        // the run stays together but sits after a base axis: the broadcast
        // dimension is inserted in place (position 1) in both orders, so the
        // value at every position agrees while the arrangement differs
        // NumPy: `a[:, [0, 1], [2, 0]]`
        let k2_row = a_row.array_index((.., [0, 1], [2, 0]));
        let k2_col = a_col.array_index((.., [0, 1], [2, 0]));
        assert_eq!(k2_row.shape(), &vec![2, 2]);
        assert_eq!(k2_col.shape(), &vec![2, 2]);
        assert_eq!(grid(&k2_row, 2, 2), vec![2, 4, 14, 16]);
        assert_eq!(grid(&k2_col, 2, 2), vec![2, 4, 14, 16]);

        // index arrays of different ranks broadcast trailing-aligned: the rank-1
        // array lines up with the *last* broadcast dimension (its 2x1 partner
        // with both), whatever the device order
        // NumPy: `a[1, [[2], [0]], [3, 0, 1, 2]]`
        for (device, a) in [(&dev_row, &a_row), (&dev_col, &a_col)] {
            let idx = rt::asarray((vec![2_isize, 0], device)).into_shape([2, 1]);
            let e = a.array_index((1, &idx, [3, 0, 1, 2]));
            assert_eq!(e.shape(), &vec![2, 4]);
            assert_eq!(grid(&e, 2, 4), vec![23, 20, 21, 22, 15, 12, 13, 14]);
        }

        // the *same logical* multi-dimensional index arrays on both devices: a
        // flat host listing is read in the device order, so the column-major
        // device is handed the F-order listing of the same array (the row-major
        // one the C-order listing) — and the two gathers agree
        let x_row = rt::arange((3, &dev_row)).into_shape([3, 1]) * 4 + rt::arange((4, &dev_row)).into_shape([1, 4]);
        let x_col = rt::arange((3, &dev_col)).into_shape([3, 1]) * 4 + rt::arange((4, &dev_col)).into_shape([1, 4]);
        let d_row = x_row.array_index((
            rt::asarray((vec![0_isize, 1, 2, 0], &dev_row)).into_shape([2, 2]),
            rt::asarray((vec![3_isize, 0, 1, 2], &dev_row)).into_shape([2, 2]),
        ));
        let d_col = x_col.array_index((
            rt::asarray((vec![0_isize, 2, 1, 0], &dev_col)).into_shape([2, 2]),
            rt::asarray((vec![3_isize, 1, 0, 2], &dev_col)).into_shape([2, 2]),
        ));
        assert_eq!(d_row.shape(), &vec![2, 2]);
        assert_eq!(d_col.shape(), &vec![2, 2]);
        // NumPy: `x[[[0, 1], [2, 0]], [[3, 0], [1, 2]]]`
        assert_eq!(grid(&d_row, 2, 2), vec![3, 4, 9, 2]);
        assert_eq!(grid(&d_col, 2, 2), vec![3, 4, 9, 2]);

        // what the order decides here is the *construction*, not the gather: the
        // same flat listing on the column-major device is the transposed pair of
        // index arrays (`reshape(flat, [2, 2], order='F')`), and the gather
        // faithfully returns other elements
        // NumPy: `x[[[0, 2], [1, 0]], [[3, 1], [0, 2]]]`
        let e_col = x_col.array_index((
            rt::asarray((vec![0_isize, 1, 2, 0], &dev_col)).into_shape([2, 2]),
            rt::asarray((vec![3_isize, 0, 1, 2], &dev_col)).into_shape([2, 2]),
        ));
        assert_eq!(grid(&e_col, 2, 2), vec![3, 9, 4, 2]);
    }

    /// The other half of the story: the column-major placement rule, and the
    /// arrangement. A run of advanced indexers that other indexers *displace*
    /// goes to the front under row-major and to the **back** under column-major
    /// (the broadcast block keeps its contiguity role: the most-strided axis of
    /// the result); a run that stays together keeps its position in both orders.
    /// So:
    ///
    /// - a 1-D result is *identical* under both orders (a single axis has a single order);
    /// - a together run keeps its *shape*, and only the arrangement differs: the result is
    ///   C-contiguous on a row-major device and F-contiguous on a column-major one, so its
    ///   flattened visit sequence (`to_vec()`, `into_shape([-1])`, `iter()`) is NumPy's `ravel()` /
    ///   `ravel(order='F')` of the same logical result;
    /// - a displaced run gets the block at the back on a column-major device, so the two orders
    ///   differ in shape; in the two-axis case the column-major result is the row-major one read
    ///   transposed (the same buffer).
    ///
    /// An n-dimensional (n > 1) index array always broadcasts to an
    /// n-dimensional bulk, hence always forces a multi-dimensional result — but
    /// it is *not* the criterion for the shape difference: that is whether the
    /// advanced indexers are apart.
    ///
    /// The kernel's own visit order is a locality choice and does not show up
    /// here: every output position is written from exactly one source position,
    /// whatever the traversal — the layout is what carries the device order into
    /// the result.
    #[test]
    fn test_array_index_order_arrangement() {
        crate::specify_test!("test_array_index_order_arrangement");

        let mut dev_row = TESTCFG.device.clone();
        dev_row.set_default_order(RowMajor);
        let mut dev_col = TESTCFG.device.clone();
        dev_col.set_default_order(ColMajor);
        let a_row = build_input_2x3x4(&dev_row);
        let a_col = build_input_2x3x4(&dev_col);

        // a 1-D result: identical under both orders, down to the strides
        let b_row = a_row.array_index((1, [0, 1, 2], [2, 0, 1]));
        let b_col = a_col.array_index((1, [0, 1, 2], [2, 0, 1]));
        assert_eq!(b_row.stride(), b_col.stride());
        assert_eq!(b_row.into_shape([-1]).to_vec(), vec![14, 16, 21]);
        assert_eq!(b_col.into_shape([-1]).to_vec(), vec![14, 16, 21]);

        // a 1-D index array plus slices makes a multi-dimensional result; the
        // run stays together, so both orders keep the shape and only the
        // arrangement differs (the same values — see the sibling test)
        // NumPy: `a[:, :, [0, 1]]`
        let c_seq = vec![0, 1, 4, 5, 8, 9, 12, 13, 16, 17, 20, 21];
        let c_row = a_row.array_index((.., .., [0, 1]));
        let c_col = a_col.array_index((.., .., [0, 1]));
        assert_eq!(c_row.shape(), &vec![2, 3, 2]);
        assert_eq!(c_col.shape(), &vec![2, 3, 2]);
        assert_eq!(c_row.stride(), &vec![6, 2, 1]);
        assert_eq!(c_col.stride(), &vec![1, 2, 6]);
        assert_eq!(c_row.into_shape([-1]).to_vec(), c_seq);
        assert_eq!(c_col.into_shape([-1]).to_vec(), f_order(&c_seq, &[2, 3, 2]));

        // ... and with the run leading the index (still together): in place at
        // the front, so the shape is kept as well
        // NumPy: `a[[0, 1], [2, 0], :]`
        let k3_seq = vec![8, 9, 10, 11, 12, 13, 14, 15];
        let k3_row = a_row.array_index(([0, 1], [2, 0], ..));
        let k3_col = a_col.array_index(([0, 1], [2, 0], ..));
        assert_eq!(k3_row.shape(), &vec![2, 4]);
        assert_eq!(k3_col.shape(), &vec![2, 4]);
        assert_eq!(k3_row.stride(), &vec![4, 1]);
        assert_eq!(k3_col.stride(), &vec![1, 2]);
        assert_eq!(k3_row.into_shape([-1]).to_vec(), k3_seq);
        assert_eq!(k3_col.into_shape([-1]).to_vec(), f_order(&k3_seq, &[2, 4]));

        // two 1-D index arrays *apart* — separated by a slice, no
        // multi-dimensional index array anywhere: the run is displaced, so the
        // column-major device puts the block at the back, and in this two-axis
        // case the result is the transpose of the row-major one (same buffer)
        // NumPy: `a[[0, 1], :, [2, 0]]`
        let sep_seq = vec![2, 6, 10, 12, 16, 20];
        let sep_row = a_row.array_index(([0, 1], .., [2, 0]));
        let sep_col = a_col.array_index(([0, 1], .., [2, 0]));
        assert_eq!(sep_row.shape(), &vec![2, 3]);
        assert_eq!(sep_col.shape(), &vec![3, 2]);
        assert_eq!(sep_row.stride(), &vec![3, 1]);
        assert_eq!(sep_col.stride(), &vec![1, 3]);
        assert_eq!(grid(&sep_row, 2, 3), sep_seq);
        // the column-major logical order is the F-order reading of the row-major
        // one (the transpose) ...
        assert_eq!(grid(&sep_col, 3, 2), f_order(&sep_seq, &[2, 3]));
        // ... and the flattened sequence is unchanged (the same buffer)
        assert_eq!(sep_row.into_shape([-1]).to_vec(), sep_seq);
        assert_eq!(sep_col.into_shape([-1]).to_vec(), sep_seq);

        // a plain integer counts as an advanced indexer for the grouping, so an
        // array...integer pair across a slice is displaced too
        // NumPy: `a[[1, 0], :, 1]`
        let int_row = a_row.array_index(([1, 0], .., 1));
        let int_col = a_col.array_index(([1, 0], .., 1));
        assert_eq!(int_row.shape(), &vec![2, 3]);
        assert_eq!(int_col.shape(), &vec![3, 2]);
        assert_eq!(grid(&int_row, 2, 3), vec![13, 17, 21, 1, 5, 9]);
        assert_eq!(grid(&int_col, 3, 2), f_order(&[13, 17, 21, 1, 5, 9], &[2, 3]));

        // multi-dimensional index arrays with the broadcast dimension in the
        // middle of the result: a slice, then two consecutive index arrays
        // (inserted in place, at position 1), then a slice — a together run, so
        // both orders keep the shape
        let a4_row = build_input_3x2x2x4(&dev_row);
        let a4_col = build_input_3x2x2x4(&dev_col);
        let shape = [2_usize, 2, 4];
        let mid = || (0..2, [0, 1], [1, 0], ..);
        let mid_row = a4_row.array_index(mid());
        let mid_col = a4_col.array_index(mid());
        // NumPy: `a[0:2, [0, 1], [1, 0], :]`
        let c_seq = vec![4, 5, 6, 7, 8, 9, 10, 11, 20, 21, 22, 23, 24, 25, 26, 27];
        assert_eq!(mid_row.shape(), &vec![2, 2, 4]);
        assert_eq!(mid_col.shape(), &vec![2, 2, 4]);
        assert_eq!(mid_row.stride(), &vec![8, 4, 1]);
        // the fancy dimension (position 1) carries stride 2 under column-major
        assert_eq!(mid_col.stride(), &vec![1, 2, 4]);
        assert_eq!(mid_row.into_shape([-1]).to_vec(), c_seq);
        assert_eq!(mid_col.into_shape([-1]).to_vec(), f_order(&c_seq, &shape));

        // the same story on the 5-D input with base axes on both sides of a
        // together run: the position is kept in both orders, so NumPy's shape
        // `(3, 2, 6, 7)` is the same and only the arrangement differs
        // NumPy: `a[:, [0, 1], [2, 0], :, :]`
        let a5_row = build_input_3x4x5x6x7(&dev_row);
        let a5_col = build_input_3x4x5x6x7(&dev_col);
        let tight = || (.., [0, 1], [2, 0], .., ..);
        let tight_row = a5_row.array_index(tight());
        let tight_col = a5_col.array_index(tight());
        assert_eq!(tight_row.shape(), &vec![3, 2, 6, 7]);
        assert_eq!(tight_col.shape(), &vec![3, 2, 6, 7]);
        assert_eq!(tight_row.stride(), &vec![84, 42, 7, 1]);
        assert_eq!(tight_col.stride(), &vec![1, 3, 6, 36]);
        // the same logical result either way (NumPy: 84, 947, 1931)
        for (i, p, l, m) in [(0, 0, 0, 0), (1, 0, 3, 2), (2, 1, 5, 6)] {
            assert_eq!(tight_row.i((i, p, l, m)).to_scalar(), tight_col.i((i, p, l, m)).to_scalar());
        }
        assert_eq!(tight_row.i((0, 0, 0, 0)).to_scalar(), 84);
        assert_eq!(tight_row.i((1, 0, 3, 2)).to_scalar(), 947);
        assert_eq!(tight_row.i((2, 1, 5, 6)).to_scalar(), 1931);

        // ... and with the advanced indexers apart (displaced): the column-major
        // device moves the block to the back, the row-major result with the
        // block re-inserted there (`col[j, l, p] = row[p, j, l]`)
        let lead = || ([0, 1], .., [1, 0], ..);
        let lead_row = a4_row.array_index(lead());
        let lead_col = a4_col.array_index(lead());
        // NumPy: `a[[0, 1], :, [1, 0], :]`
        let c_seq = vec![4, 5, 6, 7, 12, 13, 14, 15, 16, 17, 18, 19, 24, 25, 26, 27];
        assert_eq!(lead_row.shape(), &vec![2, 2, 4]);
        assert_eq!(lead_col.shape(), &vec![2, 4, 2]);
        assert_eq!(lead_row.stride(), &vec![8, 4, 1]);
        assert_eq!(lead_row.into_shape([-1]).to_vec(), c_seq);
        assert_eq!(lead_col.stride(), &vec![1, 2, 8]);
        // the permuted result, read column-major
        assert_eq!(lead_col.into_shape([-1]).to_vec(), vec![
            4, 12, 5, 13, 6, 14, 7, 15, 16, 24, 17, 25, 18, 26, 19, 27
        ]);
    }

    /// The displaced-run placement on a deep base (three base axes): the block
    /// goes to the front under row-major and behind all base axes under
    /// column-major, the base axes keeping their order —
    /// `arange(2520).reshape(3, 4, 5, 6, 7)`, NumPy `a[:, [0, 1], :, [2, 0], :]`.
    #[test]
    fn test_array_index_order_displaced_deep_base() {
        crate::specify_test!("test_array_index_order_displaced_deep_base");

        let mut dev_row = TESTCFG.device.clone();
        dev_row.set_default_order(RowMajor);
        let mut dev_col = TESTCFG.device.clone();
        dev_col.set_default_order(ColMajor);
        let a_row = build_input_3x4x5x6x7(&dev_row);
        let a_col = build_input_3x4x5x6x7(&dev_col);

        let deep = || (.., [0, 1], .., [2, 0], ..);
        let deep_row = a_row.array_index(deep());
        let deep_col = a_col.array_index(deep());
        assert_eq!(deep_row.shape(), &vec![2, 3, 5, 7]);
        assert_eq!(deep_col.shape(), &vec![3, 5, 7, 2]);
        assert_eq!(deep_row.stride(), &vec![105, 35, 7, 1]);
        assert_eq!(deep_col.stride(), &vec![1, 3, 15, 105]);
        // the block moved behind the base axes: `col[i, k, m, p] == row[p, i, k, m]`
        // (NumPy: `a[0, 0, 0, 0]` = 14, `a[1, 2, 4, 6]` = 2064)
        for (p, i, k, m) in [(0, 0, 0, 0), (1, 2, 4, 6), (0, 1, 2, 3), (1, 0, 3, 5)] {
            assert_eq!(deep_col.i((i, k, m, p)).to_scalar(), deep_row.i((p, i, k, m)).to_scalar());
        }
        assert_eq!(deep_row.i((0, 0, 0, 0)).to_scalar(), 14);
        assert_eq!(deep_row.i((1, 2, 4, 6)).to_scalar(), 2064);
    }

    /// Boolean masks follow the placement rule as integer index arrays do. A
    /// one-dimensional mask carries a single-order sequence, so the two devices
    /// select the same positions and only the arrangement differs; a mask with
    /// `ndim >= 2` carries the device's `nonzero` visit order on its count axis,
    /// so under `ColMajor` the count axis is permuted — the registered sequence
    /// divergence, the same class as `mask_select`'s.
    #[test]
    fn test_boolean_mask_orders() {
        crate::specify_test!("test_boolean_mask_orders");

        let mut dev_row = TESTCFG.device.clone();
        dev_row.set_default_order(RowMajor);
        let mut dev_col = TESTCFG.device.clone();
        dev_col.set_default_order(ColMajor);
        let a_row = build_input_3x5x5(&dev_row);
        let a_col = build_input_3x5x5(&dev_col);

        // 1-D masks: both devices select the same positions; the result keeps
        // its shape and only the arrangement matters (C- vs F-contiguous)
        let m1_row = rt::asarray((vec![true, false, false, true, false], &dev_row));
        let m1_col = rt::asarray((vec![true, false, false, true, false], &dev_col));
        let m2_row = rt::asarray((vec![false, true, false, true, false], &dev_row));
        let m2_col = rt::asarray((vec![false, true, false, true, false], &dev_col));

        let b_row = a_row.array_index((1..3, &m1_row));
        let b_col = a_col.array_index((1..3, &m1_col));
        assert_eq!(b_row.shape(), &vec![2, 2, 5]);
        assert_eq!(b_col.shape(), &vec![2, 2, 5]);
        assert_eq!(b_row.stride(), &vec![10, 5, 1]);
        assert_eq!(b_col.stride(), &vec![1, 2, 4]);
        let seq = b_row.into_shape([-1]).to_vec();
        assert_eq!(b_col.into_shape([-1]).to_vec(), f_order(&seq, &[2, 2, 5]));

        let c_row = a_row.array_index((1..3, &m1_row, &m2_row));
        let c_col = a_col.array_index((1..3, &m1_col, &m2_col));
        assert_eq!(c_row.shape(), &vec![2, 2]);
        assert_eq!(c_col.shape(), &vec![2, 2]);
        let seq = c_row.into_shape([-1]).to_vec();
        assert_eq!(seq, vec![26, 43, 51, 68]);
        assert_eq!(c_col.into_shape([-1]).to_vec(), f_order(&seq, &[2, 2]));

        // a mask and a plain integer across a slice are displaced: row-major
        // puts the block at the front, column-major at the back (the transpose,
        // the same buffer)
        let m0_row = rt::asarray((vec![true, false, true], &dev_row));
        let m0_col = rt::asarray((vec![true, false, true], &dev_col));
        let d_row = a_row.array_index((&m0_row, .., 0));
        let d_col = a_col.array_index((&m0_col, .., 0));
        assert_eq!(d_row.shape(), &vec![2, 5]);
        assert_eq!(d_col.shape(), &vec![5, 2]);
        let seq = vec![0, 5, 10, 15, 20, 50, 55, 60, 65, 70];
        assert_eq!(d_row.into_shape([-1]).to_vec(), seq);
        assert_eq!(d_col.into_shape([-1]).to_vec(), seq);

        // an n-dimensional mask: the count axis follows the device's `nonzero`
        // visit order, so the column-major result is NOT the row-major one
        // re-arranged — the values at a multi-index differ
        // built from a logical grid, so both devices hold the same mask
        // whatever their layout (the flat-listing construction trap)
        let build_mask = |device: &DeviceType| {
            let grid = rt::arange((5, device)).into_shape([5, 1]) * 5 + rt::arange((5, device)).into_shape([1, 5]);
            grid.map(|v| *v == 3 || *v == 17) // trues at (0, 3) and (3, 2)
        };
        let mask_row = build_mask(&dev_row);
        let mask_col = build_mask(&dev_col);
        let b3_row = build_input_5x5x4(&dev_row);
        let b3_col = build_input_5x5x4(&dev_col);
        let r_row = b3_row.array_index((&mask_row,));
        let r_col = b3_col.array_index((&mask_col,));
        assert_eq!(r_row.shape(), &vec![2, 4]);
        assert_eq!(r_col.shape(), &vec![2, 4]);
        // row-major visits the mask row-major: (0, 3) first
        assert_eq!(r_row.i((0, 0)).to_scalar(), 12);
        // column-major visits it column-major: (3, 2) first
        assert_eq!(r_col.i((0, 0)).to_scalar(), 68);
        // the whole count axis is the mask's `nonzero` sequence: row-major
        // reads the trues (0, 3), (3, 2); column-major reads them (3, 2), (0, 3)
        assert_eq!(r_row.i((0, 0)).to_scalar(), b3_row.i((0, 3, 0)).to_scalar());
        assert_eq!(r_row.i((1, 0)).to_scalar(), b3_row.i((3, 2, 0)).to_scalar());
        assert_eq!(r_col.i((0, 0)).to_scalar(), b3_col.i((3, 2, 0)).to_scalar());
        assert_eq!(r_col.i((1, 0)).to_scalar(), b3_col.i((0, 3, 0)).to_scalar());
    }
}
