// Most or all contents generated by AI (model deepseek-flash).
//! array_index tests: NumPy-cited array-indexing (fancy indexing) contract,
//! placement-rule cases from the NumPy indexing guide, and a randomized
//! NumPy-generated differential set (`array_index_numpy_cases.txt`).

#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

/// Parse the index spec of a generated case: tokens separated by `|`, each of
/// `I<n>` (integer), `S<a>:<b>:<c>` (slice), `A<d0>x..:<v..>` (index array),
/// `N` (new axis) or `E` (ellipsis).
fn parse_indexers(device: &DeviceType, spec: &str) -> ArrayIndexArgs<DeviceType> {
    let parse_opt = |s: &str| -> Option<isize> { if s.is_empty() { None } else { Some(s.parse().unwrap()) } };
    let mut indexers: Vec<ArrayIndexer<DeviceType>> = Vec::new();
    for token in spec.split('|') {
        if token.is_empty() {
            continue;
        }
        match &token[..1] {
            "I" => indexers.push(ArrayIndexer::Basic(Indexer::Select(token[1..].parse().unwrap()))),
            "S" => {
                let parts = token[1..].split(':').collect::<Vec<_>>();
                let slice = SliceI::new(
                    parse_opt(parts.first().copied().unwrap_or("")),
                    parse_opt(parts.get(1).copied().unwrap_or("")),
                    parse_opt(parts.get(2).copied().unwrap_or("")),
                );
                indexers.push(ArrayIndexer::Basic(Indexer::Slice(slice)));
            },
            "A" => {
                let (shape_txt, values_txt) = token[1..].split_once(':').unwrap();
                let shape = shape_txt.split('x').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
                let values = values_txt.split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>();
                let index = rt::asarray((values, device)).into_shape(shape);
                indexers.push(ArrayIndexer::ArrayIndex(index));
            },
            "N" => indexers.push(ArrayIndexer::Basic(Indexer::Insert)),
            "E" => indexers.push(ArrayIndexer::Basic(Indexer::Ellipsis)),
            other => panic!("invalid index token `{other}` in case spec `{spec}`"),
        }
    }
    ArrayIndexArgs::new(indexers)
}

#[cfg(test)]
mod numpy_array_index {
    use super::*;
    static FUNC: &str = "numpy_array_index";

    #[test]
    fn test_empty_fancy_index() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_empty_fancy_index (L127)
        // `a[[]]` gives an empty result with the same dtype. The float-dtype
        // case (`np.array([])` raises IndexError) is type-level N/A: rstsr
        // index tensors are typed `isize`.
        crate::specify_test!("test_empty_fancy_index");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((3, &device));
        let empty = rt::asarray((Vec::<isize>::new(), &device));
        let b = a.array_index(&empty);
        assert_eq!(b.shape(), &vec![0]);
        // dtype preservation is structural in rstsr: the result element type
        // is the input's `T` by construction

        // an empty index array on a higher-rank tensor keeps the trailing axes
        let c = rt::arange((12, &device)).into_shape([3, 4]);
        let d = c.array_index((&empty,));
        assert_eq!(d.shape(), &vec![0, 4]);
    }

    #[test]
    fn test_broaderrors_indexing() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_broaderrors_indexing (L365)
        // Index arrays that cannot be broadcast together raise IndexError.
        // (The `__setitem__` half is N/A: advanced-key assignment is not
        // implemented yet.)
        crate::specify_test!("test_broaderrors_indexing");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a: Tensor<f64, _> = rt::zeros(([5, 5], &device));
        assert!(a.array_index_f(([0, 1], [0, 1, 2])).is_err());
    }

    #[test]
    fn test_nontuple_ndindex() {
        // numpy: v2.5.2 | _core/tests/test_indexing.py::TestIndexing::test_nontuple_ndindex (L612)
        // A bare list indexes the first axis (`a[[0,1]]` is a row list), while
        // a tuple zips index arrays. The `a[[slice(None)]]` IndexError case is
        // N/A: Rust has no list-of-slice literal (a host list is a single
        // one-dimensional index array).
        crate::specify_test!("test_nontuple_ndindex");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((25, &device)).into_shape([5, 5]);
        assert_equal(a.array_index([0, 1]), a.slice((0..2, ..)), None);
        assert_eq!(a.array_index(([0, 1], [0, 1])).into_shape([-1]).to_vec(), vec![0, 6]);
    }
}

#[cfg(test)]
mod custom_array_index {
    use super::*;
    static FUNC: &str = "custom_array_index";

    #[test]
    fn test_placement_rule_examples() {
        crate::specify_test!("test_placement_rule_examples");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // the examples of NumPy's indexing guide ("Advanced Indexing"): one
        // contiguous advanced run broadcasts in place, separated index arrays
        // move the broadcast dimensions to the front
        let x = rt::arange((10 * 20 * 30, &device)).into_shape([10, 20, 30]);
        let ind = rt::asarray(((0..10_isize).collect::<Vec<_>>(), &device));

        // `x[:, ind, ind]`: contiguous advanced run -> in place
        let z = x.array_index((.., &ind, &ind));
        assert_eq!(z.shape(), &vec![10, 10]);
        assert_eq!(z.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 31, 62]);

        // `x[ind, :, ind]`: the advanced run is separated by a slice -> front
        let y = x.array_index((&ind, .., &ind));
        assert_eq!(y.shape(), &vec![10, 20]);
        assert_eq!(y.into_shape([-1]).to_vec()[..3].to_vec(), vec![0, 30, 60]);
    }

    #[test]
    fn test_placement_rule_4d() {
        crate::specify_test!("test_placement_rule_4d");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let f = rt::arange((2 * 3 * 4 * 5, &device)).into_shape([2, 3, 4, 5]);
        let i01 = rt::asarray((vec![1_isize, 0], &device));
        let i43 = rt::asarray((vec![4_isize, 3], &device));

        // `f[[1,0], :, :, [4,3]]`: arrays separated by two slices -> front
        assert_eq!(f.array_index((&i01, Ellipsis, &i43)).shape(), &vec![2, 3, 4]);
        // `f[:, [1,0], :, [4,3]]`: separated -> front (after nothing)
        assert_eq!(f.array_index((.., &i01, .., &i43)).shape(), &vec![2, 2, 4]);
        // `f[[1,0], :, 1, :]`: integer counts as advanced for the grouping
        assert_eq!(f.array_index((&i01, .., 1, ..)).shape(), &vec![2, 3, 5]);
        // `f[:, [1,0], 1, :]`: a single contiguous advanced run -> in place
        assert_eq!(f.array_index((.., &i01, 1, ..)).shape(), &vec![2, 2, 5]);
    }

    #[test]
    fn test_edges() {
        crate::specify_test!("test_edges");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);

        // negative indices count from the back; duplicates are allowed
        assert_eq!(a.array_index([-1]).into_shape([-1]).to_vec(), vec![8, 9, 10, 11]);
        assert_eq!(a.array_index(([0, 0],)).shape(), &vec![2, 4]);

        // a zero-dimensional integer array is a scalar index (and gives a view)
        let idx0d_owner = rt::asarray((vec![2_isize], &device));
        let idx0d = idx0d_owner.i(0);
        let b = a.array_index((&idx0d,));
        assert_eq!(b.shape(), &vec![4]);
        assert!(!b.is_owned());

        // mixed basic + array indexers with a new axis
        let c = a.array_index((.., &rt::asarray((vec![0_isize, 2], &device))));
        assert_eq!(c.shape(), &vec![3, 2]);

        // out of range / too many indexers
        assert!(a.array_index_f([3]).is_err());
        assert!(a.array_index_f((1, 2, 3)).is_err());
    }

    /// Differential check against NumPy: every line of
    /// `array_index_numpy_cases.txt` is a case generated (and solved) by
    /// `gen_array_index_cases.py` from a pinned NumPy.
    #[test]
    fn test_numpy_generated_diff() {
        crate::specify_test!("test_numpy_generated_diff");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let data = include_str!("array_index_numpy_cases.txt");
        let mut checked = 0_usize;
        for line in data.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let fields = line.split(';').collect::<Vec<_>>();
            assert_eq!(fields.len(), 4, "bad case line: {line}");
            let shape = fields[0].split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>();
            let out_shape = if fields[2].is_empty() {
                vec![]
            } else {
                fields[2].split(',').map(|s| s.parse::<usize>().unwrap()).collect::<Vec<_>>()
            };
            let values = if fields[3].is_empty() {
                vec![]
            } else {
                fields[3].split(',').map(|s| s.parse::<isize>().unwrap()).collect::<Vec<_>>()
            };
            let size = shape.iter().product::<usize>();
            let a = rt::asarray(((0..size as isize).collect::<Vec<_>>(), &device)).into_shape(shape);
            let out = a.array_index(parse_indexers(&device, fields[1]));
            assert_eq!(out.shape(), &out_shape, "shape mismatch for case: {line}");
            assert_eq!(out.into_shape([-1]).to_vec(), values, "value mismatch for case: {line}");
            checked += 1;
        }
        assert!(checked >= 200, "expected a substantial generated case set, got {checked}");
    }
}
