#![allow(non_camel_case_types)]

/*!
Batched GEMM extensions for the OpenBLAS device.

Two OpenBLAS extension interfaces are wrapped here:

- grouped (pointer-based) `?gemm_batch`, behind feature `use_batched_gemm`;
- strided `?gemm_batch_strided`, behind feature `use_batched_gemm_strided`.

The functions in this module are for internal usage: they are public, but
*not* intended as user API. They are `unsafe` and take raw pointers; the
user-facing entry points are `rt::linalg::batched_matmul` /
`rt::linalg::batched_matmul_strided`, and the broadcasted `rt::matmul` which
dispatches onto them (see [`batched_matmul_strided_try`] and
[`batched_matmul_grouped_try`]).

Most or all contents generated by AI (model glm-5.3).
*/

use crate::prelude_dev::*;
use crate::threading::with_num_threads;
use core::any::TypeId;
use core::ops::{Add, Mul};
use lapack_ffi::cblas;
use num::{Complex, Zero};
use rstsr_blas_traits::prelude::{BatchedGEMMDriverAPI, BatchedGEMMStridedDriverAPI};

type c32 = Complex<f32>;
type c64 = Complex<f64>;

/* #region helpers */

fn same_type<A: 'static, B: 'static>() -> bool {
    TypeId::of::<A>() == TypeId::of::<B>()
}

fn cblas_order_of(order: FlagOrder) -> cblas::CBLAS_LAYOUT {
    match order {
        RowMajor => cblas::CBLAS_LAYOUT::CblasRowMajor,
        ColMajor => cblas::CBLAS_LAYOUT::CblasColMajor,
    }
}

fn cblas_trans_of(t: FlagTrans) -> Result<cblas::CBLAS_TRANSPOSE> {
    match t {
        FlagTrans::N => Ok(cblas::CBLAS_TRANSPOSE::CblasNoTrans),
        FlagTrans::T => Ok(cblas::CBLAS_TRANSPOSE::CblasTrans),
        FlagTrans::C => Ok(cblas::CBLAS_TRANSPOSE::CblasConjTrans),
        // conjugate-only (no transpose) has no cblas equivalent in this
        // OpenBLAS build; callers needing it should clone and conjugate the
        // data explicitly
        _ => rstsr_invalid!(t)?,
    }
}

fn as_blas_int(v: usize) -> Result<cblas::blas_int> {
    rstsr_assert!(v <= cblas::blas_int::MAX as usize, Miscellaneous)?;
    Ok(v as cblas::blas_int)
}

fn int_vec(v: &[usize]) -> Result<Vec<cblas::blas_int>> {
    v.iter().map(|&x| as_blas_int(x)).collect()
}

/* #endregion */

/* #region usual functions: grouped (pointer-based) batched gemm */

#[cfg(feature = "use_batched_gemm")]
#[duplicate_item(
     ty    fn_name             cblas_wrap                   ;
    [f32] [batched_gemm_f32] [cblas_sgemm_batch_wrap];
    [f64] [batched_gemm_f64] [cblas_dgemm_batch_wrap];
    [c32] [batched_gemm_c32] [cblas_cgemm_batch_wrap];
    [c64] [batched_gemm_c64] [cblas_zgemm_batch_wrap];
)]
/// Grouped (pointer-based) batched GEMM over the `?gemm_batch` extension.
///
/// # Safety
///
/// All pointers in `a`, `b`, `c` must be valid for the shapes and leading
/// dimensions given by the parameter arrays, for the whole duration of the
/// call.
#[allow(clippy::too_many_arguments)]
pub unsafe fn fn_name(
    order: FlagOrder,
    transa: &[FlagTrans],
    transb: &[FlagTrans],
    m: &[usize],
    n: &[usize],
    k: &[usize],
    alpha: &[ty],
    a: &[*const ty],
    lda: &[usize],
    b: &[*const ty],
    ldb: &[usize],
    beta: &[ty],
    c: &[*mut ty],
    ldc: &[usize],
    group_count: usize,
    group_size: &[usize],
) -> Result<()> {
    rstsr_assert_eq!(transa.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(transb.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(m.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(n.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(k.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(alpha.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(lda.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(ldb.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(beta.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(ldc.len(), group_count, InvalidLayout)?;
    rstsr_assert_eq!(group_size.len(), group_count, InvalidLayout)?;
    let total: usize = group_size.iter().sum();
    rstsr_assert_eq!(a.len(), total, InvalidLayout)?;
    rstsr_assert_eq!(b.len(), total, InvalidLayout)?;
    rstsr_assert_eq!(c.len(), total, InvalidLayout)?;

    let transa_arr: Vec<_> = transa.iter().map(|&t| cblas_trans_of(t)).collect::<Result<Vec<_>>>()?;
    let transb_arr: Vec<_> = transb.iter().map(|&t| cblas_trans_of(t)).collect::<Result<Vec<_>>>()?;
    let m_arr = int_vec(m)?;
    let n_arr = int_vec(n)?;
    let k_arr = int_vec(k)?;
    let lda_arr = int_vec(lda)?;
    let ldb_arr = int_vec(ldb)?;
    let ldc_arr = int_vec(ldc)?;
    let group_size_arr = int_vec(group_size)?;
    let group_count = as_blas_int(group_count)?;
    let mut a_arr: Vec<*const ty> = a.to_vec();
    let mut b_arr: Vec<*const ty> = b.to_vec();
    let mut c_arr: Vec<*mut ty> = c.to_vec();

    cblas_wrap(
        cblas_order_of(order),
        transa_arr.as_ptr(),
        transb_arr.as_ptr(),
        m_arr.as_ptr(),
        n_arr.as_ptr(),
        k_arr.as_ptr(),
        alpha.as_ptr(),
        a_arr.as_mut_ptr(),
        lda_arr.as_ptr(),
        b_arr.as_mut_ptr(),
        ldb_arr.as_ptr(),
        beta.as_ptr(),
        c_arr.as_mut_ptr(),
        ldc_arr.as_ptr(),
        group_count,
        group_size_arr.as_ptr(),
    );
    Ok(())
}

#[cfg(feature = "use_batched_gemm")]
#[duplicate_item(
     ty    wrap_name                 cblas_func             ;
    [f32] [cblas_sgemm_batch_wrap] [cblas_sgemm_batch];
    [f64] [cblas_dgemm_batch_wrap] [cblas_dgemm_batch];
)]
#[allow(clippy::too_many_arguments)]
unsafe fn wrap_name(
    order: cblas::CBLAS_LAYOUT,
    transa: *const cblas::CBLAS_TRANSPOSE,
    transb: *const cblas::CBLAS_TRANSPOSE,
    m: *const cblas::blas_int,
    n: *const cblas::blas_int,
    k: *const cblas::blas_int,
    alpha: *const ty,
    a: *mut *const ty,
    lda: *const cblas::blas_int,
    b: *mut *const ty,
    ldb: *const cblas::blas_int,
    beta: *const ty,
    c: *mut *mut ty,
    ldc: *const cblas::blas_int,
    group_count: cblas::blas_int,
    group_size: *const cblas::blas_int,
) {
    unsafe {
        cblas::cblas_func(
            order,
            transa,
            transb,
            m,
            n,
            k,
            alpha,
            a,
            lda,
            b,
            ldb,
            beta,
            c,
            ldc,
            group_count,
            group_size,
        );
    }
}

#[cfg(feature = "use_batched_gemm")]
#[duplicate_item(
     ty    wrap_name                 cblas_func             ;
    [c32] [cblas_cgemm_batch_wrap] [cblas_cgemm_batch];
    [c64] [cblas_zgemm_batch_wrap] [cblas_zgemm_batch];
)]
#[allow(clippy::too_many_arguments)]
unsafe fn wrap_name(
    order: cblas::CBLAS_LAYOUT,
    transa: *const cblas::CBLAS_TRANSPOSE,
    transb: *const cblas::CBLAS_TRANSPOSE,
    m: *const cblas::blas_int,
    n: *const cblas::blas_int,
    k: *const cblas::blas_int,
    alpha: *const ty,
    a: *mut *const ty,
    lda: *const cblas::blas_int,
    b: *mut *const ty,
    ldb: *const cblas::blas_int,
    beta: *const ty,
    c: *mut *mut ty,
    ldc: *const cblas::blas_int,
    group_count: cblas::blas_int,
    group_size: *const cblas::blas_int,
) {
    unsafe {
        cblas::cblas_func(
            order,
            transa,
            transb,
            m,
            n,
            k,
            alpha as *const core::ffi::c_void,
            a as *mut *const core::ffi::c_void,
            lda,
            b as *mut *const core::ffi::c_void,
            ldb,
            beta as *const core::ffi::c_void,
            c as *mut *mut core::ffi::c_void,
            ldc,
            group_count,
            group_size,
        );
    }
}

/* #endregion */

/* #region usual functions: strided batched gemm */

#[cfg(feature = "use_batched_gemm_strided")]
#[duplicate_item(
     ty    fn_name                     cblas_wrap                           ;
    [f32] [batched_gemm_strided_f32] [cblas_sgemm_batch_strided_wrap];
    [f64] [batched_gemm_strided_f64] [cblas_dgemm_batch_strided_wrap];
    [c32] [batched_gemm_strided_c32] [cblas_cgemm_batch_strided_wrap];
    [c64] [batched_gemm_strided_c64] [cblas_zgemm_batch_strided_wrap];
)]
/// Strided batched GEMM over the `?gemm_batch_strided` extension.
///
/// # Safety
///
/// `a`, `b`, `c` must be valid for the shapes given by `m`, `n`, `k` and the
/// leading dimensions, for `batch_count` matrices spaced by the respective
/// strides, for the whole duration of the call.
#[allow(clippy::too_many_arguments)]
pub unsafe fn fn_name(
    order: FlagOrder,
    transa: FlagTrans,
    transb: FlagTrans,
    m: usize,
    n: usize,
    k: usize,
    alpha: ty,
    a: *const ty,
    lda: usize,
    stride_a: usize,
    b: *const ty,
    ldb: usize,
    stride_b: usize,
    beta: ty,
    c: *mut ty,
    ldc: usize,
    stride_c: usize,
    batch_count: usize,
) -> Result<()> {
    let m = as_blas_int(m)?;
    let n = as_blas_int(n)?;
    let k = as_blas_int(k)?;
    let lda = as_blas_int(lda)?;
    let ldb = as_blas_int(ldb)?;
    let ldc = as_blas_int(ldc)?;
    let stride_a = as_blas_int(stride_a)?;
    let stride_b = as_blas_int(stride_b)?;
    let stride_c = as_blas_int(stride_c)?;
    let batch_count = as_blas_int(batch_count)?;
    let transa = cblas_trans_of(transa)?;
    let transb = cblas_trans_of(transb)?;
    cblas_wrap(
        cblas_order_of(order),
        transa,
        transb,
        m,
        n,
        k,
        alpha,
        a,
        lda,
        stride_a,
        b,
        ldb,
        stride_b,
        beta,
        c,
        ldc,
        stride_c,
        batch_count,
    );
    Ok(())
}

#[cfg(feature = "use_batched_gemm_strided")]
#[duplicate_item(
     ty    wrap_name                           cblas_func                     ;
    [f32] [cblas_sgemm_batch_strided_wrap] [cblas_sgemm_batch_strided];
    [f64] [cblas_dgemm_batch_strided_wrap] [cblas_dgemm_batch_strided];
)]
#[allow(clippy::too_many_arguments)]
unsafe fn wrap_name(
    order: cblas::CBLAS_LAYOUT,
    transa: cblas::CBLAS_TRANSPOSE,
    transb: cblas::CBLAS_TRANSPOSE,
    m: cblas::blas_int,
    n: cblas::blas_int,
    k: cblas::blas_int,
    alpha: ty,
    a: *const ty,
    lda: cblas::blas_int,
    stride_a: cblas::blas_int,
    b: *const ty,
    ldb: cblas::blas_int,
    stride_b: cblas::blas_int,
    beta: ty,
    c: *mut ty,
    ldc: cblas::blas_int,
    stride_c: cblas::blas_int,
    batch_count: cblas::blas_int,
) {
    unsafe {
        cblas::cblas_func(
            order, transa, transb, m, n, k, alpha, a, lda, stride_a, b, ldb, stride_b, beta, c, ldc, stride_c,
            batch_count,
        );
    }
}

#[cfg(feature = "use_batched_gemm_strided")]
#[duplicate_item(
     ty    wrap_name                           cblas_func                     ;
    [c32] [cblas_cgemm_batch_strided_wrap] [cblas_cgemm_batch_strided];
    [c64] [cblas_zgemm_batch_strided_wrap] [cblas_zgemm_batch_strided];
)]
#[allow(clippy::too_many_arguments)]
unsafe fn wrap_name(
    order: cblas::CBLAS_LAYOUT,
    transa: cblas::CBLAS_TRANSPOSE,
    transb: cblas::CBLAS_TRANSPOSE,
    m: cblas::blas_int,
    n: cblas::blas_int,
    k: cblas::blas_int,
    alpha: ty,
    a: *const ty,
    lda: cblas::blas_int,
    stride_a: cblas::blas_int,
    b: *const ty,
    ldb: cblas::blas_int,
    stride_b: cblas::blas_int,
    beta: ty,
    c: *mut ty,
    ldc: cblas::blas_int,
    stride_c: cblas::blas_int,
    batch_count: cblas::blas_int,
) {
    unsafe {
        cblas::cblas_func(
            order,
            transa,
            transb,
            m,
            n,
            k,
            &alpha as *const _ as *const core::ffi::c_void,
            a as *const core::ffi::c_void,
            lda,
            stride_a,
            b as *const core::ffi::c_void,
            ldb,
            stride_b,
            &beta as *const _ as *const core::ffi::c_void,
            c as *mut core::ffi::c_void,
            ldc,
            stride_c,
            batch_count,
        );
    }
}

/* #endregion */

/* #region broadcasted matmul acceleration */

/// Layout pieces of one broadcasted matmul, eligible for batched GEMM.
pub(crate) struct BatchedMatmulPieces {
    pub lc_matmul: Layout<Ix2>,
    pub lc_rest: Layout<IxD>,
    pub la_matmul: Layout<Ix2>,
    pub la_rest: Layout<IxD>,
    pub lb_matmul: Layout<Ix2>,
    pub lb_rest: Layout<IxD>,
}

/// Layout-level eligibility check for batched GEMM acceleration.
///
/// Returns `None` (not an error) whenever the case should be handled by the
/// existing per-slice loop: non-batched rules, degenerate sizes, a batch of
/// one matrix, or a same-buffer product that the per-slice path can serve
/// with `syrk`.
pub(crate) fn batched_matmul_prepare<TA, TB, TC>(
    a: &[TA],
    la: &Layout<IxD>,
    b: &[TB],
    lb: &Layout<IxD>,
    lc: &Layout<IxD>,
    beta_is_zero: bool,
) -> Result<Option<BatchedMatmulPieces>>
where
    TA: 'static,
    TB: 'static,
    TC: 'static,
{
    if la.ndim() < 2 || lb.ndim() < 2 || lc.ndim() < 2 {
        return Ok(None);
    }
    if lc.size() == 0 {
        return Ok(None);
    }

    let cfg = layout_matmul_dyn_row_major_with_lc(la, lb, lc)?;
    match cfg.matmul_type {
        MatMulType::GEMM2X | MatMulType::GEMMX2 | MatMulType::GEMMXX => (),
        _ => return Ok(None),
    }

    let la_rest = cfg.la_rest.clone().unwrap();
    let lb_rest = cfg.lb_rest.clone().unwrap();
    let lc_rest = cfg.lc_rest.clone().unwrap();
    let count = lc_rest.size();

    // a batch of one matrix is better served by a plain gemm call
    if count <= 1 {
        return Ok(None);
    }
    // degenerate matrix sizes are handled by the fallback path
    if cfg.lc_matmul.shape()[0] == 0 || cfg.lc_matmul.shape()[1] == 0 || cfg.la_matmul.shape()[1] == 0 {
        return Ok(None);
    }

    // defer same-buffer products to the per-slice path, which can use syrk
    let lb_matmul_rev = cfg.lb_matmul.reverse_axes();
    if beta_is_zero
        && same_type::<TA, TB>()
        && same_type::<TA, TC>()
        && core::ptr::eq(a.as_ptr() as *const u8, b.as_ptr() as *const u8)
        && a.len() == b.len()
        && la_rest.shape() == lb_rest.shape()
        && la_rest.stride() == lb_rest.stride()
        && la_rest.offset() == lb_rest.offset()
        && cfg.la_matmul.shape() == lb_matmul_rev.shape()
        && cfg.la_matmul.stride() == lb_matmul_rev.stride()
    {
        return Ok(None);
    }

    Ok(Some(BatchedMatmulPieces {
        lc_matmul: cfg.lc_matmul.clone().into_dim::<Ix2>()?,
        lc_rest,
        la_matmul: cfg.la_matmul.clone().into_dim::<Ix2>()?,
        la_rest,
        lb_matmul: cfg.lb_matmul.clone().into_dim::<Ix2>()?,
        lb_rest,
    }))
}

/// Resolve which operand slice/rest plays the `A` role after a possible
/// `C^T = B^T A^T` swap.
fn roles_by_swap<'a, T>(
    swapped: bool,
    a: &'a [T],
    la_rest: &'a Layout<IxD>,
    b: &'a [T],
    lb_rest: &'a Layout<IxD>,
) -> (&'a [T], &'a Layout<IxD>, &'a [T], &'a Layout<IxD>) {
    if swapped {
        (b, lb_rest, a, la_rest)
    } else {
        (a, la_rest, b, lb_rest)
    }
}

/// Try to accelerate a broadcasted matmul with strided batched GEMM
/// (feature `use_batched_gemm_strided`).
///
/// Returns `Ok(true)` if the computation was performed, `Ok(false)` if the
/// case is not eligible and the caller should fall back (grouped batched
/// GEMM, or the existing per-slice loop).
#[cfg(feature = "use_batched_gemm_strided")]
#[allow(clippy::too_many_arguments)]
pub fn batched_matmul_strided_try<TA, TB, TC>(
    c: &mut [TC],
    lc: &Layout<IxD>,
    a: &[TA],
    la: &Layout<IxD>,
    b: &[TB],
    lb: &Layout<IxD>,
    alpha: TC,
    beta: TC,
    nthreads: usize,
) -> Result<bool>
where
    TA: Clone + Send + Sync + 'static,
    TB: Clone + Send + Sync + 'static,
    TC: Clone + Send + Sync + 'static,
    TA: Mul<TB, Output = TC>,
    TC: Mul<TC, Output = TC> + Add<TC, Output = TC> + Zero + PartialEq,
{
    let beta_is_zero = beta == TC::zero();
    let Some(pieces) = batched_matmul_prepare::<TA, TB, TC>(a, la, b, lb, lc, beta_is_zero)? else {
        return Ok(false);
    };

    macro_rules! impl_batched_dispatch {
        ($ty:ty) => {
            if same_type::<TA, $ty>() && same_type::<TB, $ty>() && same_type::<TC, $ty>() {
                let a2 = unsafe { core::slice::from_raw_parts(a.as_ptr() as *const $ty, a.len()) };
                let b2 = unsafe { core::slice::from_raw_parts(b.as_ptr() as *const $ty, b.len()) };
                let c2 = unsafe { core::slice::from_raw_parts_mut(c.as_mut_ptr() as *mut $ty, c.len()) };
                let alpha2 = unsafe { *(&alpha as *const TC as *const $ty) };
                let beta2 = unsafe { *(&beta as *const TC as *const $ty) };
                return batched_strided_core(&pieces, a2, b2, c2, alpha2, beta2, nthreads);
            }
        };
    }
    impl_batched_dispatch!(f32);
    impl_batched_dispatch!(f64);
    impl_batched_dispatch!(c32);
    impl_batched_dispatch!(c64);
    Ok(false)
}

#[cfg(feature = "use_batched_gemm_strided")]
#[allow(clippy::too_many_arguments)]
fn batched_strided_core<T>(
    pieces: &BatchedMatmulPieces,
    a: &[T],
    b: &[T],
    c: &mut [T],
    alpha: T,
    beta: T,
    nthreads: usize,
) -> Result<bool>
where
    T: 'static,
    crate::DeviceBLAS: BatchedGEMMStridedDriverAPI<T>,
{
    use crate::DeviceBLAS;

    let count = pieces.lc_rest.size();
    let Some((transa, la_m, transb, lb_m, lc_m, swapped)) =
        batched_canon_matmul(&pieces.la_matmul, &pieces.lb_matmul, &pieces.lc_matmul)
    else {
        return Ok(false);
    };
    let (a_slice, a_rest, b_slice, b_rest) = roles_by_swap(swapped, a, &pieces.la_rest, b, &pieces.lb_rest);

    // strided interface: every operand batch must be uniformly-strided, and
    // operands with nonzero stride must share the same flat order
    let (oa, sa) = match batched_flat_stride(a_rest) {
        Some(v) => v,
        None => return Ok(false),
    };
    let (ob, sb) = match batched_flat_stride(b_rest) {
        Some(v) => v,
        None => return Ok(false),
    };
    let (oc, sc) = match batched_flat_stride(&pieces.lc_rest) {
        Some(v) => v,
        None => return Ok(false),
    };
    let mut order: Option<BatchedFlatOrder> = None;
    let mut consistent = true;
    for (o, s) in [(oa, sa), (ob, sb), (oc, sc)] {
        if s > 0 {
            match order {
                None => order = Some(o),
                Some(prev) if prev == o => (),
                _ => consistent = false,
            }
        }
    }
    if !consistent {
        return Ok(false);
    }

    let (m, n, k) = batched_dims(transa, &la_m, &lc_m);
    let lda = batched_ld(&la_m);
    let ldb = batched_ld(&lb_m);
    let ldc = batched_ld(&lc_m);

    let ptr_a = unsafe { a_slice.as_ptr().add(a_rest.offset()) };
    let ptr_b = unsafe { b_slice.as_ptr().add(b_rest.offset()) };
    let ptr_c = unsafe { c.as_mut_ptr().add(pieces.lc_rest.offset()) };

    with_num_threads(nthreads, || -> Result<()> {
        unsafe {
            <DeviceBLAS as BatchedGEMMStridedDriverAPI<T>>::driver_batched_gemm_strided(
                ColMajor, transa, transb, m, n, k, alpha, ptr_a, lda, sa, ptr_b, ldb, sb, beta, ptr_c, ldc, sc,
                count,
            )
        }
    })?;
    Ok(true)
}

/// Try to accelerate a broadcasted matmul with grouped (pointer-based)
/// batched GEMM (feature `use_batched_gemm`), gathering one pointer per
/// matrix. Handles scattered batch layouts of any operand.
///
/// Returns `Ok(true)` if the computation was performed, `Ok(false)` if the
/// case is not eligible and the caller should fall back to the existing
/// per-slice loop.
#[cfg(feature = "use_batched_gemm")]
#[allow(clippy::too_many_arguments)]
pub fn batched_matmul_grouped_try<TA, TB, TC>(
    c: &mut [TC],
    lc: &Layout<IxD>,
    a: &[TA],
    la: &Layout<IxD>,
    b: &[TB],
    lb: &Layout<IxD>,
    alpha: TC,
    beta: TC,
    nthreads: usize,
) -> Result<bool>
where
    TA: Clone + Send + Sync + 'static,
    TB: Clone + Send + Sync + 'static,
    TC: Clone + Send + Sync + 'static,
    TA: Mul<TB, Output = TC>,
    TC: Mul<TC, Output = TC> + Add<TC, Output = TC> + Zero + PartialEq,
{
    let beta_is_zero = beta == TC::zero();
    let Some(pieces) = batched_matmul_prepare::<TA, TB, TC>(a, la, b, lb, lc, beta_is_zero)? else {
        return Ok(false);
    };

    macro_rules! impl_batched_dispatch {
        ($ty:ty) => {
            if same_type::<TA, $ty>() && same_type::<TB, $ty>() && same_type::<TC, $ty>() {
                let a2 = unsafe { core::slice::from_raw_parts(a.as_ptr() as *const $ty, a.len()) };
                let b2 = unsafe { core::slice::from_raw_parts(b.as_ptr() as *const $ty, b.len()) };
                let c2 = unsafe { core::slice::from_raw_parts_mut(c.as_mut_ptr() as *mut $ty, c.len()) };
                let alpha2 = unsafe { *(&alpha as *const TC as *const $ty) };
                let beta2 = unsafe { *(&beta as *const TC as *const $ty) };
                return batched_grouped_core(&pieces, a2, b2, c2, alpha2, beta2, nthreads);
            }
        };
    }
    impl_batched_dispatch!(f32);
    impl_batched_dispatch!(f64);
    impl_batched_dispatch!(c32);
    impl_batched_dispatch!(c64);
    Ok(false)
}

#[cfg(feature = "use_batched_gemm")]
#[allow(clippy::too_many_arguments)]
fn batched_grouped_core<T>(
    pieces: &BatchedMatmulPieces,
    a: &[T],
    b: &[T],
    c: &mut [T],
    alpha: T,
    beta: T,
    nthreads: usize,
) -> Result<bool>
where
    T: 'static,
    crate::DeviceBLAS: BatchedGEMMDriverAPI<T>,
{
    use crate::DeviceBLAS;

    let count = pieces.lc_rest.size();
    let Some((transa, la_m, transb, lb_m, lc_m, swapped)) =
        batched_canon_matmul(&pieces.la_matmul, &pieces.lb_matmul, &pieces.lc_matmul)
    else {
        return Ok(false);
    };
    let (a_slice, a_rest, b_slice, b_rest) = roles_by_swap(swapped, a, &pieces.la_rest, b, &pieces.lb_rest);

    let (m, n, k) = batched_dims(transa, &la_m, &lc_m);
    let lda = batched_ld(&la_m);
    let ldb = batched_ld(&lb_m);
    let ldc = batched_ld(&lc_m);

    // gather one pointer per matrix; any batch layout is accepted here
    let ita = IterLayoutColMajor::new(a_rest)?;
    let itb = IterLayoutColMajor::new(b_rest)?;
    let itc = IterLayoutColMajor::new(&pieces.lc_rest)?;
    let mut a_ptrs: Vec<*const T> = Vec::with_capacity(count);
    let mut b_ptrs: Vec<*const T> = Vec::with_capacity(count);
    let mut c_ptrs: Vec<*mut T> = Vec::with_capacity(count);
    for (ia, ib, ic) in izip!(ita, itb, itc) {
        a_ptrs.push(unsafe { a_slice.as_ptr().add(ia) });
        b_ptrs.push(unsafe { b_slice.as_ptr().add(ib) });
        c_ptrs.push(unsafe { c.as_mut_ptr().add(ic) });
    }

    with_num_threads(nthreads, || -> Result<()> {
        unsafe {
            <DeviceBLAS as BatchedGEMMDriverAPI<T>>::driver_batched_gemm(
                ColMajor,
                &[transa],
                &[transb],
                &[m],
                &[n],
                &[k],
                &[alpha],
                &a_ptrs,
                &[lda],
                &b_ptrs,
                &[ldb],
                &[beta],
                &c_ptrs,
                &[ldc],
                1,
                &[count],
            )
        }
    })?;
    Ok(true)
}

/* #endregion */

#[cfg(test)]
mod test {
    use super::*;
    use num::traits::ConstZero;
    use rstsr_core::prelude_dev::linspace;

    // naive reference for one row-major [m, k] @ [k, n] matrix
    fn naive_matmul(m: usize, n: usize, k: usize, a: &[f64], b: &[f64]) -> Vec<f64> {
        let mut c = vec![0.0; m * n];
        for i in 0..m {
            for j in 0..n {
                let mut acc = 0.0;
                for p in 0..k {
                    acc += a[i * k + p] * b[p * n + j];
                }
                c[i * n + j] = acc;
            }
        }
        c
    }

    // read a col-major [rows, cols] matrix slice into row-major order
    fn col_to_row(v: &[f64], rows: usize, cols: usize) -> Vec<f64> {
        (0..rows).flat_map(|r| (0..cols).map(move |c| v[c * rows + r])).collect()
    }

    #[cfg(feature = "use_batched_gemm")]
    #[test]
    fn test_batched_gemm_f64_grouped() {
        // batch of 3 matrices, m=2, k=3, n=4, col-major storage per matrix
        let (m, n, k, batch) = (2usize, 4usize, 3usize, 3usize);
        let a_data: Vec<f64> = linspace((0.0, 1.0, batch * m * k)).into_vec();
        let b_data: Vec<f64> = linspace((1.0, 2.0, batch * k * n)).into_vec();
        let mut c_data = vec![f64::ZERO; batch * m * n];

        let a_ptrs: Vec<*const f64> = (0..batch).map(|i| unsafe { a_data.as_ptr().add(i * m * k) }).collect();
        let b_ptrs: Vec<*const f64> = (0..batch).map(|i| unsafe { b_data.as_ptr().add(i * k * n) }).collect();
        let c_ptrs: Vec<*mut f64> =
            (0..batch).map(|i| unsafe { c_data.as_mut_ptr().add(i * m * n) }).collect();

        unsafe {
            batched_gemm_f64(
                ColMajor,
                &[FlagTrans::N],
                &[FlagTrans::N],
                &[m],
                &[n],
                &[k],
                &[1.0],
                &a_ptrs,
                &[m],
                &b_ptrs,
                &[k],
                &[0.0],
                &c_ptrs,
                &[m],
                1,
                &[batch],
            )
        }
        .unwrap();

        // two groups with identical parameters must give the same result
        let mut c2_data = vec![f64::ZERO; batch * m * n];
        let c2_ptrs: Vec<*mut f64> =
            (0..batch).map(|i| unsafe { c2_data.as_mut_ptr().add(i * m * n) }).collect();
        unsafe {
            batched_gemm_f64(
                ColMajor,
                &[FlagTrans::N, FlagTrans::N],
                &[FlagTrans::N, FlagTrans::N],
                &[m, m],
                &[n, n],
                &[k, k],
                &[1.0, 1.0],
                &a_ptrs,
                &[m, m],
                &b_ptrs,
                &[k, k],
                &[0.0, 0.0],
                &c2_ptrs,
                &[m, m],
                2,
                &[2, 1],
            )
        }
        .unwrap();
        assert_eq!(c_data, c2_data);

        // per-matrix reference
        for i in 0..batch {
            let a_rm = col_to_row(&a_data[i * m * k..(i + 1) * m * k], m, k);
            let b_rm = col_to_row(&b_data[i * k * n..(i + 1) * k * n], k, n);
            let expect = naive_matmul(m, n, k, &a_rm, &b_rm);
            let got = col_to_row(&c_data[i * m * n..(i + 1) * m * n], m, n);
            assert!(got.iter().zip(expect.iter()).all(|(x, y)| (x - y).abs() < 1e-10));
        }

        // alpha/beta accumulate
        let mut c3_data = vec![1.0; batch * m * n];
        let c3_ptrs: Vec<*mut f64> =
            (0..batch).map(|i| unsafe { c3_data.as_mut_ptr().add(i * m * n) }).collect();
        unsafe {
            batched_gemm_f64(
                ColMajor,
                &[FlagTrans::N],
                &[FlagTrans::N],
                &[m],
                &[n],
                &[k],
                &[2.0],
                &a_ptrs,
                &[m],
                &b_ptrs,
                &[k],
                &[3.0],
                &c3_ptrs,
                &[m],
                1,
                &[batch],
            )
        }
        .unwrap();
        for i in 0..batch {
            let a_rm = col_to_row(&a_data[i * m * k..(i + 1) * m * k], m, k);
            let b_rm = col_to_row(&b_data[i * k * n..(i + 1) * k * n], k, n);
            let expect = naive_matmul(m, n, k, &a_rm, &b_rm);
            for r in 0..m {
                for q in 0..n {
                    let got = c3_data[i * m * n + q * m + r];
                    let want = 2.0 * expect[r * n + q] + 3.0;
                    assert!((got - want).abs() < 1e-10);
                }
            }
        }
    }

    #[cfg(feature = "use_batched_gemm_strided")]
    #[test]
    fn test_batched_gemm_strided_f64() {
        // batch of 3 matrices, m=2, k=3, n=4, col-major storage per matrix
        let (m, n, k, batch) = (2usize, 4usize, 3usize, 3usize);
        let a_data: Vec<f64> = linspace((0.0, 1.0, batch * m * k)).into_vec();
        let b_data: Vec<f64> = linspace((1.0, 2.0, batch * k * n)).into_vec();
        let mut c_data = vec![f64::ZERO; batch * m * n];

        unsafe {
            batched_gemm_strided_f64(
                ColMajor,
                FlagTrans::N,
                FlagTrans::N,
                m,
                n,
                k,
                1.0,
                a_data.as_ptr(),
                m,
                m * k,
                b_data.as_ptr(),
                k,
                k * n,
                0.0,
                c_data.as_mut_ptr(),
                m,
                m * n,
                batch,
            )
        }
        .unwrap();

        // reference via the grouped interface
        #[cfg(feature = "use_batched_gemm")]
        {
            let mut c_ref = vec![f64::ZERO; batch * m * n];
            let a_ptrs: Vec<*const f64> =
                (0..batch).map(|i| unsafe { a_data.as_ptr().add(i * m * k) }).collect();
            let b_ptrs: Vec<*const f64> =
                (0..batch).map(|i| unsafe { b_data.as_ptr().add(i * k * n) }).collect();
            let c_ptrs: Vec<*mut f64> =
                (0..batch).map(|i| unsafe { c_ref.as_mut_ptr().add(i * m * n) }).collect();
            unsafe {
                batched_gemm_f64(
                    ColMajor, &[FlagTrans::N], &[FlagTrans::N], &[m], &[n], &[k], &[1.0], &a_ptrs, &[m],
                    &b_ptrs, &[k], &[0.0], &c_ptrs, &[m], 1, &[batch],
                )
            }
            .unwrap();
            assert_eq!(c_data, c_ref);
        }

        // stride-0 broadcast: every batch element uses the first B matrix
        let mut c_b = vec![f64::ZERO; batch * m * n];
        unsafe {
            batched_gemm_strided_f64(
                ColMajor,
                FlagTrans::N,
                FlagTrans::N,
                m,
                n,
                k,
                1.0,
                a_data.as_ptr(),
                m,
                m * k,
                b_data.as_ptr(),
                k,
                0,
                0.0,
                c_b.as_mut_ptr(),
                m,
                m * n,
                batch,
            )
        }
        .unwrap();
        let a0_rm = col_to_row(&b_data[..k * n], k, n);
        for i in 0..batch {
            let a_rm = col_to_row(&a_data[i * m * k..(i + 1) * m * k], m, k);
            let expect = naive_matmul(m, n, k, &a_rm, &a0_rm);
            let got = col_to_row(&c_b[i * m * n..(i + 1) * m * n], m, n);
            assert!(got.iter().zip(expect.iter()).all(|(x, y)| (x - y).abs() < 1e-10));
        }
    }

    #[cfg(feature = "use_batched_gemm_strided")]
    #[test]
    fn test_batched_matmul_strided_try() {
        // rank-3 batched matmul [3, 2, 3] @ [3, 3, 4] -> [3, 2, 4], row-major
        let (m, n, k, batch) = (2usize, 4usize, 3usize, 3usize);
        let a_data: Vec<f64> = linspace((0.0, 1.0, batch * m * k)).into_vec();
        let b_data: Vec<f64> = linspace((1.0, 2.0, batch * k * n)).into_vec();
        let mut c_data = vec![f64::ZERO; batch * m * n];

        let la = [batch, m, k].c().to_dim::<IxD>().unwrap();
        let lb = [batch, k, n].c().to_dim::<IxD>().unwrap();
        let lc = [batch, m, n].c().to_dim::<IxD>().unwrap();
        let handled =
            batched_matmul_strided_try(&mut c_data, &lc, &a_data, &la, &b_data, &lb, 1.0, 0.0, 16).unwrap();
        assert!(handled);

        for i in 0..batch {
            let a_rm = &a_data[i * m * k..(i + 1) * m * k];
            let b_rm = &b_data[i * k * n..(i + 1) * k * n];
            let expect = naive_matmul(m, n, k, a_rm, b_rm);
            let got = &c_data[i * m * n..(i + 1) * m * n];
            assert!(got.iter().zip(expect.iter()).all(|(x, y)| (x - y).abs() < 1e-10));
        }
    }

    #[cfg(feature = "use_batched_gemm")]
    #[test]
    fn test_batched_matmul_grouped_try_scattered() {
        // rank-4 batched matmul with a scattered A batch (strided slice of an
        // outer batch dim): rest strides [24, 6] cannot flatten to one stride
        let (m, n, k) = (2usize, 4usize, 3usize);
        let (b0, b1) = (2usize, 2usize);
        let batch = b0 * b1;
        let a_data: Vec<f64> = linspace((0.0, 1.0, 200)).into_vec();
        let b_data: Vec<f64> = linspace((1.0, 2.0, batch * k * n)).into_vec();
        let mut c_data = vec![f64::ZERO; batch * m * n];

        // A: shape [2, 2, 2, 3], strides [24, 6, 3, 1] (scattered on dim 0)
        let la = Layout::new(vec![b0, b1, m, k], vec![24, 6, 3, 1], 0).unwrap();
        let lb = [b0, b1, k, n].c().to_dim::<IxD>().unwrap();
        let lc = [b0, b1, m, n].c().to_dim::<IxD>().unwrap();
        let handled =
            batched_matmul_grouped_try(&mut c_data, &lc, &a_data, &la, &b_data, &lb, 1.0, 0.0, 1).unwrap();
        assert!(handled);

        let mut idx = 0;
        for i0 in 0..b0 {
            for i1 in 0..b1 {
                let base_a = i0 * 24 + i1 * 6;
                let a_rm = &a_data[base_a..base_a + m * k];
                let base_b = (i0 * b1 + i1) * k * n;
                let b_rm = &b_data[base_b..base_b + k * n];
                let expect = naive_matmul(m, n, k, a_rm, b_rm);
                let base_c = idx * m * n;
                let got = &c_data[base_c..base_c + m * n];
                assert!(got.iter().zip(expect.iter()).all(|(x, y)| (x - y).abs() < 1e-10));
                idx += 1;
            }
        }
        assert_eq!(idx, batch);
    }

    #[cfg(all(feature = "use_batched_gemm", feature = "use_batched_gemm_strided"))]
    #[test]
    fn test_batched_gemm_c32_grouped() {
        let (m, n, k, batch) = (2usize, 3usize, 3usize, 2usize);
        let a_data: Vec<c32> = linspace((c32::new(1., 1.), c32::new(6., 6.), batch * m * k)).into_vec();
        let b_data: Vec<c32> = linspace((c32::new(1., -1.), c32::new(9., -9.), batch * k * n)).into_vec();
        let mut c_data = vec![c32::ZERO; batch * m * n];

        let a_ptrs: Vec<*const c32> = (0..batch).map(|i| unsafe { a_data.as_ptr().add(i * m * k) }).collect();
        let b_ptrs: Vec<*const c32> = (0..batch).map(|i| unsafe { b_data.as_ptr().add(i * k * n) }).collect();
        let c_ptrs: Vec<*mut c32> =
            (0..batch).map(|i| unsafe { c_data.as_mut_ptr().add(i * m * n) }).collect();

        unsafe {
            batched_gemm_c32(
                ColMajor,
                &[FlagTrans::N],
                &[FlagTrans::N],
                &[m],
                &[n],
                &[k],
                &[c32::ONE],
                &a_ptrs,
                &[m],
                &b_ptrs,
                &[k],
                &[c32::ZERO],
                &c_ptrs,
                &[m],
                1,
                &[batch],
            )
        }
        .unwrap();

        // cross-check with per-matrix gemm (col-major layouts, matching the
        // col-major packing above)
        for i in 0..batch {
            let la = [m, k].f();
            let lb = [k, n].f();
            let lc = [m, n].f();
            let mut c_ref = vec![c32::ZERO; m * n];
            let pool = None;
            crate::matmul_impl::gemm_blas_no_conj_c32(
                &mut c_ref,
                &lc,
                &a_data[i * m * k..(i + 1) * m * k],
                &la,
                &b_data[i * k * n..(i + 1) * k * n],
                &lb,
                c32::ONE,
                c32::ZERO,
                pool,
            )
            .unwrap();
            // different kernels round differently in f32: compare with tolerance
            let got = &c_data[i * m * n..(i + 1) * m * n];
            assert!(got.iter().zip(c_ref.iter()).all(|(x, y)| {
                (x.re - y.re).abs() < 1e-4 * (1.0 + y.re.abs()) && (x.im - y.im).abs() < 1e-4
            }));
        }
    }
}
