/*!
Grouped batched GEMM driver (`?gemm_batch` extension).

Most or all contents generated by AI (model glm-5.3).
*/

use crate::prelude_dev::*;
use rstsr_core::prelude_dev::*;

/* #region builder */

/// Builder for a uniform batched GEMM over the grouped (`?gemm_batch`)
/// extension: batched matrix product `C[b, ..] = alpha * A[b, ..] B[b, ..]`
/// into a freshly allocated output.
///
/// The operands accept any batch layout (uniformly-strided or scattered);
/// one pointer is gathered per matrix. Both operands must have rank >= 3,
/// identical batch shapes, and uniform matrix shapes.
#[derive(Builder)]
#[builder(pattern = "owned", no_std, build_fn(error = "Error"))]
pub struct BatchedGEMM_<'a, 'b, B, T, D>
where
    T: BlasFloat,
    B: DeviceAPI<T>,
    D: DimAPI,
{
    pub a: TensorView<'a, T, B, D>,
    pub b: TensorView<'b, T, B, D>,

    #[builder(setter(into), default = "T::one()")]
    pub alpha: T,
    #[builder(setter(into), default = "T::zero()")]
    pub beta: T,
}

pub type BatchedGEMM<'a, 'b, B, T, D> = BatchedGEMM_Builder<'a, 'b, B, T, D>;


/// Output layout for batched GEMM: the per-matrix `[m, n]` piece is
/// col-major contiguous (ld = m), and the batch dims are packed in the given
/// flat order. A fully-col-major output would leave every matrix piece
/// strided (batch stride leaks into the matrix dims), which no gemm call can
/// express without a copy.
fn batched_output_layout(sc: &[usize], order: BatchedFlatOrder) -> Result<Layout<IxD>> {
    let n = sc.len();
    rstsr_assert!(n >= 3, InvalidLayout)?;
    let mut strides = vec![0isize; n];
    strides[n - 2] = 1;
    strides[n - 1] = sc[n - 2] as isize;
    let base = (sc[n - 2] * sc[n - 1]) as isize;
    match order {
        BatchedFlatOrder::RowMajor => {
            // stride[i] = m*n * prod(shape[i+1 .. n-2])
            let mut acc = base;
            for i in (0..n - 2).rev() {
                strides[i] = acc;
                acc *= sc[i] as isize;
            }
        },
        BatchedFlatOrder::ColMajor => {
            // stride[i] = m*n * prod(shape[..i])
            let mut acc = base;
            for i in 0..n - 2 {
                strides[i] = acc;
                acc *= sc[i] as isize;
            }
        },
    }
    Layout::new(sc.to_vec(), strides, 0)
}

impl<B, T, D> BatchedGEMM_<'_, '_, B, T, D>
where
    T: BlasFloat,
    B: DeviceAPI<T, Raw = Vec<T>> + DeviceCreationNumAPI<T> + DeviceRayonAPI + BlasThreadAPI + BatchedGEMMDriverAPI<T>,
    D: DimAPI,
{
    pub fn run(self) -> Result<Tensor<T, B, D>> {
        let Self { a, b, alpha, beta } = self;
        rstsr_assert!(a.device().same_device(b.device()), DeviceMismatch)?;
        let device = a.device().clone();
        let nthreads = device.get_current_pool().map_or(1, |pool| pool.current_num_threads());

        let la = a.layout().to_dim::<IxD>()?;
        let lb = b.layout().to_dim::<IxD>()?;
        let (shape_a, shape_b): (&[usize], &[usize]) = (la.shape().as_ref(), lb.shape().as_ref());
        let n = la.ndim();
        rstsr_assert!(n >= 3, InvalidLayout)?;
        rstsr_assert_eq!(n, lb.ndim(), InvalidLayout)?;
        rstsr_assert_eq!(&shape_a[..n - 2], &shape_b[..n - 2], InvalidLayout)?;
        rstsr_assert_eq!(la.shape()[n - 1], lb.shape()[n - 2], InvalidLayout)?;
        let count: usize = shape_a[..n - 2].iter().product();
        rstsr_assert!(count > 0, InvalidLayout)?;
        let (m, nn) = (la.shape()[n - 2], lb.shape()[n - 1]);

        // fresh output: col-major matrix pieces, row-major-packed batch dims
        let mut sc: Vec<usize> = shape_a[..n - 2].to_vec();
        sc.push(m);
        sc.push(nn);
        let lc_out = batched_output_layout(&sc, BatchedFlatOrder::RowMajor)?;
        let mut c = zeros_f((lc_out, &device))?;

        // split, canonicalize, gather one pointer per matrix
        let (la_rest, la_m) = la.dim_split_at(-2)?;
        let (lb_rest, lb_m) = lb.dim_split_at(-2)?;
        let lc = c.layout().clone();
        let (lc_rest, lc_m) = lc.dim_split_at(-2)?;
        let la_m = la_m.into_dim::<Ix2>()?;
        let lb_m = lb_m.into_dim::<Ix2>()?;
        let lc_m = lc_m.into_dim::<Ix2>()?;
        let Some((transa, la_m, transb, lb_m, lc_m, swapped)) = batched_canon_matmul(&la_m, &lb_m, &lc_m)
        else {
            return rstsr_invalid!("BatchedGEMM: matrix layouts are not gemm-expressible")?;
        };
        let (a_rest, b_rest) = if swapped { (&lb_rest, &la_rest) } else { (&la_rest, &lb_rest) };
        let (a_v, b_v) = if swapped { (&b, &a) } else { (&a, &b) };
        let (m, nn, k) = batched_dims(transa, &la_m, &lc_m);
        let lda = batched_ld(&la_m);
        let ldb = batched_ld(&lb_m);
        let ldc = batched_ld(&lc_m);

        let ita = IterLayoutColMajor::new(a_rest)?;
        let itb = IterLayoutColMajor::new(b_rest)?;
        let itc = IterLayoutColMajor::new(&lc_rest)?;
        let mut a_ptrs: Vec<*const T> = Vec::with_capacity(count);
        let mut b_ptrs: Vec<*const T> = Vec::with_capacity(count);
        let mut c_ptrs: Vec<*mut T> = Vec::with_capacity(count);
        let a_raw = a_v.raw().as_ptr();
        let b_raw = b_v.raw().as_ptr();
        let c_raw = c.view_mut().raw_mut().as_mut_ptr();
        for (ia, ib, ic) in izip!(ita, itb, itc) {
            a_ptrs.push(unsafe { a_raw.add(ia) });
            b_ptrs.push(unsafe { b_raw.add(ib) });
            c_ptrs.push(unsafe { c_raw.add(ic) });
        }

        device.with_blas_num_threads(nthreads, || -> Result<()> {
            unsafe {
                <B as BatchedGEMMDriverAPI<T>>::driver_batched_gemm(
                    ColMajor,
                    &[transa],
                    &[transb],
                    &[m],
                    &[nn],
                    &[k],
                    &[alpha],
                    &a_ptrs,
                    &[lda],
                    &b_ptrs,
                    &[ldb],
                    &[beta],
                    &c_ptrs,
                    &[ldc],
                    1,
                    &[count],
                )
            }
        })?;
        Ok(c.into_dim::<D>())
    }
}

/* #endregion */

/// Driver capability for grouped batched GEMM (`?gemm_batch`).
///
/// This wraps the pointer-array batched GEMM extension: each group carries its
/// own parameters, and `group_size[i]` consecutive pointer-array entries use
/// the parameters of group `i`. The uniform pointer-batch case is
/// `group_count == 1`, `group_size == [batch_count]`.
///
/// This is a BLAS *extension* (e.g. OpenBLAS >= 0.3.26, MKL), not standard
/// BLAS, hence it is not bound to any standard driver trait.
pub trait BatchedGEMMDriverAPI<T> {
    /// Grouped batched GEMM.
    ///
    /// All parameter slices must have length `group_count` except `a`/`b`/`c`
    /// (pointer arrays, total length `sum(group_size)`); strides and leading
    /// dimensions are in elements.
    ///
    /// # Safety
    ///
    /// All pointers in `a`, `b`, `c` must be valid for the shapes and leading
    /// dimensions given by the parameter arrays, for the whole duration of
    /// the call.
    #[allow(clippy::too_many_arguments)]
    unsafe fn driver_batched_gemm(
        order: FlagOrder,
        transa: &[FlagTrans],
        transb: &[FlagTrans],
        m: &[usize],
        n: &[usize],
        k: &[usize],
        alpha: &[T],
        a: &[*const T],
        lda: &[usize],
        b: &[*const T],
        ldb: &[usize],
        beta: &[T],
        c: &[*mut T],
        ldc: &[usize],
        group_count: usize,
        group_size: &[usize],
    ) -> Result<()>;
}
