/*!
Strided batched GEMM driver (`?gemm_batch_strided` extension).

Most or all contents generated by AI (model glm-5.3).
*/

use crate::prelude_dev::*;
use rstsr_core::prelude_dev::*;

/* #region builder */

/// Builder for a strided batched GEMM over the `?gemm_batch_strided`
/// extension: batched matrix product into a freshly allocated output.
///
/// Beyond the `BatchedGEMM_` contract, both operands must be
/// *uniformly-strided* batches that reduce to a single stride per operand in
/// a common flat order; the output is allocated contiguously in that same
/// order so all three operands enter one strided call.
#[derive(Builder)]
#[builder(pattern = "owned", no_std, build_fn(error = "Error"))]
pub struct BatchedGEMMStrided_<'a, 'b, B, T, D>
where
    T: BlasFloat,
    B: DeviceAPI<T>,
    D: DimAPI,
{
    pub a: TensorView<'a, T, B, D>,
    pub b: TensorView<'b, T, B, D>,

    #[builder(setter(into), default = "T::one()")]
    pub alpha: T,
    #[builder(setter(into), default = "T::zero()")]
    pub beta: T,
}

pub type BatchedGEMMStrided<'a, 'b, B, T, D> = BatchedGEMMStrided_Builder<'a, 'b, B, T, D>;


/// Output layout for batched GEMM: the per-matrix `[m, n]` piece is
/// col-major contiguous (ld = m), and the batch dims are packed in the given
/// flat order. A fully-col-major output would leave every matrix piece
/// strided (batch stride leaks into the matrix dims), which no gemm call can
/// express without a copy.
fn batched_output_layout(sc: &[usize], order: BatchedFlatOrder) -> Result<Layout<IxD>> {
    let n = sc.len();
    rstsr_assert!(n >= 3, InvalidLayout)?;
    let mut strides = vec![0isize; n];
    strides[n - 2] = 1;
    strides[n - 1] = sc[n - 2] as isize;
    let base = (sc[n - 2] * sc[n - 1]) as isize;
    match order {
        BatchedFlatOrder::RowMajor => {
            // stride[i] = m*n * prod(shape[i+1 .. n-2])
            let mut acc = base;
            for i in (0..n - 2).rev() {
                strides[i] = acc;
                acc *= sc[i] as isize;
            }
        },
        BatchedFlatOrder::ColMajor => {
            // stride[i] = m*n * prod(shape[..i])
            let mut acc = base;
            for i in 0..n - 2 {
                strides[i] = acc;
                acc *= sc[i] as isize;
            }
        },
    }
    Layout::new(sc.to_vec(), strides, 0)
}

impl<B, T, D> BatchedGEMMStrided_<'_, '_, B, T, D>
where
    T: BlasFloat,
    B: DeviceAPI<T, Raw = Vec<T>> + DeviceCreationNumAPI<T> + DeviceRayonAPI + BlasThreadAPI + BatchedGEMMStridedDriverAPI<T>,
    D: DimAPI,
{
    pub fn run(self) -> Result<Tensor<T, B, D>> {
        let Self { a, b, alpha, beta } = self;
        rstsr_assert!(a.device().same_device(b.device()), DeviceMismatch)?;
        let device = a.device().clone();
        let nthreads = device.get_current_pool().map_or(1, |pool| pool.current_num_threads());

        let la = a.layout().to_dim::<IxD>()?;
        let lb = b.layout().to_dim::<IxD>()?;
        let (shape_a, shape_b): (&[usize], &[usize]) = (la.shape().as_ref(), lb.shape().as_ref());
        let n = la.ndim();
        rstsr_assert!(n >= 3, InvalidLayout)?;
        rstsr_assert_eq!(n, lb.ndim(), InvalidLayout)?;
        rstsr_assert_eq!(&shape_a[..n - 2], &shape_b[..n - 2], InvalidLayout)?;
        rstsr_assert_eq!(la.shape()[n - 1], lb.shape()[n - 2], InvalidLayout)?;
        let count: usize = shape_a[..n - 2].iter().product();
        rstsr_assert!(count > 0, InvalidLayout)?;
        let (m, nn) = (la.shape()[n - 2], lb.shape()[n - 1]);

        // strided interface: uniformly-strided batches in a common flat order
        let (la_rest, la_m) = la.dim_split_at(-2)?;
        let (lb_rest, lb_m) = lb.dim_split_at(-2)?;
        let (oa, sa) = match batched_flat_stride(&la_rest) {
            Some(v) => v,
            None => return rstsr_invalid!("BatchedGEMMStrided: A batch dims are scattered")?,
        };
        let (ob, sb) = match batched_flat_stride(&lb_rest) {
            Some(v) => v,
            None => return rstsr_invalid!("BatchedGEMMStrided: B batch dims are scattered")?,
        };
        rstsr_assert!(sa == 0 || sb == 0 || oa == ob, InvalidLayout)?;

        // fresh output: col-major matrix pieces, batch dims packed in the
        // inputs' flat order
        let mut sc: Vec<usize> = shape_a[..n - 2].to_vec();
        sc.push(m);
        sc.push(nn);
        let lc_out = batched_output_layout(&sc, oa)?;
        let mut c = zeros_f((lc_out, &device))?;

        let lc = c.layout().clone();
        let (lc_rest, lc_m) = lc.dim_split_at(-2)?;
        let la_m = la_m.into_dim::<Ix2>()?;
        let lb_m = lb_m.into_dim::<Ix2>()?;
        let lc_m = lc_m.into_dim::<Ix2>()?;
        let Some((transa, la_m, transb, lb_m, lc_m, swapped)) = batched_canon_matmul(&la_m, &lb_m, &lc_m)
        else {
            return rstsr_invalid!("BatchedGEMMStrided: matrix layouts are not gemm-expressible")?;
        };
        let (a_rest, b_rest) = if swapped { (&lb_rest, &la_rest) } else { (&la_rest, &lb_rest) };
        let (a_v, b_v) = if swapped { (&b, &a) } else { (&a, &b) };
        let (sa, sb) = if swapped { (sb, sa) } else { (sa, sb) };
        let (m, nn, k) = batched_dims(transa, &la_m, &lc_m);
        let lda = batched_ld(&la_m);
        let ldb = batched_ld(&lb_m);
        let ldc = batched_ld(&lc_m);
        let (oc, sc_stride) = match batched_flat_stride(&lc_rest) {
            Some(v) => v,
            None => return rstsr_invalid!("BatchedGEMMStrided: output batch is scattered")?,
        };
        rstsr_assert!(sc_stride > 0 && (sa == 0 || sb == 0 || oc == oa), InvalidLayout)?;

        let ptr_a = unsafe { a_v.raw().as_ptr().add(a_rest.offset()) };
        let ptr_b = unsafe { b_v.raw().as_ptr().add(b_rest.offset()) };
        let ptr_c = unsafe { c.view_mut().raw_mut().as_mut_ptr().add(lc_rest.offset()) };

        device.with_blas_num_threads(nthreads, || -> Result<()> {
            unsafe {
                <B as BatchedGEMMStridedDriverAPI<T>>::driver_batched_gemm_strided(
                    ColMajor, transa, transb, m, nn, k, alpha, ptr_a, lda, sa, ptr_b, ldb, sb, beta, ptr_c, ldc,
                    sc_stride, count,
                )
            }
        })?;
        Ok(c.into_dim::<D>())
    }
}

/* #endregion */

/// Driver capability for strided batched GEMM (`?gemm_batch_strided`).
///
/// One parameter set for the whole batch; the `i`-th matrix of an operand is
/// at `base + i * stride` (strides in elements). `stride == 0` is legal and
/// reuses the same matrix for every batch element (the broadcast case).
///
/// This is a BLAS *extension* (e.g. OpenBLAS >= 0.3.34, MKL), not standard
/// BLAS, hence it is not bound to any standard driver trait.
pub trait BatchedGEMMStridedDriverAPI<T> {
    /// Strided batched GEMM.
    ///
    /// # Safety
    ///
    /// `a`, `b`, `c` must be valid for the shapes given by `m`, `n`, `k` and
    /// the leading dimensions, for `batch_count` matrices spaced by the
    /// respective strides, for the whole duration of the call.
    #[allow(clippy::too_many_arguments)]
    unsafe fn driver_batched_gemm_strided(
        order: FlagOrder,
        transa: FlagTrans,
        transb: FlagTrans,
        m: usize,
        n: usize,
        k: usize,
        alpha: T,
        a: *const T,
        lda: usize,
        stride_a: usize,
        b: *const T,
        ldb: usize,
        stride_b: usize,
        beta: T,
        c: *mut T,
        ldc: usize,
        stride_c: usize,
        batch_count: usize,
    ) -> Result<()>;
}
