/*!
Extensions to standard BLAS.

These traits describe device capabilities that are *not* part of standard
BLAS/LAPACK (e.g. batched GEMM extensions exposed by some backends). They are
deliberately standalone: they do not supertrait [`crate::trait_def::BlasDriverAPI`]
or [`crate::trait_def::LapackDriverAPI`], and backends without the extension
simply do not implement them.

Most or all contents generated by AI (model glm-5.3).
*/

pub mod batched_gemm;
pub mod batched_gemm_strided;

pub use batched_gemm::*;
pub use batched_gemm_strided::*;
