/*!
Grouped batched GEMM driver impl for the OpenBLAS device.

Most or all contents generated by AI (model glm-5.3).
*/

use duplicate::duplicate_item;
use num::Complex;
use rstsr_blas_traits::prelude::*;
use rstsr_common::prelude::*;
use rstsr_core::prelude_dev::*;

#[duplicate_item(
    T              fn_name            ;
   [f32]           [batched_gemm_f32] ;
   [f64]           [batched_gemm_f64] ;
   [Complex<f32>]  [batched_gemm_c32] ;
   [Complex<f64>]  [batched_gemm_c64] ;
)]
impl BatchedGEMMDriverAPI<T> for crate::DeviceBLAS {
    unsafe fn driver_batched_gemm(
        order: FlagOrder,
        transa: &[FlagTrans],
        transb: &[FlagTrans],
        m: &[usize],
        n: &[usize],
        k: &[usize],
        alpha: &[T],
        a: &[*const T],
        lda: &[usize],
        b: &[*const T],
        ldb: &[usize],
        beta: &[T],
        c: &[*mut T],
        ldc: &[usize],
        group_count: usize,
        group_size: &[usize],
    ) -> Result<()> {
        crate::batched_gemm_impl::fn_name(
            order, transa, transb, m, n, k, alpha, a, lda, b, ldb, beta, c, ldc, group_count, group_size,
        )
    }
}
