/*!
Strided batched GEMM driver impl for the OpenBLAS device.

Most or all contents generated by AI (model glm-5.3).
*/

use duplicate::duplicate_item;
use num::Complex;
use rstsr_blas_traits::prelude::*;
use rstsr_common::prelude::*;
use rstsr_core::prelude_dev::*;

#[duplicate_item(
    T              fn_name                    ;
   [f32]           [batched_gemm_strided_f32] ;
   [f64]           [batched_gemm_strided_f64] ;
   [Complex<f32>]  [batched_gemm_strided_c32] ;
   [Complex<f64>]  [batched_gemm_strided_c64] ;
)]
impl BatchedGEMMStridedDriverAPI<T> for crate::DeviceBLAS {
    unsafe fn driver_batched_gemm_strided(
        order: FlagOrder,
        transa: FlagTrans,
        transb: FlagTrans,
        m: usize,
        n: usize,
        k: usize,
        alpha: T,
        a: *const T,
        lda: usize,
        stride_a: usize,
        b: *const T,
        ldb: usize,
        stride_b: usize,
        beta: T,
        c: *mut T,
        ldc: usize,
        stride_c: usize,
        batch_count: usize,
    ) -> Result<()> {
        crate::batched_gemm_impl::fn_name(
            order, transa, transb, m, n, k, alpha, a, lda, stride_a, b, ldb, stride_b, beta, c, ldc,
            stride_c, batch_count,
        )
    }
}
