// Most or all contents generated by AI (model glm-5.2).
pub mod test_arange;
pub mod test_eye;
pub mod test_from_scalar;
pub mod test_full;
pub mod test_linspace;
pub mod test_ones;
pub mod test_tril_triu;
pub mod test_zeros;

pub static CATEGORY: &str = "creation";
