// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_tril_triu {
    use super::*;
    static FUNC: &str = "numpy_tril_triu";

    #[test]
    fn test_ndim2() {
        // NumPy v2.5.2, lib/tests/test_twodim_base.py, test_tril_triu_ndim2 (line 335)
        crate::specify_test!("test_ndim2");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = np.ones((2, 2))
        // b = np.tril(a); c = np.triu(a)
        // assert_array_equal(b, [[1, 0], [1, 1]])
        // assert_array_equal(c, b.T)  i.e. [[1, 1], [0, 1]]
        let a: Tensor<i32, _> = rt::ones(([2, 2], &device));
        let b = rt::tril((&a, 0));
        assert_equal(&b, rt::tensor_from_nested!([[1, 0], [1, 1]], &device), None);
        let c = rt::triu((&a, 0));
        assert_equal(&c, rt::tensor_from_nested!([[1, 1], [0, 1]], &device), None);
    }

    #[test]
    fn test_ndim3() {
        // NumPy v2.5.2, lib/tests/test_twodim_base.py, test_tril_triu_ndim3 (line 347)
        crate::specify_test!("test_ndim3");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = [[[1,1],[1,1]], [[1,1],[1,0]], [[1,1],[0,0]]]
        let a = rt::tensor_from_nested!([[[1, 1], [1, 1]], [[1, 1], [1, 0]], [[1, 1], [0, 0]]], &device);
        // a_tril_desired = [[[1,0],[1,1]], [[1,0],[1,0]], [[1,0],[0,0]]]
        let tril_desired = rt::tensor_from_nested!([[[1, 0], [1, 1]], [[1, 0], [1, 0]], [[1, 0], [0, 0]]], &device);
        // a_triu_desired = [[[1,1],[0,1]], [[1,1],[0,0]], [[1,1],[0,0]]]
        let triu_desired = rt::tensor_from_nested!([[[1, 1], [0, 1]], [[1, 1], [0, 0]], [[1, 1], [0, 0]]], &device);
        assert_equal(rt::tril((&a, 0)), &tril_desired, None);
        assert_equal(rt::triu((&a, 0)), &triu_desired, None);
    }

    #[test]
    fn test_with_offset() {
        crate::specify_test!("test_with_offset");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.tril(ones((3,3)), k=1) keeps the first superdiagonal too:
        // [[1,1,0],[1,1,1],[1,1,1]] (k=1 lower-includes the superdiagonal)
        let a: Tensor<i32, _> = rt::ones(([3, 3], &device));
        let tril1 = rt::tril((&a, 1));
        assert_equal(&tril1, rt::tensor_from_nested!([[1, 1, 0], [1, 1, 1], [1, 1, 1]], &device), None);
        // np.triu(ones((3,3)), k=-1):
        // [[1,1,1],[1,1,1],[0,1,1]]
        let triu_neg1 = rt::triu((&a, -1));
        assert_equal(&triu_neg1, rt::tensor_from_nested!([[1, 1, 1], [1, 1, 1], [0, 1, 1]], &device), None);
    }
}

#[cfg(test)]
mod custom_tril_triu {
    use super::*;
    static FUNC: &str = "custom_tril_triu";

    #[test]
    fn test_k_outside_row_bounds() {
        crate::specify_test!("test_k_outside_row_bounds");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // Regression, found 2026-10-06 through the rstsr-faer-py conformance
        // suite (xp.triu(3x3, k=2) panicked): triu zeroes columns `j < i + k`
        // without clamping `i + k` to the row, indexing past the buffer
        // whenever the diagonal leaves the matrix.
        let a: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6], [7, 8, 9]], &device);
        // np.triu(a, k=2): only (0, 2) sits on or above the diagonal
        assert_equal(rt::triu((&a, 2)), rt::tensor_from_nested!([[0, 0, 3], [0, 0, 0], [0, 0, 0]], &device), None);
        // fully below the diagonal
        let zeros: Tensor<i32, _> = rt::zeros(([3, 3], &device));
        assert_equal(rt::triu((&a, 3)), &zeros, None);
        // np.tril(a, k=-2): only (2, 0) sits on or below the diagonal
        assert_equal(rt::tril((&a, -2)), rt::tensor_from_nested!([[0, 0, 0], [0, 0, 0], [7, 0, 0]], &device), None);
        assert_equal(rt::tril((&a, -3)), &zeros, None);

        // M > N (each row of triu at k = -1 starts past the single column)
        let b: Tensor<i32, _> = rt::tensor_from_nested!([[1], [2], [3], [4]], &device);
        assert_equal(rt::triu((&b, -1)), rt::tensor_from_nested!([[1], [2], [0], [0]], &device), None);
        // N > M
        let c: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2, 3, 4]], &device);
        assert_equal(rt::triu((&c, 1)), rt::tensor_from_nested!([[0, 2, 3, 4]], &device), None);
    }

    #[test]
    fn test_extreme_k() {
        crate::specify_test!("test_extreme_k");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // `k` at the isize bounds must not overflow the `i + k` arithmetic:
        // a huge positive k zeroes the whole matrix for triu (every column is
        // below the diagonal), a huge negative k keeps it
        let a: Tensor<i32, _> = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6], [7, 8, 9]], &device);
        let zeros: Tensor<i32, _> = rt::zeros(([3, 3], &device));
        assert_equal(rt::triu((&a, isize::MAX)), &zeros, None);
        assert_equal(rt::triu((&a, isize::MIN)), &a, None);
        assert_equal(rt::tril((&a, isize::MIN)), &zeros, None);
        assert_equal(rt::tril((&a, isize::MAX)), &a, None);
    }

    #[test]
    fn test_ndim1_error() {
        crate::specify_test!("test_ndim1_error");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // Regression (rstsr-faer-py review, 2026-10-06): rank-1 input used to
        // surface as a bare AxisError from `dim_split_at(-2)`.
        let a: Tensor<i32, _> = rt::tensor_from_nested!([1, 2, 3], &device);
        let err = rt::tril_f((&a, 0)).unwrap_err();
        assert!(format!("{err}").contains("at least 2 dimensions"));
        let err = rt::triu_f((&a, 0)).unwrap_err();
        assert!(format!("{err}").contains("at least 2 dimensions"));
    }
}
