// Most or all contents generated by AI (model glm-5.3-flash).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy's 0-d `np.array(value)` has no dedicated, cleanly transferable test in
// upstream suites; these are `custom_*` value tests for `rt::from_scalar`.

#[cfg(test)]
mod custom_from_scalar {
    use super::*;
    static FUNC: &str = "custom_from_scalar";

    #[test]
    fn test_basic() {
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.array(3.0) -> 0-d array; dtype follows the value or annotation
        let a = rt::from_scalar(3.0, &device);
        assert_eq!(a.shape().len(), 0);
        assert_eq!(a.to_scalar(), 3.0);
        assert!(a.device().same_device(&device));

        let b: Tensor<i32, _, _> = rt::from_scalar(7, &device);
        assert_eq!(b.shape().len(), 0);
        assert_eq!(b.to_scalar(), 7);

        let c = rt::from_scalar(2_i128, &device);
        assert_eq!(c.to_scalar(), 2);
    }

    #[test]
    fn test_bool_where_operand() {
        crate::specify_test!("test_bool_where_operand");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // motivating case: a bool constant as a tensor operand (bool scalars
        // are rejected by rstsr's scalar overloads; a 0-d bool tensor
        // broadcasts with the other operands instead)
        let cond = rt::tensor_from_nested!([true, false, true], &device);
        let x = rt::tensor_from_nested!([1, 2, 3], &device);
        let r = rt::r#where(&cond, &x, &rt::from_scalar(false, &device));
        assert_eq!(r.to_vec(), vec![1, 0, 3]);

        let t = rt::from_scalar(true, &device);
        let r = rt::r#where(&cond, &x, &t);
        assert_eq!(r.to_vec(), vec![1, 1, 3]);
    }
}
