//! Reduction functions: aggregate a tensor into a scalar or along axes.
//!
//! Families (`sum`, `prod`, `mean`, `var`, `std`, `min`, `max`, `argmin`,
//! `argmax`, `nanargmin`, `nanargmax`, `count_nonzero`, `all`, `any`,
//! `l2_norm`) are generated by the local `trait_reduction!` macro, and
//! [`allclose`] is hand-written. Each family exposes:
//!
//! - `<fam>(tensor)`: reduce **all** elements to a scalar;
//! - `<fam>_all(tensor)`: the same, explicit form;
//! - `<fam>_axes(tensor, axes)`: reduce along the given axes (negative values count from the back;
//!   `None` reduces everything into a 0-D tensor);
//! - `<fam>_with_args(tensor, args)`: the same, with [`ReduceArgs`] grouping `axes` and `keepdims`
//!   (reduced axes kept as size-1 dimensions); var/std take [`VarArgs`], which adds array-api
//!   `correction` (NumPy `ddof`) on top;
//! - `<fam>_with_dtype::<TOut>(tensor, args)` (sum/prod/mean/var/std): reduce with an explicit
//!   output dtype; elements are cast inside the fold, so accumulation happens in `TOut`
//!   (anti-overflow semantics of array-api's `dtype=`), with no cast copy of the input;
//! - fallible `_f` versions of all of the above.
//!
//! The arg* families (`argmin`, `argmax`, and their `unraveled_` variants from
//! the `trait_reduction_arg!` macro) return element indices instead of values:
//! the all-element forms return the flat (linear) index, and the `_axes`
//! forms return index tensors.
//!
//! <div class="warning">
//!
//! **Row/Column Major Notice**
//!
//! This function behaves differently on default orders ([`RowMajor`] and [`ColMajor`]) of device.
//!
//! </div>
//!
//! The note above applies to the arg* families and `_axes` result layouts
//! only: value aggregations (`sum`, `mean`, `max`, ...) produce the same
//! values under both orders, and `_axes` outputs keep the input's axis
//! arrangement ([`TensorIterOrder::K`]) regardless of the device default
//! order. The arg* functions are order-independent: ties resolve to the first
//! occurrence in row-major order, and the all-element forms return a
//! row-major flat index even on a [`ColMajor`] device. The
//! `nanargmin`/`nanargmax` families follow NumPy's `nanarg*`: NaN elements
//! are skipped wherever they appear, and an all-NaN input raises
//! `InvalidValue` ("All-NaN slice encountered"); use these for inputs that
//! may contain NaN. See [`order_semantics`](crate::order_semantics).
//!
//! # Examples
//!
//! ```rust
//! # use rstsr::prelude::*;
//! # let mut device = DeviceCpu::default();
//! # device.set_default_order(RowMajor);
//! let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
//!
//! // reduce everything to a scalar
//! println!("{}", rt::sum(&a));
//! // 21
//! println!("{}", rt::sum_axes(&a, 0));
//! // [ 5 7 9]
//! println!("{}", rt::count_nonzero_axes(&a, 0));
//! // [ 2 2 2]
//! # assert_eq!(rt::sum(&a), 21);
//! # assert_eq!(format!("{}", rt::sum_axes(&a, 0)), "[ 5 7 9]");
//! ```
//!
//! The arg* families return indices:
//!
//! ```rust
//! # use rstsr::prelude::*;
//! # let mut device = DeviceCpu::default();
//! # device.set_default_order(RowMajor);
//! let a = rt::tensor_from_nested!([[1.0, 5.0, 3.0], [4.0, 5.0, 2.0]], &device);
//! println!("{}", rt::argmax(&a));
//! // 1
//! println!("{}", rt::argmax_axes(&a, 0));
//! // [ 1 0 0]
//! # assert_eq!(rt::argmax(&a), 1);
//! # assert_eq!(format!("{}", rt::argmax_axes(&a, 0)), "[ 1 0 0]");
//! ```
//!
//! `*_with_args` and `*_with_dtype`:
//!
//! ```rust
//! # use rstsr::prelude::*;
//! # let mut device = DeviceCpu::default();
//! # device.set_default_order(RowMajor);
//! let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
//! // keep reduced axes as size-1 dimensions
//! println!("{}", rt::sum_with_args(&a, ([0], true)));
//! // [[ 5 7 9]]
//! // explicit output dtype: fold in f64
//! println!("{}", a.sum_with_dtype::<f64>(1));
//! // [ 6 15]
//! # assert_eq!(format!("{}", rt::sum_with_args(&a, ([0], true))), "[[ 5 7 9]]");
//! # assert_eq!(a.sum_with_dtype::<f64>(1)[[1]], 15.0);
//! ```

use crate::prelude_dev::*;
use num::{Float, FromPrimitive};

/* #region reduce args */

/// Reduction arguments: `axes` and `keepdims`.
///
/// Default (`ReduceArgs::default()` or `()`): reduce **all** axes, dropping
/// them from the result layout.
///
/// # Parameters
///
/// - `axes`: axes to reduce; `AxesIndex::None` reduces everything. Negative values count from the
///   back. Unlike NumPy's `axis` keyword the field is spelled `axes` (plural), consistent with
///   RSTSR's existing [`AxesIndex`] conventions.
/// - `keepdims`: if `true`, reduced axes are kept in the result as size-1 dimensions instead of
///   being dropped.
///
/// Note: `()` (and [`ReduceArgs::default`]) means reduce **all** axes. This differs from the bare
/// `AxesIndex::from(())` (an empty axes list, i.e. reduce nothing) that the `_axes` functions
/// accept; here `()` always reads as the default argument set.
///
/// # Notes of API accordance
///
/// - array-api: `sum(x, axis=..., keepdims=...)` spells the axis argument `axis` and only accepts
///   this in keyword form; RSTSR groups both into this struct.
///
/// # Examples
///
/// ```rust
/// # use rstsr::prelude::*;
/// # let mut device = DeviceCpu::default();
/// # device.set_default_order(RowMajor);
/// let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
/// // reduce all axes, keep dimensions: shape (1, 1), value 21
/// let s = rt::sum_with_args(&a, true);
/// assert_eq!(s.shape().to_vec(), vec![1, 1]);
/// assert_eq!(s.to_scalar(), 21);
/// // reduce axis 0 only, keepdims: shape (1, 3), values [5 7 9]
/// let s = rt::sum_with_args(&a, ([0], true));
/// assert_eq!(s.shape().to_vec(), vec![1, 3]);
/// assert_eq!(s[[0, 2]], 9);
/// ```
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReduceArgs {
    pub axes: AxesIndex<isize>,
    pub keepdims: bool,
}

impl Default for ReduceArgs {
    fn default() -> Self {
        ReduceArgs { axes: AxesIndex::None, keepdims: false }
    }
}

impl From<()> for ReduceArgs {
    fn from(_: ()) -> Self {
        Self::default()
    }
}

/// `keepdims` shorthand: `sum_with_args(&a, true)` reduces all axes keeping dims.
impl From<bool> for ReduceArgs {
    fn from(keepdims: bool) -> Self {
        Self { axes: AxesIndex::None, keepdims }
    }
}

impl From<AxesIndex<isize>> for ReduceArgs {
    fn from(axes: AxesIndex<isize>) -> Self {
        Self { axes, keepdims: false }
    }
}

impl From<Option<AxesIndex<isize>>> for ReduceArgs {
    fn from(axes: Option<AxesIndex<isize>>) -> Self {
        Self::from(axes.unwrap_or(AxesIndex::None))
    }
}

impl From<Vec<isize>> for ReduceArgs {
    fn from(axes: Vec<isize>) -> Self {
        Self::from(AxesIndex::Vec(axes))
    }
}

impl<const N: usize> From<[isize; N]> for ReduceArgs {
    fn from(axes: [isize; N]) -> Self {
        Self::from(AxesIndex::Vec(axes.to_vec()))
    }
}

/// `as isize` (not TryFrom): `From` is infallible by convention, so an
/// out-of-range value must not panic here. Widened/negative values are
/// rejected later by the axes validation (`normalize_axes_index`), which
/// surfaces as `Err` for the `_f` entry points.
macro_rules! impl_reduce_args_from_int {
    ($Args: ident, $($t: ty),* $(,)?) => {$(
        impl From<$t> for $Args {
            fn from(axis: $t) -> Self {
                Self::from(AxesIndex::Val(axis as isize))
            }
        }

        impl From<($t, bool)> for $Args {
            fn from((axis, keepdims): ($t, bool)) -> Self {
                Self::from((AxesIndex::Val(axis as isize), keepdims))
            }
        }
    )*};
}

// `isize` converts directly (no TryFrom needed; the std blanket TryFrom has an
// `Infallible` error type that does not carry rstsr backtrace info)
impl From<isize> for ReduceArgs {
    fn from(axis: isize) -> Self {
        Self::from(AxesIndex::Val(axis))
    }
}

impl From<(isize, bool)> for ReduceArgs {
    fn from((axis, keepdims): (isize, bool)) -> Self {
        Self { axes: AxesIndex::Val(axis), keepdims }
    }
}

impl From<isize> for VarArgs {
    fn from(axis: isize) -> Self {
        Self::from(AxesIndex::Val(axis))
    }
}

impl From<(isize, bool)> for VarArgs {
    fn from((axis, keepdims): (isize, bool)) -> Self {
        Self { axes: AxesIndex::Val(axis), keepdims, correction: None }
    }
}

impl_reduce_args_from_int!(ReduceArgs, i32, i64, usize);
impl_reduce_args_from_int!(VarArgs, i32, i64, usize);

impl From<(AxesIndex<isize>, bool)> for ReduceArgs {
    fn from((axes, keepdims): (AxesIndex<isize>, bool)) -> Self {
        Self { axes, keepdims }
    }
}

impl<const N: usize> From<([isize; N], bool)> for ReduceArgs {
    fn from((axes, keepdims): ([isize; N], bool)) -> Self {
        Self { axes: AxesIndex::Vec(axes.to_vec()), keepdims }
    }
}

impl From<(Vec<isize>, bool)> for ReduceArgs {
    fn from((axes, keepdims): (Vec<isize>, bool)) -> Self {
        Self { axes: AxesIndex::Vec(axes), keepdims }
    }
}

/// Container overloads for common integer element types (parity with the
/// `AxesIndex` conversions accepted by the `_axes` functions). `as isize`
/// keeps `From` infallible; invalid values are rejected by the later axes
/// validation.
macro_rules! impl_reduce_args_from_int_container {
    ($Args: ident, $($t: ty),* $(,)?) => {$(
        impl From<Vec<$t>> for $Args {
            fn from(axes: Vec<$t>) -> Self {
                Self::from(AxesIndex::Vec(axes.into_iter().map(|v| v as isize).collect_vec()))
            }
        }

        impl<const N: usize> From<[$t; N]> for $Args {
            fn from(axes: [$t; N]) -> Self {
                Self::from(AxesIndex::Vec(axes.into_iter().map(|v| v as isize).collect_vec()))
            }
        }

        impl From<(Vec<$t>, bool)> for $Args {
            fn from((axes, keepdims): (Vec<$t>, bool)) -> Self {
                Self::from((AxesIndex::Vec(axes.into_iter().map(|v| v as isize).collect_vec()), keepdims))
            }
        }

        impl<const N: usize> From<([$t; N], bool)> for $Args {
            fn from((axes, keepdims): ([$t; N], bool)) -> Self {
                Self::from((AxesIndex::Vec(axes.into_iter().map(|v| v as isize).collect_vec()), keepdims))
            }
        }
    )*};
}

impl_reduce_args_from_int_container!(ReduceArgs, i32, i64, u32, u64, usize);
impl_reduce_args_from_int_container!(VarArgs, i32, i64, u32, u64, usize);

impl From<bool> for VarArgs {
    fn from(keepdims: bool) -> Self {
        Self { axes: AxesIndex::None, keepdims, correction: None }
    }
}

impl From<Option<AxesIndex<isize>>> for VarArgs {
    fn from(axes: Option<AxesIndex<isize>>) -> Self {
        Self::from(axes.unwrap_or(AxesIndex::None))
    }
}

impl From<(Vec<isize>, bool)> for VarArgs {
    fn from((axes, keepdims): (Vec<isize>, bool)) -> Self {
        Self { axes: AxesIndex::Vec(axes), keepdims, correction: None }
    }
}

/* #endregion */

/* #region var args */

/// Variance/std reduction arguments: [`ReduceArgs`] fields plus `correction`.
///
/// `correction` follows array-api `std`/`var`: the divisor is `M -
/// correction` (NumPy's `ddof`), default `0` (population variance). If
/// `M - correction <= 0` the result is NaN.
#[derive(Debug, Clone, PartialEq)]
pub struct VarArgs {
    pub axes: AxesIndex<isize>,
    pub keepdims: bool,
    /// `f64` (not generic over the tensor's float type): corrections are
    /// counts (NumPy `ddof`), exactly representable in `f64`, and the
    /// rescale factor is computed once in `f64` then converted to the output
    /// dtype - strictly more accurate than accumulating in a narrower float.
    pub correction: Option<f64>,
}

impl Default for VarArgs {
    fn default() -> Self {
        VarArgs { axes: AxesIndex::None, keepdims: false, correction: None }
    }
}

impl From<()> for VarArgs {
    fn from(_: ()) -> Self {
        Self::default()
    }
}

impl From<AxesIndex<isize>> for VarArgs {
    fn from(axes: AxesIndex<isize>) -> Self {
        Self { axes, keepdims: false, correction: None }
    }
}

impl From<Vec<isize>> for VarArgs {
    fn from(axes: Vec<isize>) -> Self {
        Self::from(AxesIndex::Vec(axes))
    }
}

impl<const N: usize> From<[isize; N]> for VarArgs {
    fn from(axes: [isize; N]) -> Self {
        Self::from(AxesIndex::Vec(axes.to_vec()))
    }
}

impl From<(AxesIndex<isize>, bool)> for VarArgs {
    fn from((axes, keepdims): (AxesIndex<isize>, bool)) -> Self {
        Self { axes, keepdims, correction: None }
    }
}

impl<const N: usize> From<([isize; N], bool)> for VarArgs {
    fn from((axes, keepdims): ([isize; N], bool)) -> Self {
        Self { axes: AxesIndex::Vec(axes.to_vec()), keepdims, correction: None }
    }
}

/* #endregion */

/* #region keepdims layout helpers */

/// Layout for a whole-reduction result: 0-D, or `(1,)*ndim` if keepdims.
fn reduce_layout_whole(ndim: usize, keepdims: bool) -> Result<Layout<IxD>> {
    let mut layout = Layout::new(vec![], vec![], 0)?;
    if keepdims {
        for axis in 0..ndim {
            layout = layout.dim_insert(axis as isize)?;
        }
    }
    Ok(layout)
}

/// Reinsert size-1 dims at the (normalized, sorted) reduced axes if keepdims;
/// otherwise return the layout unchanged.
///
/// Ascending insertion: after the first `i` inserts the layout holds the
/// remaining axes plus `i` size-1 dims, and the next reduced axis `a_i` is
/// always a valid insert position (`a_i <= ndim_original - k + i`).
fn reduce_layout_keepdims(
    layout: Layout<IxD>,
    axes: &AxesIndex<isize>,
    ndim: usize,
    keepdims: bool,
) -> Result<Layout<IxD>> {
    if !keepdims {
        return Ok(layout);
    }
    let axes_norm = normalize_axes_index(axes.clone(), ndim, false, true)?;
    let mut layout = layout;
    for &axis in axes_norm.iter() {
        layout = layout.dim_insert(axis)?;
    }
    Ok(layout)
}

/* #endregion */

macro_rules! trait_reduction {
    ([$($with_args: ident)?] $OpReduceAPI: ident, $fn: ident, $fn_f: ident, $fn_axes: ident, $fn_axes_f: ident, $fn_all: ident, $fn_all_f: ident, $fn_with_args: ident, $fn_with_args_f: ident) => {
        pub fn $fn_all_f<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> Result<B::TOut>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            let tensor = tensor.view();
            tensor.device().$fn_all(tensor.raw(), tensor.layout())
        }

        pub fn $fn_axes_f<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
        ) -> Result<Tensor<B::TOut, B, IxD>>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceCreationAnyAPI<B::TOut>,
        {
            let axes = axes.try_into().map_err(Into::into)?;
            let tensor = tensor.view();

            match axes {
                AxesIndex::None => {
                    let sum = tensor.device().$fn_all(tensor.raw(), tensor.layout())?;
                    let storage = tensor.device().outof_cpu_vec(vec![sum])?;
                    let layout = Layout::new(vec![], vec![], 0)?;
                    Tensor::new_f(storage, layout)
                },
                _ => {
                    let (storage, layout) = tensor.device().$fn_axes(tensor.raw(), tensor.layout(), axes.as_ref())?;
                    Tensor::new_f(storage, layout)
                },
            }
        }

        pub fn $fn_all<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> B::TOut
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all_f(tensor).rstsr_unwrap()
        }

        pub fn $fn_axes<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
        ) -> Tensor<B::TOut, B, IxD>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceCreationAnyAPI<B::TOut>,
        {
            $fn_axes_f(tensor, axes).rstsr_unwrap()
        }

        pub fn $fn_f<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> Result<B::TOut>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all_f(tensor)
        }

        pub fn $fn<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> B::TOut
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all(tensor)
        }

        trait_reduction_with_args!([$($with_args)?] $OpReduceAPI, $fn_with_args_f, $fn_with_args, $fn_axes, $fn_all);

        impl<R, T, B, D> TensorAny<R, T, B, D>
        where
            R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            pub fn $fn_all_f(&self) -> Result<B::TOut> {
                $fn_all_f(self)
            }

            pub fn $fn_all(&self) -> B::TOut {
                $fn_all(self)
            }

            pub fn $fn_axes_f(
                &self,
                axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
            ) -> Result<Tensor<B::TOut, B, IxD>>
            where
                B: DeviceCreationAnyAPI<B::TOut>,
            {
                $fn_axes_f(self, axes)
            }

            pub fn $fn_axes(&self, axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>) -> Tensor<B::TOut, B, IxD>
            where
                B: DeviceCreationAnyAPI<B::TOut>,
            {
                $fn_axes(self, axes)
            }

            pub fn $fn_f(&self) -> Result<B::TOut> {
                $fn_f(self)
            }

            pub fn $fn(&self) -> B::TOut {
                $fn(self)
            }

            trait_reduction_with_args_methods!([$($with_args)?] $fn_with_args_f, $fn_with_args);
        }
    };
}

/// Free functions and methods `<fam>_with_args[_f]` for reduction families
/// taking [`ReduceArgs`] (axes + keepdims). Emitted only for families marked
/// `[with_args]` in [`trait_reduction!`]; var/std use hand-written
/// [`VarArgs`] versions (correction).
macro_rules! trait_reduction_with_args {
    ([$_with_args: ident] $OpReduceAPI: ident, $fn_with_args_f: ident, $fn_with_args: ident, $fn_axes: ident, $fn_all: ident) => {
        pub fn $fn_with_args_f<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Result<Tensor<B::TOut, B, IxD>>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceCreationAnyAPI<B::TOut>,
        {
            let ReduceArgs { axes, keepdims } = args.into();
            let tensor = tensor.view();

            match axes {
                AxesIndex::None => {
                    let val = tensor.device().$fn_all(tensor.raw(), tensor.layout())?;
                    let storage = tensor.device().outof_cpu_vec(vec![val])?;
                    let layout = reduce_layout_whole(tensor.layout().ndim(), keepdims)?;
                    Tensor::new_f(storage, layout)
                },
                axes => {
                    let (storage, layout) = tensor.device().$fn_axes(tensor.raw(), tensor.layout(), axes.as_ref())?;
                    let layout = reduce_layout_keepdims(layout, &axes, tensor.layout().ndim(), keepdims)?;
                    Tensor::new_f(storage, layout)
                },
            }
        }

        pub fn $fn_with_args<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Tensor<B::TOut, B, IxD>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceCreationAnyAPI<B::TOut>,
        {
            $fn_with_args_f(tensor, args).rstsr_unwrap()
        }
    };
    ([] $($rest: tt)*) => {};
}

macro_rules! trait_reduction_with_args_methods {
    ([$_with_args: ident] $fn_with_args_f: ident, $fn_with_args: ident) => {
        pub fn $fn_with_args_f(&self, args: impl Into<ReduceArgs>) -> Result<Tensor<B::TOut, B, IxD>>
        where
            B: DeviceCreationAnyAPI<B::TOut>,
        {
            $fn_with_args_f(self, args)
        }

        pub fn $fn_with_args(&self, args: impl Into<ReduceArgs>) -> Tensor<B::TOut, B, IxD>
        where
            B: DeviceCreationAnyAPI<B::TOut>,
        {
            $fn_with_args(self, args)
        }
    };
    ([] $($rest: tt)*) => {};
}

#[rustfmt::skip]
mod impl_trait_reduction {
    use super::*;
    trait_reduction!([with_args] OpSumAPI, sum, sum_f, sum_axes, sum_axes_f, sum_all, sum_all_f, sum_with_args, sum_with_args_f);
    trait_reduction!([with_args] OpMinAPI, min, min_f, min_axes, min_axes_f, min_all, min_all_f, min_with_args, min_with_args_f);
    trait_reduction!([with_args] OpMaxAPI, max, max_f, max_axes, max_axes_f, max_all, max_all_f, max_with_args, max_with_args_f);
    trait_reduction!([with_args] OpProdAPI, prod, prod_f, prod_axes, prod_axes_f, prod_all, prod_all_f, prod_with_args, prod_with_args_f);
    trait_reduction!([with_args] OpMeanAPI, mean, mean_f, mean_axes, mean_axes_f, mean_all, mean_all_f, mean_with_args, mean_with_args_f);
    trait_reduction!([] OpVarAPI, var, var_f, var_axes, var_axes_f, var_all, var_all_f, var_with_args, var_with_args_f);
    trait_reduction!([] OpStdAPI, std, std_f, std_axes, std_axes_f, std_all, std_all_f, std_with_args, std_with_args_f);
    trait_reduction!([with_args] OpL2NormAPI, l2_norm, l2_norm_f, l2_norm_axes, l2_norm_axes_f, l2_norm_all, l2_norm_all_f, l2_norm_with_args, l2_norm_with_args_f);
    trait_reduction!([with_args] OpArgMinAPI, argmin, argmin_f, argmin_axes, argmin_axes_f, argmin_all, argmin_all_f, argmin_with_args, argmin_with_args_f);
    trait_reduction!([with_args] OpArgMaxAPI, argmax, argmax_f, argmax_axes, argmax_axes_f, argmax_all, argmax_all_f, argmax_with_args, argmax_with_args_f);
    trait_reduction!([with_args] OpNanArgMinAPI, nanargmin, nanargmin_f, nanargmin_axes, nanargmin_axes_f, nanargmin_all, nanargmin_all_f, nanargmin_with_args, nanargmin_with_args_f);
    trait_reduction!([with_args] OpNanArgMaxAPI, nanargmax, nanargmax_f, nanargmax_axes, nanargmax_axes_f, nanargmax_all, nanargmax_all_f, nanargmax_with_args, nanargmax_with_args_f);
    trait_reduction!([with_args] OpAllAPI, all, all_f, all_axes, all_axes_f, all_all, all_all_f, all_with_args, all_with_args_f);
    trait_reduction!([with_args] OpAnyAPI, any, any_f, any_axes, any_axes_f, any_all, any_all_f, any_with_args, any_with_args_f);
    trait_reduction!([with_args] OpCountNonZeroAPI, count_nonzero, count_nonzero_f, count_nonzero_axes, count_nonzero_axes_f, count_nonzero_all, count_nonzero_all_f, count_nonzero_with_args, count_nonzero_with_args_f);
}
pub use impl_trait_reduction::*;

/* #region with dtype */

/// Reduction families with an explicit output dtype: `<fam>_with_dtype::<TOut>`.
///
/// The fold runs in `TOut` (elements are cast per element inside the kernel's
/// accumulate closure), so accumulation happens in the requested dtype
/// (anti-overflow semantics of array-api's `dtype=` keyword) without
/// materializing a cast copy of the input.
/// Dispatch + output-layout plumbing shared by the `*_with_args` /
/// `*_with_dtype` entry points (a macro so each call site expands inline:
/// closure-based helpers lose the outer generics' associated types).
///
/// Requires `tensor` in scope (a viewed `TensorAny`), plus device methods
/// `$all` / `$axes`; expands to a `Result<Tensor<..>>`.
macro_rules! reduce_dispatch_output {
    ($tensor: ident, $all: ident, $axes: ident, $axes_val: expr, $keepdims: expr) => {{
        let axes = $axes_val;
        let keepdims = $keepdims;
        let layout: Layout<IxD> = $tensor.layout().to_dim()?;
        match axes {
            AxesIndex::None => {
                let val = $tensor.device().$all($tensor.raw(), $tensor.layout())?;
                let storage = $tensor.device().outof_cpu_vec(vec![val])?;
                let out_layout = reduce_layout_whole(layout.ndim(), keepdims)?;
                Tensor::new_f(storage, out_layout)
            },
            axes => {
                let (storage, out_layout) = $tensor.device().$axes($tensor.raw(), $tensor.layout(), axes.as_ref())?;
                let out_layout = reduce_layout_keepdims(out_layout, &axes, layout.ndim(), keepdims)?;
                Tensor::new_f(storage, out_layout)
            },
        }
    }};
    ($tensor: ident, @axes_kernel $axes: ident, $axes_val: expr, $keepdims: expr) => {{
        let axes = $axes_val;
        let keepdims = $keepdims;
        let layout: Layout<IxD> = $tensor.layout().to_dim()?;
        let axes = match axes {
            AxesIndex::None => AxesIndex::Vec((0..layout.ndim() as isize).collect_vec()),
            axes => axes,
        };
        let (storage, out_layout) = $tensor.device().$axes($tensor.raw(), $tensor.layout(), axes.as_ref())?;
        let out_layout = reduce_layout_keepdims(out_layout, &axes, layout.ndim(), keepdims)?;
        Tensor::new_f(storage, out_layout)
    }};
}

/// Dispatch + output-layout plumbing shared by the `*_with_args` /
/// `*_with_dtype` entry points: `AxesIndex::None` routes to the whole-array
/// kernel (which, unlike the axes kernel, supports broadcast and zero-size
/// inputs), other axes to the axes kernel; keepdims rebuilds the output
/// layout afterwards.
macro_rules! trait_reduction_dtype {
    ($OpReduceDtypeAPI: ident, $fn_with_dtype: ident, $fn_with_dtype_f: ident, $fn_axes_dtype: ident) => {
        pub fn $fn_with_dtype_f<T, TOut, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Result<Tensor<TOut, B, IxD>>
        where
            D: DimAPI,
            B: $OpReduceDtypeAPI<T, TOut, D> + DeviceCreationAnyAPI<TOut>,
        {
            let ReduceArgs { axes, keepdims } = args.into();
            let tensor = tensor.view();

            reduce_dispatch_output!(tensor, @axes_kernel $fn_axes_dtype, axes, keepdims)
        }

        pub fn $fn_with_dtype<T, TOut, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Tensor<TOut, B, IxD>
        where
            D: DimAPI,
            B: $OpReduceDtypeAPI<T, TOut, D> + DeviceCreationAnyAPI<TOut>,
        {
            $fn_with_dtype_f(tensor, args).rstsr_unwrap()
        }

        impl<R, T, B, D> TensorAny<R, T, B, D>
        where
            R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
            D: DimAPI,
            B: DeviceAPI<T>,
        {
            pub fn $fn_with_dtype_f<TOut>(&self, args: impl Into<ReduceArgs>) -> Result<Tensor<TOut, B, IxD>>
            where
                B: $OpReduceDtypeAPI<T, TOut, D> + DeviceCreationAnyAPI<TOut>,
            {
                $fn_with_dtype_f(self, args)
            }

            pub fn $fn_with_dtype<TOut>(&self, args: impl Into<ReduceArgs>) -> Tensor<TOut, B, IxD>
            where
                B: $OpReduceDtypeAPI<T, TOut, D> + DeviceCreationAnyAPI<TOut>,
            {
                $fn_with_dtype(self, args)
            }
        }
    };
}

/// var/std `*_with_dtype`: same dispatch as [`trait_reduction_dtype`], but
/// consuming [`VarArgs`] and applying array-api `correction` to the finished
/// result (output-sized rescale; no input-sized intermediate).
///
/// The fold accumulates `(sum, sum-of-squares)` in `TOut` (one-pass formula, same as NumPy). With
/// a narrower accumulator than the input (e.g. `f64` input folded in `f32`) catastrophic
/// cancellation can yield a negative variance / NaN std; prefer an equal-width or wider `TOut`
/// when precision matters.
macro_rules! trait_reduction_dtype_varstd {
    ($OpReduceDtypeAPI: ident, $fn_with_dtype: ident, $fn_with_dtype_f: ident, $fn_axes_dtype: ident, $is_std: literal) => {
        pub fn $fn_with_dtype_f<T, TOut, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<VarArgs>,
        ) -> Result<Tensor<TOut, B, IxD>>
        where
            D: DimAPI,
            TOut: Float + FromPrimitive + Send + Sync + 'static,
            B: $OpReduceDtypeAPI<T, TOut, D>
                + DeviceCreationAnyAPI<TOut>
                + DeviceRawAPI<MaybeUninit<TOut>>
                + for<'f> Op_MutA_RefB_API<
                    TOut,
                    TOut,
                    IxD,
                    dyn Fn(&mut MaybeUninit<TOut>, &TOut) + Send + Sync + 'f,
                >,
        {
            let VarArgs {
                axes,
                keepdims,
                correction,
            } = args.into();
            let tensor = tensor.view();

            let result = reduce_dispatch_output!(tensor, @axes_kernel $fn_axes_dtype, axes.clone(), keepdims)?;

            match correction {
                None => Ok(result),
                Some(correction) => {
                    let size = reduced_axes_size(&axes, tensor.layout())?;
                    let factor = <TOut as FromPrimitive>::from_f64(var_correction_factor(size, correction, $is_std)).unwrap();
                    Ok(result.mapv(move |x| x * factor))
                },
            }
        }

        pub fn $fn_with_dtype<T, TOut, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<VarArgs>,
        ) -> Tensor<TOut, B, IxD>
        where
            D: DimAPI,
            TOut: Float + FromPrimitive + Send + Sync + 'static,
            B: $OpReduceDtypeAPI<T, TOut, D>
                + DeviceCreationAnyAPI<TOut>
                + DeviceRawAPI<MaybeUninit<TOut>>
                + for<'f> Op_MutA_RefB_API<
                    TOut,
                    TOut,
                    IxD,
                    dyn Fn(&mut MaybeUninit<TOut>, &TOut) + Send + Sync + 'f,
                >,
        {
            $fn_with_dtype_f(tensor, args).rstsr_unwrap()
        }

        impl<R, T, B, D> TensorAny<R, T, B, D>
        where
            R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
            D: DimAPI,
            B: DeviceAPI<T>,
        {
            pub fn $fn_with_dtype_f<TOut>(&self, args: impl Into<VarArgs>) -> Result<Tensor<TOut, B, IxD>>
            where
                TOut: Float + FromPrimitive + Send + Sync + 'static,
                B: $OpReduceDtypeAPI<T, TOut, D>
                    + DeviceCreationAnyAPI<TOut>
                    + DeviceRawAPI<MaybeUninit<TOut>>
                    + for<'f> Op_MutA_RefB_API<
                        TOut,
                        TOut,
                        IxD,
                        dyn Fn(&mut MaybeUninit<TOut>, &TOut) + Send + Sync + 'f,
                    >,
            {
                $fn_with_dtype_f(self, args)
            }

            pub fn $fn_with_dtype<TOut>(&self, args: impl Into<VarArgs>) -> Tensor<TOut, B, IxD>
            where
                TOut: Float + FromPrimitive + Send + Sync + 'static,
                B: $OpReduceDtypeAPI<T, TOut, D>
                    + DeviceCreationAnyAPI<TOut>
                    + DeviceRawAPI<MaybeUninit<TOut>>
                    + for<'f> Op_MutA_RefB_API<
                        TOut,
                        TOut,
                        IxD,
                        dyn Fn(&mut MaybeUninit<TOut>, &TOut) + Send + Sync + 'f,
                    >,
            {
                $fn_with_dtype(self, args)
            }
        }
    };
}

#[rustfmt::skip]
mod impl_trait_reduction_dtype {
    use super::*;
    trait_reduction_dtype!(OpSumDtypeAPI, sum_with_dtype, sum_with_dtype_f, sum_axes_dtype);
    trait_reduction_dtype!(OpProdDtypeAPI, prod_with_dtype, prod_with_dtype_f, prod_axes_dtype);
    trait_reduction_dtype!(OpMeanDtypeAPI, mean_with_dtype, mean_with_dtype_f, mean_axes_dtype);
    trait_reduction_dtype_varstd!(OpVarDtypeAPI, var_with_dtype, var_with_dtype_f, var_axes_dtype, false);
    trait_reduction_dtype_varstd!(OpStdDtypeAPI, std_with_dtype, std_with_dtype_f, std_axes_dtype, true);
}
pub use impl_trait_reduction_dtype::*;

/* #endregion */

/* #region var/std with args (correction) */

/// Rescale factor from population variance to corrected variance
/// (NumPy `ddof` / array-api `correction`): `M / (M - correction)`, `sqrt`'ed
/// for std. NaN when `M - correction <= 0` (array-api contract).
fn var_correction_factor(size: usize, correction: f64, is_std: bool) -> f64 {
    let m = size as f64;
    let d = m - correction;
    if d <= 0.0 {
        f64::NAN
    } else {
        let factor = m / d;
        if is_std {
            factor.sqrt()
        } else {
            factor
        }
    }
}

/// Variance with [`VarArgs`] (axes, keepdims, correction).
///
/// The correction rescales the population variance by `M / (M - correction)`
/// on the (output-sized) result; no input-sized intermediate is created.
pub fn var_with_args_f<T, B, D>(
    tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
    args: impl Into<VarArgs>,
) -> Result<Tensor<B::TOut, B, IxD>>
where
    D: DimAPI,
    B: OpVarAPI<T, D>
        + DeviceCreationAnyAPI<B::TOut>
        + Op_MutA_RefB_API<
            B::TOut,
            B::TOut,
            IxD,
            dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
        >,
    B::TOut: Float + FromPrimitive + Send + Sync + 'static,
{
    let VarArgs { axes, keepdims, correction } = args.into();
    let tensor = tensor.view();

    let result: Tensor<B::TOut, B, IxD> = reduce_dispatch_output!(tensor, var_all, var_axes, axes.clone(), keepdims)?;

    if let Some(correction) = correction {
        let size = reduced_axes_size(&axes, tensor.layout())?;
        let factor = B::TOut::from_f64(var_correction_factor(size, correction, false)).unwrap();
        return Ok(result.mapv(move |x| x * factor));
    }
    Ok(result)
}

/// Variance with [`VarArgs`]; panicking version of [`var_with_args_f`].
pub fn var_with_args<T, B, D>(
    tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
    args: impl Into<VarArgs>,
) -> Tensor<B::TOut, B, IxD>
where
    D: DimAPI,
    B: OpVarAPI<T, D>
        + DeviceCreationAnyAPI<B::TOut>
        + Op_MutA_RefB_API<
            B::TOut,
            B::TOut,
            IxD,
            dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
        >,
    B::TOut: Float + FromPrimitive + Send + Sync + 'static,
{
    var_with_args_f(tensor, args).rstsr_unwrap()
}

/// Standard deviation with [`VarArgs`] (axes, keepdims, correction).
pub fn std_with_args_f<T, B, D>(
    tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
    args: impl Into<VarArgs>,
) -> Result<Tensor<B::TOut, B, IxD>>
where
    D: DimAPI,
    B: OpStdAPI<T, D>
        + DeviceCreationAnyAPI<B::TOut>
        + Op_MutA_RefB_API<
            B::TOut,
            B::TOut,
            IxD,
            dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
        >,
    B::TOut: Float + FromPrimitive + Send + Sync + 'static,
{
    let VarArgs { axes, keepdims, correction } = args.into();
    let tensor = tensor.view();

    let result: Tensor<B::TOut, B, IxD> = reduce_dispatch_output!(tensor, std_all, std_axes, axes.clone(), keepdims)?;

    if let Some(correction) = correction {
        let size = reduced_axes_size(&axes, tensor.layout())?;
        let factor = B::TOut::from_f64(var_correction_factor(size, correction, true)).unwrap();
        return Ok(result.mapv(move |x| x * factor));
    }
    Ok(result)
}

/// Standard deviation with [`VarArgs`]; panicking version of [`std_with_args_f`].
pub fn std_with_args<T, B, D>(
    tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
    args: impl Into<VarArgs>,
) -> Tensor<B::TOut, B, IxD>
where
    D: DimAPI,
    B: OpStdAPI<T, D>
        + DeviceCreationAnyAPI<B::TOut>
        + Op_MutA_RefB_API<
            B::TOut,
            B::TOut,
            IxD,
            dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
        >,
    B::TOut: Float + FromPrimitive + Send + Sync + 'static,
{
    std_with_args_f(tensor, args).rstsr_unwrap()
}

/// Number of elements each output cell aggregates: the product of the reduced
/// axes' sizes (all axes when `AxesIndex::None`).
fn reduced_axes_size<D: DimAPI>(axes: &AxesIndex<isize>, layout: &Layout<D>) -> Result<usize> {
    match axes {
        AxesIndex::None => Ok(layout.size()),
        axes => {
            let axes_norm = normalize_axes_index(axes.clone(), layout.ndim(), false, true)?;
            Ok(axes_norm.iter().map(|&axis| layout.shape()[axis as usize]).product::<usize>())
        },
    }
}

impl<R, T, B, D> TensorAny<R, T, B, D>
where
    R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
    D: DimAPI,
    B: OpVarAPI<T, D>,
{
    pub fn var_with_args_f(&self, args: impl Into<VarArgs>) -> Result<Tensor<B::TOut, B, IxD>>
    where
        B: DeviceCreationAnyAPI<B::TOut>
            + Op_MutA_RefB_API<
                B::TOut,
                B::TOut,
                IxD,
                dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
            >,
        B::TOut: Float + FromPrimitive + Send + Sync + 'static,
    {
        var_with_args_f(self, args)
    }

    pub fn var_with_args(&self, args: impl Into<VarArgs>) -> Tensor<B::TOut, B, IxD>
    where
        B: DeviceCreationAnyAPI<B::TOut>
            + Op_MutA_RefB_API<
                B::TOut,
                B::TOut,
                IxD,
                dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
            >,
        B::TOut: Float + FromPrimitive + Send + Sync + 'static,
    {
        var_with_args(self, args)
    }
}

impl<R, T, B, D> TensorAny<R, T, B, D>
where
    R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
    D: DimAPI,
    B: OpStdAPI<T, D>,
{
    pub fn std_with_args_f(&self, args: impl Into<VarArgs>) -> Result<Tensor<B::TOut, B, IxD>>
    where
        B: DeviceCreationAnyAPI<B::TOut>
            + Op_MutA_RefB_API<
                B::TOut,
                B::TOut,
                IxD,
                dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
            >,
        B::TOut: Float + FromPrimitive + Send + Sync + 'static,
    {
        std_with_args_f(self, args)
    }

    pub fn std_with_args(&self, args: impl Into<VarArgs>) -> Tensor<B::TOut, B, IxD>
    where
        B: DeviceCreationAnyAPI<B::TOut>
            + Op_MutA_RefB_API<
                B::TOut,
                B::TOut,
                IxD,
                dyn for<'x, 'y> Fn(&'x mut MaybeUninit<B::TOut>, &'y B::TOut) + Send + Sync,
            >,
        B::TOut: Float + FromPrimitive + Send + Sync + 'static,
    {
        std_with_args(self, args)
    }
}

/* #endregion */

macro_rules! trait_reduction_arg {
    ([$($with_args: ident)?] $OpReduceAPI: ident, $fn: ident, $fn_f: ident, $fn_axes: ident, $fn_axes_f: ident, $fn_all: ident, $fn_all_f: ident, $fn_with_args: ident, $fn_with_args_f: ident) => {
        pub fn $fn_all_f<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> Result<D>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            let tensor = tensor.view();
            tensor.device().$fn_all(tensor.raw(), tensor.layout())
        }

        pub fn $fn_axes_f<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
        ) -> Result<Tensor<IxD, B, IxD>>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            let axes = axes.try_into().map_err(Into::into)?;
            let tensor = tensor.view();

            match axes {
                AxesIndex::None => {
                    // special case for reducing all axes
                    let arg = tensor.device().$fn_all(tensor.raw(), tensor.layout())?;
                    let storage = tensor.device().outof_cpu_vec(vec![arg.into()])?;
                    let layout = Layout::new(vec![], vec![], 0)?;
                    Tensor::new_f(storage, layout)
                },
                _ => {
                    let (storage, layout) = tensor.device().$fn_axes(tensor.raw(), tensor.layout(), axes.as_ref())?;
                    Tensor::new_f(storage, layout)
                },
            }
        }

        pub fn $fn_all<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> D
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all_f(tensor).rstsr_unwrap()
        }

        pub fn $fn_axes<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
        ) -> Tensor<IxD, B, IxD>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            $fn_axes_f(tensor, axes).rstsr_unwrap()
        }

        pub fn $fn_f<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> Result<D>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all_f(tensor)
        }

        pub fn $fn<T, B, D>(tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>) -> D
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            $fn_all(tensor)
        }

        trait_reduction_arg_with_args!([$($with_args)?] $OpReduceAPI, $fn_with_args_f, $fn_with_args, $fn_axes, $fn_all);

        impl<R, T, B, D> TensorAny<R, T, B, D>
        where
            R: DataAPI<Data = <B as DeviceRawAPI<T>>::Raw>,
            D: DimAPI,
            B: $OpReduceAPI<T, D>,
        {
            pub fn $fn_all_f(&self) -> Result<D> {
                $fn_all_f(self)
            }

            pub fn $fn_all(&self) -> D {
                $fn_all(self)
            }

            pub fn $fn_axes_f(
                &self,
                axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>,
            ) -> Result<Tensor<IxD, B, IxD>>
            where
                B: DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
            {
                $fn_axes_f(self, axes)
            }

            pub fn $fn_axes(&self, axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>) -> Tensor<IxD, B, IxD>
            where
                B: DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
            {
                $fn_axes(self, axes)
            }

            pub fn $fn_f(&self) -> Result<D> {
                $fn_f(self)
            }

            pub fn $fn(&self) -> D {
                $fn(self)
            }

            trait_reduction_arg_with_args_methods!([$($with_args)?] $fn_with_args_f, $fn_with_args);
        }
    };
}

/// Methods `<fam>_with_args[_f]` for the unraveled-arg families (IxD output).
macro_rules! trait_reduction_arg_with_args_methods {
    ([$_with_args: ident] $fn_with_args_f: ident, $fn_with_args: ident) => {
        pub fn $fn_with_args_f(&self, args: impl Into<ReduceArgs>) -> Result<Tensor<IxD, B, IxD>>
        where
            B: DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            $fn_with_args_f(self, args)
        }

        pub fn $fn_with_args(&self, args: impl Into<ReduceArgs>) -> Tensor<IxD, B, IxD>
        where
            B: DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            $fn_with_args(self, args)
        }
    };
    ([] $($rest: tt)*) => {};
}

/// Free functions `<fam>_with_args[_f]` for the unraveled-arg families.
macro_rules! trait_reduction_arg_with_args {
    ([$_with_args: ident] $OpReduceAPI: ident, $fn_with_args_f: ident, $fn_with_args: ident, $fn_axes: ident, $fn_all: ident) => {
        pub fn $fn_with_args_f<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Result<Tensor<IxD, B, IxD>>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            let ReduceArgs { axes, keepdims } = args.into();
            let tensor = tensor.view();

            {
                // unraveled all-form returns a dim; wrap into the 0-D/keepdims tensor
                match axes {
                    AxesIndex::None => {
                        let arg = tensor.device().$fn_all(tensor.raw(), tensor.layout())?;
                        let storage = tensor.device().outof_cpu_vec(vec![arg.into()])?;
                        let out_layout = reduce_layout_whole(tensor.layout().ndim(), keepdims)?;
                        Tensor::new_f(storage, out_layout)
                    },
                    axes => {
                        let (storage, out_layout) =
                            tensor.device().$fn_axes(tensor.raw(), tensor.layout(), axes.as_ref())?;
                        let out_layout = reduce_layout_keepdims(out_layout, &axes, tensor.layout().ndim(), keepdims)?;
                        Tensor::new_f(storage, out_layout)
                    },
                }
            }
        }

        pub fn $fn_with_args<T, B, D>(
            tensor: impl TensorViewAPI<Type = T, Backend = B, Dim = D>,
            args: impl Into<ReduceArgs>,
        ) -> Tensor<IxD, B, IxD>
        where
            D: DimAPI,
            B: $OpReduceAPI<T, D> + DeviceAPI<IxD> + DeviceCreationAnyAPI<IxD>,
        {
            $fn_with_args_f(tensor, args).rstsr_unwrap()
        }
    };
    ([] $($rest: tt)*) => {};
}

trait_reduction_arg!(
    [with_args]
    OpUnraveledArgMinAPI,
    unraveled_argmin,
    unraveled_argmin_f,
    unraveled_argmin_axes,
    unraveled_argmin_axes_f,
    unraveled_argmin_all,
    unraveled_argmin_all_f,
    unraveled_argmin_with_args,
    unraveled_argmin_with_args_f
);
trait_reduction_arg!(
    [with_args]
    OpUnraveledArgMaxAPI,
    unraveled_argmax,
    unraveled_argmax_f,
    unraveled_argmax_axes,
    unraveled_argmax_axes_f,
    unraveled_argmax_all,
    unraveled_argmax_all_f,
    unraveled_argmax_with_args,
    unraveled_argmax_with_args_f
);

/* #region sum (bool) */

pub trait TensorSumBoolAPI<B, D>
where
    D: DimAPI,
    B: DeviceAPI<bool> + DeviceAPI<usize> + OpSumBoolAPI<D>,
{
    fn sum_all_f(&self) -> Result<usize>;
    fn sum_all(&self) -> usize {
        self.sum_all_f().rstsr_unwrap()
    }
    fn sum_f(&self) -> Result<usize> {
        self.sum_all_f()
    }
    fn sum(&self) -> usize {
        self.sum_f().rstsr_unwrap()
    }
    fn sum_axes_f(&self, axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>) -> Result<Tensor<usize, B, IxD>>;
    fn sum_axes(&self, axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>) -> Tensor<usize, B, IxD> {
        self.sum_axes_f(axes).rstsr_unwrap()
    }
    fn sum_with_args_f(&self, args: impl Into<ReduceArgs>) -> Result<Tensor<usize, B, IxD>>;
    fn sum_with_args(&self, args: impl Into<ReduceArgs>) -> Tensor<usize, B, IxD> {
        self.sum_with_args_f(args).rstsr_unwrap()
    }
}

impl<R, B, D> TensorSumBoolAPI<B, D> for TensorAny<R, bool, B, D>
where
    R: DataAPI<Data = <B as DeviceRawAPI<bool>>::Raw>,
    D: DimAPI,
    B: DeviceAPI<bool> + DeviceAPI<usize> + OpSumBoolAPI<D> + DeviceCreationAnyAPI<usize>,
{
    fn sum_all_f(&self) -> Result<usize> {
        self.device().sum_all(self.raw(), self.layout())
    }

    fn sum_axes_f(&self, axes: impl TryInto<AxesIndex<isize>, Error: Into<Error>>) -> Result<Tensor<usize, B, IxD>> {
        let axes = axes.try_into().map_err(Into::into)?;

        match axes {
            AxesIndex::None => {
                // special case for summing all axes
                let sum = self.device().sum_all(self.raw(), self.layout())?;
                let storage = self.device().outof_cpu_vec(vec![sum])?;
                let layout = Layout::new(vec![], vec![], 0)?;
                Tensor::new_f(storage, layout)
            },
            _ => {
                let (storage, layout) = self.device().sum_axes(self.raw(), self.layout(), axes.as_ref())?;
                Tensor::new_f(storage, layout)
            },
        }
    }

    fn sum_with_args_f(&self, args: impl Into<ReduceArgs>) -> Result<Tensor<usize, B, IxD>> {
        let ReduceArgs { axes, keepdims } = args.into();
        let tensor = self.view();
        reduce_dispatch_output!(tensor, sum_all, sum_axes, axes, keepdims)
    }
}

/* #endregion */

/* #region allclose */

/// Whether two tensors are element-wise equal within tolerances
/// (`all(|a - b| <= atol + rtol * |b|)`).
///
/// The two tensors are broadcast against each other; the result is a single
/// `bool`. Default tolerances (for `f64`): `rtol = 1.0e-5`, `atol = 1.0e-8`,
/// `equal_nan = false` (see [`IsCloseArgs`]).
///
/// This function behaves identically under [`RowMajor`] and [`ColMajor`] device default orders.
///
/// # Parameters
///
/// - `tensor_a` / `tensor_b`: the tensors to compare (broadcast against each other).
/// - `isclose_args`: tolerances; anything that converts into [`IsCloseArgs`] — pass `None` for the
///   defaults.
///
/// # Returns
///
/// - `bool`: `true` if every element pair is close.
///
/// # Examples
///
/// ```rust
/// # use rstsr::prelude::*;
/// # let mut device = DeviceCpu::default();
/// # device.set_default_order(RowMajor);
/// let a = rt::tensor_from_nested!([[1.0, 5.0, 3.0], [4.0, 5.0, 2.0]], &device);
/// let b = rt::tensor_from_nested!([[1.0, 5.0, 3.0], [4.0, 5.0, 2.0]], &device);
/// println!("{}", rt::allclose(&a, &b, None));
/// // true
/// let c = rt::tensor_from_nested!([[1.0, 5.1, 3.0], [4.0, 5.0, 2.0]], &device);
/// println!("{}", rt::allclose(&a, &c, None));
/// // false
/// # assert!(rt::allclose(&a, &b, None));
/// # assert!(!rt::allclose(&a, &c, None));
/// ```
///
/// # Notes of API accordance
///
/// - NumPy: `numpy.allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)` ([`numpy.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html))
/// - RSTSR: `rt::allclose(&a, &b, None)`; tolerances are grouped into [`IsCloseArgs`]. The macro
///   form `allclose!(&a, &b)` is also available.
///
/// # See also
///
/// ## Similar function from other crates/libraries
///
/// - NumPy: [`numpy.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)
///
/// ## Related functions in RSTSR
///
/// - `isclose`: element-wise closeness is available on the dtype traits (`ExtFloat::isclose` of
///   `rstsr-dtype-traits`).
///
/// ## Variants of this function
///
/// - [`allclose_f`]: fallible version.
/// - [`allclose_all`] / [`allclose_all_f`]: explicit all-element form.
/// - Macro: `allclose!(&a, &b)` (crate-level exported, same name as the function).
pub fn allclose_all_f<TA, TB, TE, B, DA, DB>(
    tensor_a: impl TensorViewAPI<Type = TA, Backend = B, Dim = DA>,
    tensor_b: impl TensorViewAPI<Type = TB, Backend = B, Dim = DB>,
    isclose_args: impl Into<IsCloseArgs<TE>>,
) -> Result<bool>
where
    DA: DimAPI,
    DB: DimAPI,
    B: DeviceAPI<bool> + OpAllCloseAPI<TA, TB, TE, IxD>,
    TE: 'static,
{
    let tensor_a = tensor_a.view();
    let tensor_b = tensor_b.view();
    let isclose_args = isclose_args.into();
    let device = tensor_a.device();

    // check device
    rstsr_assert!(tensor_a.device().same_device(tensor_b.device()), DeviceMismatch)?;

    // check and broadcast layout

    let la = tensor_a.layout().to_dim::<IxD>()?;
    let lb = tensor_b.layout().to_dim::<IxD>()?;
    let default_order = device.default_order();
    let (la_b, lb_b) = broadcast_layout(&la, &lb, default_order)?;

    device.allclose_all(tensor_a.raw(), &la_b, tensor_b.raw(), &lb_b, &isclose_args)
}

pub fn allclose_all<TA, TB, TE, B, DA, DB>(
    tensor_a: impl TensorViewAPI<Type = TA, Backend = B, Dim = DA>,
    tensor_b: impl TensorViewAPI<Type = TB, Backend = B, Dim = DB>,
    isclose_args: impl Into<IsCloseArgs<TE>>,
) -> bool
where
    DA: DimAPI,
    DB: DimAPI,
    B: DeviceAPI<bool> + OpAllCloseAPI<TA, TB, TE, IxD>,
    TE: 'static,
{
    allclose_all_f(tensor_a, tensor_b, isclose_args).rstsr_unwrap()
}

pub fn allclose_f<TA, TB, TE, B, DA, DB>(
    tensor_a: impl TensorViewAPI<Type = TA, Backend = B, Dim = DA>,
    tensor_b: impl TensorViewAPI<Type = TB, Backend = B, Dim = DB>,
    isclose_args: impl Into<IsCloseArgs<TE>>,
) -> Result<bool>
where
    DA: DimAPI,
    DB: DimAPI,
    B: DeviceAPI<bool> + OpAllCloseAPI<TA, TB, TE, IxD>,
    TE: 'static,
{
    allclose_all_f(tensor_a, tensor_b, isclose_args)
}

pub fn allclose<TA, TB, TE, B, DA, DB>(
    tensor_a: impl TensorViewAPI<Type = TA, Backend = B, Dim = DA>,
    tensor_b: impl TensorViewAPI<Type = TB, Backend = B, Dim = DB>,
    isclose_args: impl Into<IsCloseArgs<TE>>,
) -> bool
where
    DA: DimAPI,
    DB: DimAPI,
    B: DeviceAPI<bool> + OpAllCloseAPI<TA, TB, TE, IxD>,
    TE: 'static,
{
    allclose_f(tensor_a, tensor_b, isclose_args).rstsr_unwrap()
}

#[macro_export]
macro_rules! allclose {
    ($tensor_a:expr, $tensor_b:expr, $isclose_args:expr) => {{
        use rstsr::prelude::rstsr_funcs::allclose;
        allclose($tensor_a, $tensor_b, $isclose_args)
    }};
    ($tensor_a:expr, $tensor_b:expr) => {{
        use rstsr::prelude::rstsr_funcs::allclose;
        allclose($tensor_a, $tensor_b, None)
    }};
}

/* #endregion */

#[cfg(test)]
mod test {
    use num::ToPrimitive;

    use super::*;

    #[test]
    #[cfg(not(feature = "col_major"))]
    fn test_sum_all_row_major() {
        // DeviceCpuSerial
        let a = arange((24, &DeviceCpuSerial::default()));
        let s = sum_all(&a);
        assert_eq!(s, 276);

        // np.arange(3240).reshape(12, 15, 18)
        //   .swapaxes(-1, -2)[2:-3, 1:-4:2, -1:3:-2].sum()
        let a_owned = arange((3240, &DeviceCpuSerial::default())).into_shape([12, 15, 18]).into_swapaxes(-1, -2);
        let a = a_owned.i((slice!(2, -3), slice!(1, -4, 2), slice!(-1, 3, -2)));
        let s = a.sum_all();
        assert_eq!(s, 446586);

        let s = a.sum_axes(None);
        println!("{s:?}");
        assert_eq!(s.to_scalar(), 446586);

        // DeviceFaer
        let a = arange(24);
        let s = sum_all(&a);
        assert_eq!(s, 276);

        // np.arange(3240).reshape(12, 15, 18)
        //   .swapaxes(-1, -2)[2:-3, 1:-4:2, -1:3:-2].sum()
        let a_owned: Tensor<usize> = arange(3240).into_shape([12, 15, 18]).into_swapaxes(-1, -2);
        let a = a_owned.i((slice!(2, -3), slice!(1, -4, 2), slice!(-1, 3, -2)));
        let s = a.sum_all();
        assert_eq!(s, 446586);

        let s = a.sum_axes(None);
        println!("{s:?}");
        assert_eq!(s.to_scalar(), 446586);
    }

    #[test]
    #[cfg(feature = "col_major")]
    fn test_sum_all_col_major() {
        // DeviceCpuSerial
        let a = arange((24, &DeviceCpuSerial::default()));
        let s = sum_all(&a);
        assert_eq!(s, 276);

        // a = reshape(range(0, 3239), (12, 15, 18));
        // a = permutedims(a, (1, 3, 2));
        // a = a[3:9, 2:2:15, 15:-2:4];
        // sum(a)
        let a_owned = arange((3240, &DeviceCpuSerial::default())).into_shape([12, 15, 18]).into_swapaxes(-1, -2);
        let a = a_owned.i((slice!(2, -3), slice!(1, -4, 2), slice!(-1, 3, -2)));
        let s = a.sum_all();
        assert_eq!(s, 403662);

        let s = a.sum_axes(None);
        println!("{s:?}");
        assert_eq!(s.to_scalar(), 403662);

        // DeviceFaer
        let a = arange(24);
        let s = sum_all(&a);
        assert_eq!(s, 276);

        let a_owned: Tensor<usize> = arange(3240).into_shape([12, 15, 18]).into_swapaxes(-1, -2);
        let a = a_owned.i((slice!(2, -3), slice!(1, -4, 2), slice!(-1, 3, -2)));
        let s = a.sum_all();
        assert_eq!(s, 403662);

        let s = a.sum_axes(None);
        println!("{s:?}");
        assert_eq!(s.to_scalar(), 403662);
    }

    #[test]
    fn test_sum_axes() {
        #[cfg(not(feature = "col_major"))]
        {
            // a = np.arange(3240).reshape(4, 6, 15, 9).transpose(2, 0, 3, 1)
            // a.sum(axis=(0, -2))
            // DeviceCpuSerial
            let a = arange((3240, &DeviceCpuSerial::default())).into_shape([4, 6, 15, 9]).into_transpose([2, 0, 3, 1]);
            let s = a.sum_axes([0, -2]);
            println!("{s:?}");
            assert_eq!(s[[0, 1]], 27270);
            assert_eq!(s[[1, 2]], 154845);
            assert_eq!(s[[3, 5]], 428220);

            // DeviceFaer
            let a: Tensor<usize> = arange(3240).into_shape([4, 6, 15, 9]).into_transpose([2, 0, 3, 1]);
            let s = a.sum_axes([0, -2]);
            println!("{s:?}");
            assert_eq!(s[[0, 1]], 27270);
            assert_eq!(s[[1, 2]], 154845);
            assert_eq!(s[[3, 5]], 428220);
        }
        #[cfg(feature = "col_major")]
        {
            // a = reshape(range(0, 3239), (4, 6, 15, 9));
            // a = permutedims(a, (3, 1, 4, 2));
            // sum(a, dims=(1, 3))
            // DeviceCpuSerial
            let a = arange((3240, &DeviceCpuSerial::default())).into_shape([4, 6, 15, 9]).into_transpose([2, 0, 3, 1]);
            let s = a.sum_axes([0, -2]);
            println!("{s:?}");
            assert_eq!(s[[0, 1]], 217620);
            assert_eq!(s[[1, 2]], 218295);
            assert_eq!(s[[3, 5]], 220185);

            // DeviceFaer
            let a: Tensor<usize> = arange(3240).into_shape([4, 6, 15, 9]).into_transpose([2, 0, 3, 1]);
            let s = a.sum_axes([0, -2]);
            println!("{s:?}");
            assert_eq!(s[[0, 1]], 217620);
            assert_eq!(s[[1, 2]], 218295);
            assert_eq!(s[[3, 5]], 220185);
        }
    }

    #[test]
    fn test_min() {
        // DeviceCpuSerial
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default()));
        println!("{a:}");
        let m = a.min_axes(0);
        assert_eq!(m.to_vec(), vec![2, 3, 1]);
        let m = a.min_axes(1);
        assert_eq!(m.to_vec(), vec![2, 3, 1, 5]);
        let m = a.min_all();
        assert_eq!(m, 1);

        // DeviceFaer
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c()));
        println!("{a:}");
        let m = a.min_axes(0);
        assert_eq!(m.to_vec(), vec![2, 3, 1]);
        let m = a.min_axes(1);
        assert_eq!(m.to_vec(), vec![2, 3, 1, 5]);
        let m = a.min_all();
        assert_eq!(m, 1);
    }

    #[test]
    fn test_mean() {
        #[cfg(not(feature = "col_major"))]
        {
            // DeviceCpuSerial
            let a = arange((24.0, &DeviceCpuSerial::default())).into_shape((2, 3, 4));
            let m = a.mean_all();
            assert_eq!(m, 11.5);

            let m = a.mean_axes((0, 2));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![7.5, 11.5, 15.5]);

            let m = a.i((slice!(None, None, -1), .., slice!(None, None, -2))).mean_axes((-1, 1));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![18.0, 6.0]);

            // DeviceFaer
            let a: Tensor<f64> = arange(24.0).into_shape((2, 3, 4));
            let m = a.mean_all();
            assert_eq!(m, 11.5);

            let m = a.mean_axes((0, 2));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![7.5, 11.5, 15.5]);

            let m = a.i((slice!(None, None, -1), .., slice!(None, None, -2))).mean_axes((-1, 1));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![18.0, 6.0]);
        }
        #[cfg(feature = "col_major")]
        {
            // DeviceCpuSerial
            let a = arange((24.0, &DeviceCpuSerial::default())).into_shape((2, 3, 4));
            let m = a.mean_all();
            assert_eq!(m, 11.5);

            let m = a.mean_axes((0, 2));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![9.5, 11.5, 13.5]);

            let m = a.i((slice!(None, None, -1), .., slice!(None, None, -2))).mean_axes((-1, 1));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![15.0, 14.0]);

            // // DeviceFaer
            let a: Tensor<f64> = arange(24.0).into_shape((2, 3, 4));
            let m = a.mean_all();
            assert_eq!(m, 11.5);

            let m = a.mean_axes((0, 2));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![9.5, 11.5, 13.5]);

            let m = a.i((slice!(None, None, -1), .., slice!(None, None, -2))).mean_axes((-1, 1));
            println!("{m:}");
            assert_eq!(m.to_vec(), vec![15.0, 14.0]);
        }
    }

    #[test]
    fn test_var() {
        // DeviceCpuSerial
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default())).mapv(|x| x as f64);

        let m = a.var_all();
        println!("{m:}");
        assert!((m - 8.409722222222221).abs() < 1e-10);

        let m = a.var_axes(0);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![7.1875, 8.1875, 5.6875])));

        let m = a.var_axes(1);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![6.22222222, 6.22222222, 9.55555556, 4.66666667])));

        // DeviceFaer
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c())).mapv(|x| x as f64);

        let m = a.var_all();
        println!("{m:}");
        assert!((m - 8.409722222222221).abs() < 1e-10);

        let m = a.var_axes(0);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![7.1875, 8.1875, 5.6875])));

        let m = a.var_axes(1);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![6.22222222, 6.22222222, 9.55555556, 4.66666667])));
    }

    #[test]
    fn test_std() {
        // DeviceCpuSerial
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default())).mapv(|x| x as f64);

        let m = a.std_all();
        println!("{m:}");
        assert!((m - 2.899952106884219).abs() < 1e-10);

        let m = a.std_axes(0);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![2.68095132, 2.86138079, 2.384848])));

        let m = a.std_axes(1);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![2.49443826, 2.49443826, 3.09120617, 2.1602469])));

        let vr = [8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let vi = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
        let v = vr
            .iter()
            .zip(vi.iter())
            .map(|(r, i)| num::Complex::new(r.to_f64().unwrap(), i.to_f64().unwrap()))
            .collect::<Vec<_>>();
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default()));

        let m = a.std_all();
        println!("{m:}");
        assert!((m - 4.508479664907993).abs() < 1e-10);

        // DeviceFaer
        let v = vec![8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let a = asarray((&v, [4, 3].c())).mapv(|x| x as f64);

        let m = a.std_all();
        println!("{m:}");
        assert!((m - 2.899952106884219).abs() < 1e-10);

        let m = a.std_axes(0);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![2.68095132, 2.86138079, 2.384848])));

        let m = a.std_axes(1);
        println!("{m:}");
        assert!(allclose_f64(&m, &asarray(vec![2.49443826, 2.49443826, 3.09120617, 2.1602469])));

        let vr = [8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let vi = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
        let v = vr
            .iter()
            .zip(vi.iter())
            .map(|(r, i)| num::Complex::new(r.to_f64().unwrap(), i.to_f64().unwrap()))
            .collect::<Vec<_>>();
        let a = asarray((&v, [4, 3].c()));

        let m = a.std_all();
        println!("{m:}");
        assert!((m - 4.508479664907993).abs() < 1e-10);
    }

    #[test]
    fn test_l2_norm() {
        // DeviceCpuSerial
        let vr = [8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let vi = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
        let v = vr
            .iter()
            .zip(vi.iter())
            .map(|(r, i)| num::Complex::new(r.to_f64().unwrap(), i.to_f64().unwrap()))
            .collect::<Vec<_>>();
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default()));

        let m = a.l2_norm_all();
        println!("{m:}");
        assert!((m - 33.21144381083123).abs() < 1e-10);

        // DeviceFaer
        let vr = [8, 4, 2, 9, 3, 7, 2, 8, 1, 6, 10, 5];
        let vi = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];
        let v = vr
            .iter()
            .zip(vi.iter())
            .map(|(r, i)| num::Complex::new(r.to_f64().unwrap(), i.to_f64().unwrap()))
            .collect::<Vec<_>>();
        let a = asarray((&v, [4, 3].c()));

        let m = a.l2_norm_all();
        println!("{m:}");
        assert!((m - 33.21144381083123).abs() < 1e-10);
    }

    #[test]
    #[cfg(feature = "rayon")]
    fn test_large_std() {
        #[cfg(not(feature = "col_major"))]
        {
            // a = np.linspace(0, 1, 1048576).reshape(16, 256, 256)
            // b = np.linspace(1, 2, 1048576).reshape(16, 256, 256)
            // c = a @ b
            // print(c.mean(), c.std())
            // print(c.std(axis=(0, 1))[[0, -1]])
            // print(c.std(axis=(1, 2))[[0, -1]])
            let a = linspace((0.0, 1.0, 1048576)).into_shape([16, 256, 256]);
            let b = linspace((1.0, 2.0, 1048576)).into_shape([16, 256, 256]);
            let c: Tensor<f64> = &a % &b;

            let c_mean = c.mean_all();
            println!("{c_mean:?}");
            assert!((c_mean - 213.2503660477036) < 1e-6);

            let c_std = c.std_all();
            println!("{c_std:?}");
            assert!((c_std - 148.88523481701804) < 1e-6);

            let c_std_1 = c.std_axes((0, 1));
            println!("{c_std_1}");
            assert!(c_std_1[[0]] - 148.8763226818815 < 1e-6);
            assert!(c_std_1[[255]] - 148.8941462322758 < 1e-6);

            let c_std_2 = c.std_axes((1, 2));
            println!("{c_std_2}");
            assert!(c_std_2[[0]] - 4.763105902995575 < 1e-6);
            assert!(c_std_2[[15]] - 9.093224903569157 < 1e-6);
        }
        #[cfg(feature = "col_major")]
        {
            // a = reshape(LinRange(0, 1, 1048576), (256, 256, 16));
            // b = reshape(LinRange(1, 2, 1048576), (256, 256, 16));
            // c = Array{Float64}(undef, 256, 256, 16);
            // for i in 1:16
            //     c[:, :, i] = a[:, :, i] * b[:, :, i]
            // end
            // mean(c), std(c)
            // std(c, dims=(2, 3))
            // std(c, dims=(1, 2))
            let a = linspace((0.0, 1.0, 1048576)).into_shape([256, 256, 16]);
            let b = linspace((1.0, 2.0, 1048576)).into_shape([256, 256, 16]);
            let mut c: Tensor<f64> = zeros([256, 256, 16]);
            for i in 0..16 {
                c.i_mut((.., .., i)).assign(&a.i((.., .., i)) % &b.i((.., .., i)));
            }

            let c_mean = c.mean_all();
            println!("{c_mean:?}");
            assert!((c_mean - 213.25036604770355) < 1e-6);

            let c_std = c.std_all();
            println!("{c_std:?}");
            assert!((c_std - 148.7419537312827) < 1e-6);

            let c_std_1 = c.std_axes((1, 2));
            println!("{c_std_1}");
            assert!(c_std_1[[0]] - 148.75113653867191 < 1e-6);
            assert!(c_std_1[[255]] - 148.7689445622776 < 1e-6);

            let c_std_2 = c.std_axes((0, 1));
            println!("{c_std_2}");
            assert!(c_std_2[[0]] - 0.145530296246335 < 1e-6);
            assert!(c_std_2[[15]] - 4.474611918106057 < 1e-6);
        }
    }

    #[test]
    fn test_unraveled_argmin() {
        // DeviceCpuSerial
        let v = vec![8, 4, 2, 9, 7, 1, 2, 1, 8, 6, 10, 5];
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default()));
        println!("{a:}");
        // [[ 8 4 2]
        //  [ 9 7 1]
        //  [ 2 1 8]
        //  [ 6 10 5]]

        let m = a.unraveled_argmin_all();
        println!("{m:?}");
        assert_eq!(m, vec![1, 2]);

        let m = a.unraveled_argmin_axes(-1);
        println!("{m:?}");
        let m_vec = m.raw();
        assert_eq!(m_vec, &vec![vec![2], vec![2], vec![1], vec![2]]);

        let m = a.unraveled_argmin_axes(0);
        println!("{m:?}");
        let m_vec = m.raw();
        assert_eq!(m_vec, &vec![vec![2], vec![2], vec![1]]);
    }

    #[test]
    fn test_argmin() {
        // DeviceCpuSerial
        let v = vec![8, 4, 2, 9, 7, 1, 2, 1, 8, 6, 10, 5];
        let a = asarray((&v, [4, 3].c(), &DeviceCpuSerial::default()));
        println!("{a:}");
        // [[ 8 4 2]
        //  [ 9 7 1]
        //  [ 2 1 8]
        //  [ 6 10 5]]

        let m = a.argmin_all();
        println!("{m:?}");
        assert_eq!(m, 5);

        let m = a.argmin_axes(-1);
        println!("{m:?}");
        let m_vec = m.raw();
        assert_eq!(m_vec, &vec![2, 2, 1, 2]);

        let m = a.argmin_axes(0);
        println!("{m:?}");
        let m_vec = m.raw();
        assert_eq!(m_vec, &vec![2, 2, 1]);
    }

    #[test]
    #[cfg(feature = "faer")]
    fn test_with_args_and_dtype_faer() {
        // rayon (DeviceFaer) paths of *_with_args / *_with_dtype
        let a: Tensor<i32, DeviceFaer> = asarray((vec![1, 2, 3, 4, 5, 6], [2, 3].c(), &DeviceFaer::default()));

        let s = a.sum_with_args(([0], true));
        assert_eq!(s.shape().to_vec(), vec![1, 3]);
        assert_eq!(s[[0, 0]], 5);
        assert_eq!(s[[0, 2]], 9);

        let s = a.sum_with_dtype::<i64>(true);
        assert_eq!(s.to_scalar(), 21i64);

        let m = a.mean_with_dtype::<f64>(1);
        assert_eq!(m[[0]], 2.0);
        assert_eq!(m[[1]], 5.0);

        // prod / var / std dtype paths (rayon kernels)
        let p = a.prod_with_dtype::<i64>(());
        assert_eq!(p.to_scalar(), 720i64);
        let x: Tensor<f64, DeviceFaer> = asarray((vec![1.0, 2.0, 3.0, 4.0], &DeviceFaer::default()));
        let v = x.var_with_dtype::<f64>(VarArgs { correction: Some(1.0), ..Default::default() });
        assert!((v.to_scalar() - 5.0 / 3.0).abs() < 1e-12);
        let s = x.std_with_dtype::<f64>(VarArgs { correction: Some(1.0), ..Default::default() });
        assert!((s.to_scalar() - (5.0f64 / 3.0).sqrt()).abs() < 1e-12);

        // with_args + stride-0 input (rayon axes kernel)
        let av: Tensor<i64, DeviceFaer> = asarray((vec![0i64, 1, 2, 3], [4, 1].c(), &DeviceFaer::default()));
        let av_dyn = av.into_dyn();
        let bv: TensorView<i64, DeviceFaer, Vec<usize>> = broadcast_to(&av_dyn, vec![4usize, 3]);
        assert_eq!(bv.sum_axes(1).to_vec(), vec![0i64, 3, 6, 9]);
        assert_eq!(bv.sum_axes([0, 1]).to_scalar(), 18i64);
    }

    #[test]
    fn test_all() {
        let a = asarray((vec![true, true, false, true, true, true], [2, 3].c()));
        let a_all = a.all_axes(-2);
        println!("{:?}", a_all);
        assert_eq!(a_all.raw(), &[true, true, false]);
    }

    #[test]
    fn test_allclose_cpu_serial() {
        use rstsr_dtype_traits::IsCloseArgsBuilder;

        let mut device = DeviceCpuSerial::default();
        device.set_default_order(RowMajor);
        let a = asarray((vec![1, 2, 3, 4], [2, 2].c(), &device));
        let b = asarray((vec![1.0f32, 3.0, 2.0, 4.00001], [2, 2].f(), &device));
        let result = allclose(&a, &b, None);
        println!("Allclose result: {result}");
        assert!(result);
        let args = IsCloseArgsBuilder::default().atol(1e-8).rtol(1e-8).build().unwrap();
        let result = allclose(&a, &b, args);
        println!("Allclose result with tight args: {result}");
        assert!(!result);
    }

    #[test]
    #[cfg(feature = "faer")]
    fn test_allclose_faer() {
        use rstsr_dtype_traits::IsCloseArgsBuilder;

        let mut device = DeviceFaer::default();
        device.set_default_order(RowMajor);
        let a = asarray((vec![1, 2, 3, 4], [2, 2].c(), &device));
        let b = asarray((vec![1.0f32, 3.0, 2.0, 4.00001], [2, 2].f(), &device));
        let result = allclose(&a, &b, None);
        println!("Allclose result: {result}");
        assert!(result);
        let args = IsCloseArgsBuilder::default().atol(1e-8).rtol(1e-8).build().unwrap();
        let result = allclose(&a, &b, args);
        println!("Allclose result with tight args: {result}");
        assert!(!result);
    }
}
