/*!
Strided batched matmul (uniformly-strided batches) for the OpenBLAS device.

The computation delegates to the device matmul, which dispatches onto the
strided batched GEMM extension whenever the feature `use_batched_gemm_strided`
is enabled. Beyond the `batched_matmul` contract, this trait requires the
batch dims of both operands to be *uniformly-strided* (reducible to a single
stride per operand, in a common flat order); scattered batches are runtime
errors here and should use `batched_matmul` instead.

Most or all contents generated by AI (model glm-5.3).
*/

use crate::DeviceBLAS;
use rstsr_blas_traits::prelude::*;
use rstsr_core::prelude::rt;
use rstsr_core::prelude_dev::*;
use rstsr_linalg_traits::prelude_dev::*;

#[duplicate_item(
     TrA                               TrB                              ;
    [ TensorAny<RA, T, DeviceBLAS, D>] [ TensorAny<RB, T, DeviceBLAS, D>];
    [&TensorAny<RA, T, DeviceBLAS, D>] [ TensorAny<RB, T, DeviceBLAS, D>];
    [ TensorAny<RA, T, DeviceBLAS, D>] [&TensorAny<RB, T, DeviceBLAS, D>];
    [&TensorAny<RA, T, DeviceBLAS, D>] [&TensorAny<RB, T, DeviceBLAS, D>];
)]
impl<RA, RB, T, D> BatchedMatmulStridedAPI<DeviceBLAS> for (TrA, TrB)
where
    RA: DataAPI<Data = <DeviceBLAS as DeviceRawAPI<T>>::Raw>,
    RB: DataAPI<Data = <DeviceBLAS as DeviceRawAPI<T>>::Raw>,
    T: BlasFloat,
    D: DimAPI,
    DeviceBLAS: DeviceCreationAnyAPI<T> + DeviceMatMulAPI<T, T, T, D, D, D>,
    LayoutMatMulConfig<D, D>: LayoutMatMulAPI<D, D, DC = D>,
{
    type Out = Tensor<T, DeviceBLAS, D>;

    fn batched_matmul_strided_f(self) -> Result<Self::Out> {
        let (a, b) = self;
        let a = a.view();
        let b = b.view();
        rstsr_assert!(a.device().same_device(b.device()), DeviceMismatch)?;
        let la = a.layout();
        let lb = b.layout();
        let n = la.ndim();
        rstsr_assert!(n >= 3, InvalidLayout)?;
        rstsr_assert_eq!(n, lb.ndim(), InvalidLayout)?;
        rstsr_assert_eq!(&la.shape().as_ref()[..n - 2], &lb.shape().as_ref()[..n - 2], InvalidLayout)?;
        rstsr_assert_eq!(la.shape()[n - 1], lb.shape()[n - 2], InvalidLayout)?;

        // require uniformly-strided batches, in a common flat order, on both
        // operands (the output is freshly allocated by the device matmul)
        let la = a.layout().to_dim::<IxD>()?;
        let lb = b.layout().to_dim::<IxD>()?;
        let (la_rest, _) = la.dim_split_at(-2)?;
        let (lb_rest, _) = lb.dim_split_at(-2)?;
        let (oa, sa) = match batched_flat_stride(&la_rest) {
            Some(v) => v,
            None => return rstsr_invalid!("A batch dims are scattered; use batched_matmul instead")?,
        };
        let (ob, sb) = match batched_flat_stride(&lb_rest) {
            Some(v) => v,
            None => return rstsr_invalid!("B batch dims are scattered; use batched_matmul instead")?,
        };
        rstsr_assert!(
            sa == 0 || sb == 0 || oa == ob,
            InvalidLayout,
            "A and B batch dims must reduce to a common flat order"
        )?;

        rt::matmul_f(a, b)
    }
}
