/*!
Batched matmul (arbitrary batch layouts) for the OpenBLAS device.

The trait accepts any batch layout (uniformly-strided or scattered); the
computation delegates to the device matmul, which dispatches onto the
grouped (pointer-based) batched GEMM extension whenever the feature
`use_batched_gemm` is enabled, and falls back to the per-slice loop
otherwise.

Contract: both operands have rank >= 3, identical batch shapes, and uniform
matrix shapes; violations are runtime errors.

Most or all contents generated by AI (model glm-5.3).
*/

use crate::DeviceBLAS;
use rstsr_blas_traits::prelude::*;
use rstsr_core::prelude::rt;
use rstsr_core::prelude_dev::*;
use rstsr_linalg_traits::prelude_dev::*;

#[duplicate_item(
     TrA                               TrB                              ;
    [ TensorAny<RA, T, DeviceBLAS, D>] [ TensorAny<RB, T, DeviceBLAS, D>];
    [&TensorAny<RA, T, DeviceBLAS, D>] [ TensorAny<RB, T, DeviceBLAS, D>];
    [ TensorAny<RA, T, DeviceBLAS, D>] [&TensorAny<RB, T, DeviceBLAS, D>];
    [&TensorAny<RA, T, DeviceBLAS, D>] [&TensorAny<RB, T, DeviceBLAS, D>];
)]
impl<RA, RB, T, D> BatchedMatmulAPI<DeviceBLAS> for (TrA, TrB)
where
    RA: DataAPI<Data = <DeviceBLAS as DeviceRawAPI<T>>::Raw>,
    RB: DataAPI<Data = <DeviceBLAS as DeviceRawAPI<T>>::Raw>,
    T: BlasFloat,
    D: DimAPI,
    DeviceBLAS: DeviceCreationAnyAPI<T> + DeviceMatMulAPI<T, T, T, D, D, D>,
    LayoutMatMulConfig<D, D>: LayoutMatMulAPI<D, D, DC = D>,
{
    type Out = Tensor<T, DeviceBLAS, D>;

    fn batched_matmul_f(self) -> Result<Self::Out> {
        let (a, b) = self;
        let a = a.view();
        let b = b.view();
        rstsr_assert!(a.device().same_device(b.device()), DeviceMismatch)?;
        let la = a.layout();
        let lb = b.layout();
        let n = la.ndim();
        rstsr_assert!(n >= 3, InvalidLayout)?;
        rstsr_assert_eq!(n, lb.ndim(), InvalidLayout)?;
        rstsr_assert_eq!(&la.shape().as_ref()[..n - 2], &lb.shape().as_ref()[..n - 2], InvalidLayout)?;
        rstsr_assert_eq!(la.shape()[n - 1], lb.shape()[n - 2], InvalidLayout)?;
        rt::matmul_f(a, b)
    }
}
