//! Element-wise operators: arithmetic (`add`, `sub`, `mul`, `div`, `rem`),
//! unary math (`sin`, `exp`, `sqrt`, ...), comparisons, and bitwise
//! operations, available as free functions and
//! [`TensorAny`](crate::TensorAny) methods.
//!
//! Functions and their backing traits are generated by macros
//! (`duplicate_item`, `trait_unary!`); device-side trait definitions live in
//! [`crate::operators`]. Note that `%` between two tensors is matrix
//! multiplication (see [`matmul`](crate::tensor::linalg::matmul::matmul()));
//! the element-wise remainder is the function
//! [`rem`](crate::tensor::operators::op_binary_arithmetic::rem()).

pub mod op_binary_arithmetic;
pub mod op_binary_assign;
pub mod op_binary_common;
pub mod op_tri;
pub mod op_unary_arithmetic;
pub mod op_unary_common;
pub mod op_with_func;

#[allow(unused_imports)]
pub mod exports {
    use super::*;
    pub use op_binary_arithmetic::*;
    pub use op_binary_assign::*;
    pub use op_binary_common::*;
    pub use op_tri::*;
    pub use op_unary_arithmetic::*;
    pub use op_unary_common::*;
    pub use op_with_func::*;
}
