// Most or all contents generated by AI (model glm-5.3).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy TestClip (numpy/_core/tests/test_multiarray.py) translations.
// Known divergences (see tests/tracking/numpy_differences.md):
// - the `(a_min, a_max)` positional pair becomes a single `(lo, hi)` argument group carrying `None`
//   for an absent bound; both bounds absent returns a copy (array-API) where NumPy raises.
// - scalar bounds follow rstsr's strong promotion, not NumPy's NEP 50 weak scalars.
// - in-place (`out=`) and byteorder variants are not translated (rstsr clip is out-of-place only).

#[cfg(test)]
mod numpy_clip {
    use super::*;
    static FUNC: &str = "numpy_clip";

    /// Clip a fixed value list under scalar bounds and check both the scalar
    /// and the equivalent 0-d tensor form against `min(max(x, lo), hi)`.
    macro_rules! assert_basic_case {
        ($ty:ty, $vals:expr, $lo:expr, $hi:expr, $device:expr) => {{
            let device = &$device;
            let vals: Vec<$ty> = $vals.iter().map(|&v| v as $ty).collect();
            let x = rt::asarray((vals.clone(), device));
            let lo: $ty = $lo as $ty;
            let hi: $ty = $hi as $ty;
            let expect: Vec<$ty> = vals.iter().map(|&v| v.max(lo).min(hi)).collect();

            assert_eq!(rt::clip(&x, (lo, hi)).to_vec(), expect);
            assert_eq!(rt::clip(&x, (None, hi)).to_vec(), vals.iter().map(|&v| v.min(hi)).collect::<Vec<$ty>>());
            assert_eq!(rt::clip(&x, (lo, None)).to_vec(), vals.iter().map(|&v| v.max(lo)).collect::<Vec<$ty>>());

            let lo0 = rt::full(([], lo, device));
            let hi0 = rt::full(([], hi, device));
            assert_eq!(rt::clip(&x, (&lo0, &hi0)).to_vec(), expect);
        }};
    }

    #[test]
    fn test_basic() {
        // numpy: v2.5.2 | _core/tests/test_multiarray.py::TestClip::test_basic (L5800)
        crate::specify_test!("test_basic");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let vals: Vec<f64> = vec![-1000.0, -120.0, -12.0, 0.0, 0.5, 13.5, 99.0, 150.0, 1000.0];

        // float: [-12.8, 100.2] and the degenerate [0, 0]
        assert_basic_case!(f32, vals, -12.8, 100.2, device);
        assert_basic_case!(f64, vals, -12.8, 100.2, device);
        assert_basic_case!(f32, vals, 0.0, 0.0, device);
        assert_basic_case!(f64, vals, 0.0, 0.0, device);

        // signed int: [-120, 100] and the degenerate [0, 0]
        assert_basic_case!(i8, vals, -120, 100, device);
        assert_basic_case!(i16, vals, -120, 100, device);
        assert_basic_case!(i32, vals, -120, 100, device);
        assert_basic_case!(i64, vals, -120, 100, device);
        assert_basic_case!(i32, vals, 0, 0, device);

        // unsigned int: [10, 100] and the degenerate [0, 0]
        assert_basic_case!(u8, vals, 10, 100, device);
        assert_basic_case!(u16, vals, 10, 100, device);
        assert_basic_case!(u32, vals, 10, 100, device);
        assert_basic_case!(u64, vals, 10, 100, device);
        assert_basic_case!(u32, vals, 0, 0, device);
    }

    #[test]
    fn test_int_out_of_range() {
        // numpy: v2.5.2 | _core/tests/test_multiarray.py::TestClip::test_int_out_of_range (L5818)
        crate::specify_test!("test_int_out_of_range");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x: Vec<u8> = (0..=255u16).step_by(3).map(|v| v as u8).collect();
        let x = rt::asarray((x.clone(), &device));

        // bounds that do not fit the uint8 dtype: rstsr promotes instead of wrapping (the
        // in-place `casting='unsafe'` path NumPy needs is not applicable here)
        assert_eq!(rt::clip(&x, (-1, 300)).to_vec(), x.to_vec().iter().map(|&v| v as i32).collect::<Vec<i32>>());
        assert_eq!(
            rt::clip(&x, (-1, 50)).to_vec(),
            x.to_vec().iter().map(|&v| (v as i32).min(50)).collect::<Vec<i32>>()
        );
        assert_eq!(
            rt::clip(&x, (100, 1000)).to_vec(),
            x.to_vec().iter().map(|&v| (v as i32).max(100)).collect::<Vec<i32>>()
        );
    }

    #[test]
    fn test_max_or_min() {
        // numpy: v2.5.2 | _core/tests/test_multiarray.py::TestClip::test_max_or_min (L5843)
        crate::specify_test!("test_max_or_min");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let val = rt::tensor_from_nested!([0, 1, 2, 3, 4, 5, 6, 7], &device);

        // min-only, max-only, and both
        assert_eq!(rt::clip(&val, (3, None)).to_vec(), vec![3, 3, 3, 3, 4, 5, 6, 7]);
        assert_eq!(rt::clip(&val, (None, 4)).to_vec(), vec![0, 1, 2, 3, 4, 4, 4, 4]);
        assert_eq!(rt::clip(&val, (3, 4)).to_vec(), vec![3, 3, 3, 3, 4, 4, 4, 4]);
    }

    #[test]
    fn test_nan() {
        // numpy: v2.5.2 | _core/tests/test_multiarray.py::TestClip::test_nan (L5852)
        crate::specify_test!("test_nan");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x = rt::asarray((vec![-2.0_f64, f64::NAN, 0.5, 3.0, 0.25, f64::NAN], &device));
        let r = rt::clip(&x, (-1.0_f64, 1.0_f64));
        let expected = [-1.0_f64, f64::NAN, 0.5, 1.0, 0.25, f64::NAN];
        let got: Vec<f64> = r.to_vec();
        for (g, e) in got.iter().zip(expected.iter()) {
            assert!(g == e || (g.is_nan() && e.is_nan()), "clip NaN mismatch: {g} vs {e}");
        }
    }
}

#[cfg(test)]
mod custom_clip {
    use super::*;
    static FUNC: &str = "custom_clip";

    #[test]
    fn test_method_form() {
        crate::specify_test!("test_method_form");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x = rt::tensor_from_nested!([-3, -1, 0, 2, 5], &device);
        let lo = rt::tensor_from_nested!([-2, -2, -2, -2, -2], &device);

        // method form mirrors the free function; view and owned receivers both work
        assert_eq!(x.clip((0, 3)).to_vec(), rt::clip(&x, (0, 3)).to_vec());
        assert_eq!(x.view().clip((&lo, 1)).to_vec(), vec![-2, -1, 0, 1, 1]);
        assert_eq!(rt::clip(&x, (lo.view(), 1)).to_vec(), vec![-2, -1, 0, 1, 1]);
    }

    #[test]
    fn test_tensor_bounds() {
        crate::specify_test!("test_tensor_bounds");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let x = rt::tensor_from_nested!([[-3, 2], [4, -5]], &device);
        let lo = rt::tensor_from_nested!([[-1, 0], [1, -1]], &device);
        let hi = rt::tensor_from_nested!([[0, 5], [3, 0]], &device);

        assert_eq!(rt::clip(&x, (&lo, &hi)).reshape([4]).to_vec(), vec![-1, 2, 3, -1]);
        // hi is a bound tensor, lo a scalar
        assert_eq!(rt::clip(&x, (0, &hi)).reshape([4]).to_vec(), vec![0, 2, 3, 0]);
    }

    #[test]
    fn test_promotion() {
        crate::specify_test!("test_promotion");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // f32 tensor + i64 scalar bound -> f64 (house-strong promotion)
        let x: Tensor<f32, _, _> = rt::tensor_from_nested!([[-3.0, 2.0], [4.0, -5.0]], &device);
        let r = rt::clip(&x, (-1_i64, 3_i64));
        assert_eq!(r.reshape([4]).to_vec(), vec![-1.0_f64, 2.0, 3.0, -1.0]);

        // absent hi borrows the tensor dtype, so the result stays f32
        let r = rt::clip(&x, (0.0_f32, None));
        assert_eq!(r.reshape([4]).to_vec(), vec![0.0_f32, 2.0, 4.0, 0.0]);
    }

    #[test]
    fn test_both_absent_identity() {
        crate::specify_test!("test_both_absent_identity");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // array-API: both bounds absent returns a copy of x (NumPy raises here)
        let x = rt::tensor_from_nested!([1, 2, 3], &device);
        assert_eq!(rt::clip(&x, (None, None)).to_vec(), vec![1, 2, 3]);
    }

    #[test]
    fn test_output_layout() {
        crate::specify_test!("test_output_layout");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // output memory order follows the shared elementwise-op policy: with all operands
        // f-contiguous, the result is f-contiguous, matching rt::maximum on the same inputs
        let x = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let lo = rt::tensor_from_nested!([[-1, -2, -3], [-4, -5, -6]], &device);
        let r = rt::clip(&x.t(), (&lo.t(), 4));
        assert_eq!(r.shape(), &[3, 2]);
        assert_eq!(r.stride(), &[1, 3]);
        let r_max = rt::maximum(&x.t(), &lo.t());
        assert_eq!(r_max.stride(), &[1, 3]);
    }
}
