// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy's add/subtract/multiply/divide/remainder tests (test_umath.py) are heavily
// dtype/casting/out=/FP-edge-case oriented and not cleanly transferable; these are
// `custom_*` value tests exercising elementwise binary arithmetic + broadcasting.

#[cfg(test)]
mod custom_add {
    use super::*;
    static FUNC: &str = "custom_add";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let b = rt::tensor_from_nested!([[10, 20], [30, 40]], &device);
        // np.add(a, b) == [[11, 22], [33, 44]]
        assert_equal(rt::add(&a, &b), rt::tensor_from_nested!([[11, 22], [33, 44]], &device), None);
        assert_equal(&(&a + &b), rt::tensor_from_nested!([[11, 22], [33, 44]], &device), None);
    }

    #[test]
    fn test_broadcast() {
        crate::specify_test!("test_broadcast");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a (2,3) + b (3,) broadcasts the row across both rows.
        let a = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        let b = rt::tensor_from_nested!([10, 20, 30], &device);
        assert_equal(rt::add(&a, &b), rt::tensor_from_nested!([[11, 22, 33], [14, 25, 36]], &device), None);
    }
}

#[cfg(test)]
mod custom_sub {
    use super::*;
    static FUNC: &str = "custom_sub";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[10, 20], [30, 40]], &device);
        let b = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        assert_equal(rt::sub(&a, &b), rt::tensor_from_nested!([[9, 18], [27, 36]], &device), None);
        assert_equal(&(&a - &b), rt::tensor_from_nested!([[9, 18], [27, 36]], &device), None);
    }
}

#[cfg(test)]
mod custom_mul {
    use super::*;
    static FUNC: &str = "custom_mul";

    #[test]
    fn test_elementwise_broadcast() {
        crate::specify_test!("test_elementwise_broadcast");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let b = rt::tensor_from_nested!([10, 100], &device);
        // np.multiply(a, b) broadcasts (2,2)*(2,) -> [[10,200],[30,400]]
        assert_equal(rt::mul(&a, &b), rt::tensor_from_nested!([[10, 200], [30, 400]], &device), None);
        assert_equal(&(&a * &b), rt::tensor_from_nested!([[10, 200], [30, 400]], &device), None);
    }
}

#[cfg(test)]
mod custom_div {
    use super::*;
    static FUNC: &str = "custom_div";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // float division (numpy true_divide semantics); use f64 to avoid integer
        // truncation ambiguity.
        let a = rt::tensor_from_nested!([[10.0, 20.0], [30.0, 40.0]], &device);
        let b = rt::tensor_from_nested!([[2.0, 4.0], [5.0, 8.0]], &device);
        assert_equal(rt::div(&a, &b), rt::tensor_from_nested!([[5.0, 5.0], [6.0, 5.0]], &device), None);
        assert_equal(&(&a / &b), rt::tensor_from_nested!([[5.0, 5.0], [6.0, 5.0]], &device), None);
    }
}

#[cfg(test)]
mod custom_rem {
    use super::*;
    static FUNC: &str = "custom_rem";

    #[test]
    fn test_elementwise() {
        crate::specify_test!("test_elementwise");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.remainder(a, b)
        let a = rt::tensor_from_nested!([[10, 21], [33, 44]], &device);
        let b = rt::tensor_from_nested!([[3, 4], [5, 7]], &device);
        // rt::rem is the NumPy-compatible elementwise remainder.
        assert_equal(rt::rem(&a, &b), rt::tensor_from_nested!([[1, 1], [3, 2]], &device), None);
        // RSTSR's `%` (Rem) operator is intentionally matrix multiplication, not
        // remainder (the elementwise rem binding is commented out so the matmul Rem
        // impl in linalg/matmul.rs applies). a % b == a.matmul(b) == [[135, 187], [319, 440]].
        assert_equal(&a % &b, rt::tensor_from_nested!([[135, 187], [319, 440]], &device), None);
    }

    // `assert_equal` goes through `allclose`, which conflates `+0.0`/`-0.0`, so the
    // float remainder special cases are checked on the bit pattern.
    fn bits(v: &[f64]) -> Vec<u64> {
        v.iter().map(|x| x.to_bits()).collect()
    }

    #[test]
    fn test_float_floored_and_special() {
        crate::specify_test!("test_float_floored_and_special");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // Floored (sign-of-divisor) remainder for finite operands.
        // np.remainder([-7, 7, -7, 7], [3, -3, -3, 3]) == [2, -2, -1, 1]
        let a = rt::tensor_from_nested!([-7.0, 7.0, -7.0, 7.0], &device);
        let b = rt::tensor_from_nested!([3.0, -3.0, -3.0, 3.0], &device);
        assert_eq!(bits(&rt::rem(&a, &b).to_vec()), bits(&[2.0, -2.0, -1.0, 1.0]));

        // Array-API special cases: signed zero and opposite-sign infinite divisor.
        // np.remainder([-0.0, 0.0, -1.0, 1.0], [2.0, -2.0, inf, -inf]) == [+0, -0, inf, -inf]
        let z = rt::tensor_from_nested!([-0.0, 0.0, -1.0, 1.0], &device);
        let d = rt::tensor_from_nested!([2.0, -2.0, f64::INFINITY, f64::NEG_INFINITY], &device);
        assert_eq!(bits(&rt::rem(&z, &d).to_vec()), bits(&[0.0, -0.0, f64::INFINITY, f64::NEG_INFINITY]));

        // Same-sign infinite divisor keeps the dividend.
        // np.remainder([1.0, -1.0], [inf, -inf]) == [1.0, -1.0]
        let s = rt::tensor_from_nested!([1.0, -1.0], &device);
        let di = rt::tensor_from_nested!([f64::INFINITY, f64::NEG_INFINITY], &device);
        assert_eq!(bits(&rt::rem(&s, &di).to_vec()), bits(&[1.0, -1.0]));

        // Exact multiple carries the divisor's sign: np.remainder(4.0, -2.0) == -0.0
        let m = rt::tensor_from_nested!([4.0], &device);
        let n = rt::tensor_from_nested!([-2.0], &device);
        assert_eq!(bits(&rt::rem(&m, &n).to_vec()), bits(&[-0.0]));
    }
}
