// Most or all contents generated by AI (model glm-5.2); slice twins rewritten
// (model glm-5.3[1m], 2026-10-06).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_indexing {
    use super::*;
    static FUNC: &str = "doc_indexing";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let m = rt::arange((12, &device)).into_shape([3, 4]);
        println!("{}", m.i(1));
        // [ 4 5 6 7]
        println!("{}", m.i((.., slice!(1, 3))));
        // [[ 1 2]
        //  [ 5 6]
        //  [ 9 10]]
        println!("{:?}", m.i((.., None)).shape());
        // [3, 1, 4]
        let v = rt::arange((6, &device));
        println!("{:?}", rt::index_select(&v, 0, [1, 3, 5]));
        // [1, 3, 5]
        crate::test_utils::assert_equal(m.i(1), rt::tensor_from_nested!([4, 5, 6, 7], &device), None);
        crate::test_utils::assert_equal(
            m.i((.., slice!(1, 3))),
            rt::tensor_from_nested!([[1, 2], [5, 6], [9, 10]], &device),
            None,
        );
        assert_eq!(m.i((.., None)).shape(), &[3, 1, 4]);
        crate::test_utils::assert_equal(
            rt::index_select(&v, 0, [1, 3, 5]),
            rt::tensor_from_nested!([1, 3, 5], &device),
            None,
        );
    }
}

mod doc_slice {
    use super::*;
    static FUNC: &str = "doc_slice";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a 1-D tensor and the three most common indexers
        let a = rt::arange((10, &device));
        println!("{}", a.i(1..4));
        // [ 1 2 3]
        assert_eq!(format!("{}", a.i(1..4)), "[ 1 2 3]");

        // a 1-tuple indexes the first axis as well
        println!("{}", a.i((1..4,)));
        // [ 1 2 3]
        assert_eq!(format!("{}", a.i((1..4,))), "[ 1 2 3]");

        println!("{}", a.i(2));
        // 2
        println!("{:?}", a.i(2).shape());
        // []
        assert_eq!(a.i(2).shape(), &[] as &[usize]);

        println!("{}", a.i(-3..));
        // [ 7 8 9]
        assert_eq!(format!("{}", a.i(-3..)), "[ 7 8 9]");

        // a 2-D tensor: one indexer per axis, written as a tuple
        let m = rt::arange((12, &device)).into_shape([3, 4]);
        println!("{}", m.i(1));
        // [ 4 5 6 7]
        assert_eq!(format!("{}", m.i(1)), "[ 4 5 6 7]");

        println!("{}", m.i((.., 1..3)));
        // [[ 1 2]
        //  [ 5 6]
        //  [ 9 10]]
        assert_eq!(format!("{}", m.i((.., 1..3))), "[[ 1 2]\n [ 5 6]\n [ 9 10]]");

        println!("{}", m.i((1..3, ..)));
        // [[ 4 5 6 7]
        //  [ 8 9 10 11]]
        assert_eq!(format!("{}", m.i((1..3, ..))), "[[ 4 5 6 7]\n [ 8 9 10 11]]");

        // the four indexer forms used in the introduction example of the doc
        let second_row = m.i(1);
        let top_right = m.i((0..2, 2..4));
        let last_column = m.i((Ellipsis, -1));
        let expanded = m.i((.., None));
        println!("{}", last_column);
        // [ 3 7 11]
        assert_eq!(second_row.to_vec(), vec![4, 5, 6, 7]);
        assert_eq!(top_right.shape(), &[2, 2]);
        assert_eq!(format!("{}", last_column), "[ 3 7 11]");
        assert_eq!(expanded.shape(), &[3, 1, 4]);

        // None inserts a new axis of size one
        println!("{:?}", m.i((.., None)).shape());
        // [3, 1, 4]
        assert_eq!(m.i((.., None)).shape(), &[3, 1, 4]);

        // stepped ranges use the slice! macro (any bound can be None)
        println!("{}", a.i(slice!(2, 7, 2)));
        // [ 2 4 6]
        assert_eq!(format!("{}", a.i(slice!(2, 7, 2))), "[ 2 4 6]");

        // new axes line two tensors up for broadcasting (outer sum)
        let v = rt::arange((5, &device));
        let outer = &v.i((.., None)) + &v.i((None, ..));
        println!("{}", outer);
        // [[ 0 1 2 3 4]
        //  [ 1 2 3 4 5]
        //  [ 2 3 4 5 6]
        //  [ 3 4 5 6 7]
        //  [ 4 5 6 7 8]]
        assert_eq!(outer.shape(), &[5, 5]);
        crate::test_utils::assert_equal(
            &outer,
            &rt::tensor_from_nested!(
                [[0, 1, 2, 3, 4], [1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4, 5, 6, 7, 8]],
                &device
            ),
            None,
        );

        println!("{}", m.i((.., slice!(None, None, 2))));
        // [[ 0 2]
        //  [ 4 6]
        //  [ 8 10]]
        assert_eq!(format!("{}", m.i((.., slice!(None, None, 2)))), "[[ 0 2]\n [ 4 6]\n [ 8 10]]");
    }
}

mod doc_slice_nd {
    use super::*;
    static FUNC: &str = "doc_slice_nd";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let b = rt::arange((24, &device)).into_shape([2, 3, 4]);
        println!("{}", b.i((1..2, 1..3, 1..4)));
        // [[[ 17 18 19]
        //   [ 21 22 23]]]
        assert_eq!(format!("{}", b.i((1..2, 1..3, 1..4))), "[[[ 17 18 19]\n  [ 21 22 23]]]");

        // integer selects one position and drops the axis
        println!("{}", b.i(1));
        // [[ 12 13 14 15]
        //  [ 16 17 18 19]
        //  [ 20 21 22 23]]
        assert_eq!(format!("{}", b.i(1)), "[[ 12 13 14 15]\n [ 16 17 18 19]\n [ 20 21 22 23]]");

        // a tuple of integers selects down to a 0-dim view
        println!("{}", b.i((1, 2, 3)));
        // 23
        assert_eq!(b.i((1, 2, 3)).to_scalar(), 23);

        // scalar access by the [] operator (boundary-checked)
        println!("{}", b[[1, 2, 3]]);
        // 23
        assert_eq!(b[[1, 2, 3]], 23);

        // mutable slice, written in place
        let mut a: Tensor<i32, _> = rt::arange((5, &device));
        let mut v = a.i_mut(1..4);
        v += 10;
        println!("{a}");
        // [ 0 11 12 13 4]
        assert_eq!(format!("{a}"), "[ 0 11 12 13 4]");
    }
}

mod doc_slice_indexers {
    use super::*;
    static FUNC: &str = "doc_slice_indexers";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((10, &device));
        let m = rt::arange((12, &device)).into_shape([3, 4]);

        // every range type works: a..b, a.., ..b, ..
        println!("{}", a.i(2..8));
        // [ 2 3 4 5 6 7]
        assert_eq!(format!("{}", a.i(2..8)), "[ 2 3 4 5 6 7]");
        println!("{}", a.i(2..));
        // [ 2 3 4 5 6 7 8 9]
        assert_eq!(format!("{}", a.i(2..)), "[ 2 3 4 5 6 7 8 9]");
        println!("{}", a.i(..3));
        // [ 0 1 2]
        assert_eq!(format!("{}", a.i(..3)), "[ 0 1 2]");
        println!("{}", a.i(..));
        // [ 0 1 2 ... 7 8 9]
        // (display of long tensors is truncated with an ellipsis)
        assert_eq!(format!("{}", a.i(..)), "[ 0 1 2 ... 7 8 9]");

        // a range keeps the axis (length 1), an integer drops it
        println!("{:?}", m.i(1..2).shape());
        // [1, 4]
        assert_eq!(m.i(1..2).shape(), &[1, 4]);
        println!("{:?}", m.i(1).shape());
        // [4]
        assert_eq!(m.i(1).shape(), &[4]);

        // NumPy x[1:7:2] == [1, 3, 5]
        println!("{}", a.i(slice!(1, 7, 2)));
        // [ 1 3 5]
        assert_eq!(format!("{}", a.i(slice!(1, 7, 2))), "[ 1 3 5]");

        // negative integers count from the back of the axis
        println!("{}", m.i((-1, ..)));
        // [ 8 9 10 11]
        assert_eq!(format!("{}", m.i((-1, ..))), "[ 8 9 10 11]");

        // reversed axis: negative step
        println!("{}", a.i(slice!(None, None, -1)));
        // [ 9 8 7 ... 2 1 0]
        assert_eq!(format!("{}", a.i(slice!(None, None, -1))), "[ 9 8 7 ... 2 1 0]");
        println!("{}", a.i(slice!(-1, None, -2)));
        // [ 9 7 5 3 1]
        assert_eq!(format!("{}", a.i(slice!(-1, None, -2))), "[ 9 7 5 3 1]");

        // out-of-bound range ends are clamped (as in Python); empty results are fine
        println!("{}", a.i(7..20));
        // [ 7 8 9]
        assert_eq!(format!("{}", a.i(7..20)), "[ 7 8 9]");
        println!("{:?}", a.i(3..3).size());
        // 0
        assert_eq!(a.i(3..3).size(), 0);

        // None as a single indexer also works: inserts an axis at the front
        println!("{:?}", a.i(None).shape());
        // [1, 10]
        assert_eq!(a.i(None).shape(), &[1, 10]);

        // Ellipsis expands to as many full ranges as needed
        let b = rt::arange((24, &device)).into_shape([2, 3, 4]);
        println!("{:?}", b.i((Ellipsis, 2)).shape());
        // [2, 3]
        assert_eq!(b.i((Ellipsis, 2)).shape(), &[2, 3]);
        println!("{:?}", b.i((1, Ellipsis)).shape());
        // [3, 4]
        assert_eq!(b.i((1, Ellipsis)).shape(), &[3, 4]);

        // NewAxis is the named form of None; indexers can be mixed freely in
        // tuples. The new axis lands as in NumPy: x[1, None, :] -> (1, 3, 4)
        println!("{:?}", b.i((1, NewAxis, ..)).shape());
        // [1, 3, 4]
        assert_eq!(b.i((1, NewAxis, ..)).shape(), &[1, 3, 4]);
        println!("{:?}", b.i((None, 1)).shape());
        // [1, 3, 4]
        assert_eq!(b.i((None, 1)).shape(), &[1, 3, 4]);
        println!("{:?}", b.i((1, None, Ellipsis, 2)).shape());
        // [1, 3]
        assert_eq!(b.i((1, None, Ellipsis, 2)).shape(), &[1, 3]);
    }
}

mod doc_slice_views {
    use super::*;
    static FUNC: &str = "doc_slice_views";

    #[test]
    // *&mut view.i_mut(..) += rhs is the documented place-expression idiom
    #[allow(clippy::deref_addrof)]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // slicing is layout-only: shape/stride/offset change, no data is touched
        let m = rt::arange((12, &device)).into_shape([3, 4]);
        let s = m.i((.., 1..3));
        assert_eq!(s.shape(), &[3, 2]);
        assert_eq!(s.stride(), &[4, 1]);
        assert_eq!(s.offset(), 1);

        // the Debug format shows the layout: shape, stride, offset
        println!("{:?}", m.i((.., 2)));
        println!("{:?}", m.i((.., slice!(None, None, 2))));

        // views of views: each step is another view on the same data
        // (intermediate views must be bound to a variable, see the docstring)
        let b = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let v = b.i((1, ..));
        let c = v.i((.., 1..3));
        println!("{}", c);
        // [[13 14]
        //  [17 18]
        //  [21 22]]
        assert_eq!(format!("{}", c), "[[ 13 14]\n [ 17 18]\n [ 21 22]]");

        // preferred: the same view in one combined tuple indexer
        let c2 = b.i((1, .., 1..3));
        assert_eq!(format!("{}", c2), format!("{}", c));

        // a strided view is not contiguous; use to_contig when an algorithm needs that
        let s = b.i((.., .., slice!(None, None, 2)));
        assert!(!s.c_contig());
        let t = s.to_contig(RowMajor);
        assert!(t.c_contig());
        assert_eq!(t.shape(), &[2, 3, 2]);

        // on the same logical tensor stored column-major, i() returns the same values
        let m_f = m.to_contig(ColMajor);
        assert!(m_f.f_contig());
        assert_eq!(format!("{}", m_f.i((.., 1..3))), "[[ 1 2]\n [ 5 6]\n [ 9 10]]");

        // a view shares data: writing through i_mut is visible in the parent
        let mut a: Tensor<i32, _> = rt::arange((6, &device)).into_shape([2, 3]);
        *&mut a.i_mut((1, ..)) += 10;
        println!("{a}");
        // [[ 0 1 2]
        //  [ 13 14 15]]
        assert_eq!(format!("{a}"), "[[ 0 1 2]\n [ 13 14 15]]");

        // into_slice consumes the tensor and returns the same ownership kind
        let d = rt::arange((6, &device));
        let d0 = d.into_slice(1..3);
        println!("{}", d0);
        // [ 1 2]
        assert_eq!(format!("{}", d0), "[ 1 2]");
    }
}

mod doc_slice_dynamic {
    use super::*;
    static FUNC: &str = "doc_slice_dynamic";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let m = rt::arange((12, &device)).into_shape([3, 4]);

        // runtime values work directly in tuples (mixed integer types are fine)
        let i: usize = 2;
        let j: usize = 0;
        println!("{}", m.i((i, j)));
        // 8
        assert_eq!(m.i((i, j)).to_scalar(), 8);

        // the s! macro accepts runtime values as well
        let p: usize = 1;
        let q: isize = -2;
        println!("{}", m.i(s![p, q]));
        // 6
        assert_eq!(m.i(s![p, q]).to_scalar(), 6);

        // when the number of indexers is itself only known at runtime (tuple
        // arities are fixed 2..10), an owned Vec of one integer type works
        let b = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let idx: Vec<isize> = vec![1, -1, 2];
        println!("{}", b.i(idx.clone()));
        // 22
        assert_eq!(b.i(idx).to_scalar(), 22);
    }
}

mod doc_diagonal {
    use super::*;
    static FUNC: &str = "doc_diagonal";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((9, &device)).into_shape([3, 3]);
        println!("{}", a.diagonal(()));
        // [ 0 4 8]
        assert_eq!(format!("{}", a.diagonal(())), "[ 0 4 8]");
        println!("{}", a.diagonal(1));
        // [ 1 5]
        assert_eq!(format!("{}", a.diagonal(1)), "[ 1 5]");

        // 3-D: diagonal over axes (0, 1), one remaining axis
        let b = rt::arange((24, &device)).into_shape([2, 3, 4]);
        let d = b.diagonal((0, 0, 1));
        println!("{}", d);
        println!("{:?}", d.shape());
        assert_eq!(d.shape(), &[4, 2]);

        // mutable diagonal, written in place
        let mut c: Tensor<i32, _> = rt::zeros(([3, 3], &device));
        let mut d = c.diagonal_mut(());
        d += 2;
        println!("{c}");
        // [[ 2 0 0]
        //  [ 0 2 0]
        //  [ 0 0 2]]
        assert_eq!(format!("{c}"), "[[ 2 0 0]\n [ 0 2 0]\n [ 0 0 2]]");

        // the same logical tensor stored F-contiguously: diagonal views and
        // diagonal_mut writes are unchanged
        let a_f = a.to_contig(ColMajor);
        assert!(a_f.f_contig());
        println!("{}", a_f.diagonal(()));
        assert_eq!(format!("{}", a_f.diagonal(())), "[ 0 4 8]");
        assert_eq!(format!("{}", a_f.diagonal(1)), "[ 1 5]");

        // on a ColMajor-default device, zeros are F-contiguous; diagonal_mut
        // writes through identically
        let mut device_c = TESTCFG.device.clone();
        device_c.set_default_order(ColMajor);
        let mut c_c: Tensor<i32, _> = rt::zeros(([3, 3], &device_c));
        assert!(c_c.f_contig());
        let mut d_c = c_c.diagonal_mut(());
        d_c += 2;
        assert_eq!(format!("{c_c}"), "[[ 2 0 0]\n [ 0 2 0]\n [ 0 0 2]]");
    }
}

mod doc_adv_indexing {
    use super::*;
    static FUNC: &str = "doc_adv_indexing";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        let a = rt::arange((12, &device)).into_shape([3, 4]);

        println!("{}", rt::index_select(&a, 0, [0, 2]));
        // [[ 0 1 2 3]
        //  [ 8 9 10 11]]
        assert_eq!(format!("{}", rt::index_select(&a, 0, [0, 2])), "[[ 0 1 2 3]\n [ 8 9 10 11]]");

        println!("{}", rt::index_select(&a, 1, vec![3, 1]));
        // [[ 3 1]
        //  [ 7 5]
        //  [ 11 9]]
        assert_eq!(format!("{}", rt::index_select(&a, 1, vec![3, 1])), "[[ 3 1]\n [ 7 5]\n [ 11 9]]");

        // negative indices count from the back
        println!("{}", rt::index_select(&a, 0, [-1]));
        // [[ 8 9 10 11]]
        assert_eq!(format!("{}", rt::index_select(&a, 0, [-1])), "[[ 8 9 10 11]]");

        // take: same operation as index_select, NumPy argument order
        println!("{}", rt::take(&a, [0, 2], 0));
        // [[ 0 1 2 3]
        //  [ 8 9 10 11]]
        assert_eq!(format!("{}", rt::take(&a, [0, 2], 0)), "[[ 0 1 2 3]\n [ 8 9 10 11]]");

        // bool_select: mask of the same length as the axis
        println!("{}", rt::bool_select(&a, 1, [true, false, true, false]));
        // [[ 0 2]
        //  [ 4 6]
        //  [ 8 10]]
        assert_eq!(format!("{}", rt::bool_select(&a, 1, [true, false, true, false])), "[[ 0 2]\n [ 4 6]\n [ 8 10]]");
    }
}
