// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_cumulative_sum {
    use super::*;
    static FUNC: &str = "doc_cumulative_sum";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // 1-D default args scan along the only axis
        let a = rt::tensor_from_nested!([1, 2, 3, 4], &device);
        println!("{}", rt::cumulative_sum(&a, ()));
        assert_eq!(format!("{}", rt::cumulative_sum(&a, ())), "[ 1 3 6 10]");
        // include the initial value 0
        println!("{}", rt::cumulative_sum(&a, true));
        assert_eq!(format!("{}", rt::cumulative_sum(&a, true)), "[ 0 1 3 6 10]");

        // 2-D requires an explicit axis
        let b = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        println!("{}", rt::cumulative_sum(&b, 1));
        assert_eq!(format!("{}", rt::cumulative_sum(&b, 1)), "[[ 1 3 6]\n [ 4 9 15]]");
        // accumulate in f64 to avoid overflow of narrow integer dtypes
        println!("{}", b.cumulative_sum_with_dtype::<f64>(0));
        assert_eq!(format!("{}", b.cumulative_sum_with_dtype::<f64>(0)), "[[ 1 2 3]\n [ 5 7 9]]");
    }
}

mod doc_cumulative_prod {
    use super::*;
    static FUNC: &str = "doc_cumulative_prod";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // 1-D default args scan along the only axis
        let a = rt::tensor_from_nested!([1, 2, 3, 4], &device);
        println!("{}", rt::cumulative_prod(&a, ()));
        assert_eq!(format!("{}", rt::cumulative_prod(&a, ())), "[ 1 2 6 24]");
        // include the initial value 1
        println!("{}", rt::cumulative_prod(&a, true));
        assert_eq!(format!("{}", rt::cumulative_prod(&a, true)), "[ 1 1 2 6 24]");

        // 2-D requires an explicit axis
        let b = rt::tensor_from_nested!([[1, 2, 3], [4, 5, 6]], &device);
        println!("{}", rt::cumulative_prod(&b, -1));
        assert_eq!(format!("{}", rt::cumulative_prod(&b, -1)), "[[ 1 2 6]\n [ 4 20 120]]");
        // accumulate in f64 to avoid overflow of narrow integer dtypes
        println!("{}", b.cumulative_prod_with_dtype::<f64>(0));
        assert_eq!(format!("{}", b.cumulative_prod_with_dtype::<f64>(0)), "[[ 1 2 3]\n [ 4 10 18]]");
    }
}
