// Most or all contents generated by AI (model glm-5.3).
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

mod doc_reduce_all {
    use super::*;
    static FUNC: &str = "doc_reduce_all";

    #[test]
    fn test_doc() {
        crate::specify_test!("test_doc");
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // the 3-norm of a vector, spelled with the fold machinery
        let v = rt::tensor_from_nested!([1.0, 2.0, 2.0], &device);
        let p3 = rt::reduce_all(&v, || 0.0_f64, |acc, x| acc + x * x * x, |acc1, acc2| acc1 + acc2, |acc| acc.cbrt());
        println!("{p3}");
        assert_eq!(p3, 2.571281590658235);
    }
}
