// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

#[cfg(test)]
mod numpy_matmul {
    use super::*;
    static FUNC: &str = "numpy_matmul";

    #[test]
    fn test_vector_vector_values() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, MatmulCommon::test_vector_vector_values
        // (line 7869) NumPy iterates dtypes + a bool case; rstsr transfers the i32 value
        // cases.
        crate::specify_test!("test_vector_vector_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // vec1 = [1, 2]; vec2 = [[3], [4]]
        // matmul(vec1, vec2) == [11]   ((2,) @ (2,1) -> (1,))
        let v1 = rt::tensor_from_nested!([1, 2], &device);
        let v2 = rt::tensor_from_nested!([[3], [4]], &device);
        assert_equal(rt::matmul(&v1, &v2), rt::tensor_from_nested!([11], &device), None);

        // matmul(vec2, vec1.reshape(1,-1)) == [[3, 6], [4, 8]]  ((2,1) @ (1,2) -> (2,2))
        let v1r = rt::tensor_from_nested!([[1, 2]], &device);
        assert_equal(rt::matmul(&v2, &v1r), rt::tensor_from_nested!([[3, 6], [4, 8]], &device), None);
    }

    #[test]
    fn test_vector_matrix_values() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, MatmulCommon::test_vector_matrix_values
        // (line 7888)
        crate::specify_test!("test_vector_matrix_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // vec = [1, 2]; mat1 = [[1, 2], [3, 4]]
        // matmul(vec, mat1) == [7, 10]
        let v = rt::tensor_from_nested!([1, 2], &device);
        let m1 = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        assert_equal(rt::matmul(&v, &m1), rt::tensor_from_nested!([7, 10], &device), None);
    }

    #[test]
    fn test_matrix_vector_values() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, MatmulCommon::test_matrix_vector_values
        // (line 7915)
        crate::specify_test!("test_matrix_vector_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // mat1 = [[1, 2], [3, 4]]; vec = [1, 2]
        // matmul(mat1, vec) == [5, 11]
        let m1 = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let v = rt::tensor_from_nested!([1, 2], &device);
        assert_equal(rt::matmul(&m1, &v), rt::tensor_from_nested!([5, 11], &device), None);
    }

    #[test]
    fn test_matrix_matrix_values() {
        // NumPy v2.5.2, _core/tests/test_multiarray.py, MatmulCommon::test_matrix_matrix_values
        // (line 7942)
        crate::specify_test!("test_matrix_matrix_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // m1 = [[1, 2], [3, 4]]; m2 = [[1, 0], [1, 1]]
        let m1 = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let m2 = rt::tensor_from_nested!([[1, 0], [1, 1]], &device);

        // matmul(m1, m2) == [[3, 2], [7, 4]]
        assert_equal(rt::matmul(&m1, &m2), rt::tensor_from_nested!([[3, 2], [7, 4]], &device), None);
        // matmul(m2, m1) == [[1, 2], [4, 6]]
        assert_equal(rt::matmul(&m2, &m1), rt::tensor_from_nested!([[1, 2], [4, 6]], &device), None);
    }
}

#[cfg(test)]
mod custom_matmul {
    use super::*;
    static FUNC: &str = "custom_matmul";

    #[test]
    fn test_batched_matmul() {
        crate::specify_test!("test_batched_matmul");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // stacked (batched) matmul: (2,2,2) @ (2,2) broadcasts over the leading axis.
        // m12 = [[[1,2],[3,4]], [[1,0],[1,1]]]; matmul(m12, m1) per-slice.
        let m1 = rt::tensor_from_nested!([[1, 2], [3, 4]], &device);
        let m12 = rt::tensor_from_nested!([[[1, 2], [3, 4]], [[1, 0], [1, 1]]], &device);
        // matmul(m12, m1) -> stack([matmul(m1,m1), matmul(m2,m1)])
        //   matmul(m1,m1) = [[7,10],[15,22]]; matmul(m2,m1) = [[1,2],[4,6]]
        let res = rt::matmul(&m12, &m1);
        let expected = rt::tensor_from_nested!([[[7, 10], [15, 22]], [[1, 2], [4, 6]]], &device);
        assert_equal(&res, &expected, None);
    }
}
