// Most or all contents generated by AI (model glm-5.2).
#[allow(unused_imports)]
use crate::test_utils::*;
use rstsr::prelude::*;

use super::CATEGORY;
use crate::TESTCFG;

// NumPy's unary-ufunc tests (test_umath.py::TestSpecialFloats / TestExp / TestLog /
// TestRoundingFunctions / TestSign / TestFPClass) are FP-special-value and dtype
// oriented. These `custom_*` tests cover representative value parity for the main
// unary math functions (they share the same elementwise map code path).

#[cfg(test)]
mod custom_math_basic {
    use super::*;
    static FUNC: &str = "custom_math_basic";

    #[test]
    fn test_abs_sqrt_sign_rounding() {
        crate::specify_test!("test_abs_sqrt_sign_rounding");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.abs([-1, 2, -3]) == [1, 2, 3]
        let a = rt::tensor_from_nested!([-1, 2, -3], &device);
        assert_equal(rt::abs(&a), rt::tensor_from_nested!([1, 2, 3], &device), None);

        // np.sqrt([0, 1, 4, 9]) == [0, 1, 2, 3]
        let s = rt::tensor_from_nested!([0.0, 1.0, 4.0, 9.0], &device);
        assert_equal(rt::sqrt(&s), rt::tensor_from_nested!([0.0, 1.0, 2.0, 3.0], &device), None);

        // np.sign([-2, 0, 3]) == [-1, 0, 1]; sign accepts any ExtNum dtype (floats and integers).
        let g = rt::tensor_from_nested!([-2.0, 0.0, 3.0], &device);
        assert_equal(rt::sign(&g), rt::tensor_from_nested!([-1.0, 0.0, 1.0], &device), None);

        // np.sign(np.array([-2, 0, 3])) == array([-1, 0, 1]); integer dtypes stay integers
        let gi = rt::tensor_from_nested!([-2, 0, 3], &device);
        assert_eq!(rt::sign(&gi).to_vec(), vec![-1, 0, 1]);

        // np.sign(np.array([0, 5], dtype=np.uint8)) == array([0, 1], dtype=uint8)
        let gu: Tensor<u8, _> = rt::tensor_from_nested!([0, 5], &device);
        assert_eq!(rt::sign(&gu).to_vec(), vec![0u8, 1u8]);

        // np.floor / np.ceil / np.trunc on [-1.5, 0.5, 2.4]
        let f = rt::tensor_from_nested!([-1.5, 0.5, 2.4], &device);
        assert_equal(rt::floor(&f), rt::tensor_from_nested!([-2.0, 0.0, 2.0], &device), None);
        assert_equal(rt::ceil(&f), rt::tensor_from_nested!([-1.0, 1.0, 3.0], &device), None);
        assert_equal(rt::trunc(&f), rt::tensor_from_nested!([-1.0, 0.0, 2.0], &device), None);
    }

    #[test]
    fn test_sign_special_values() {
        crate::specify_test!("test_sign_special_values");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.sign([nan, inf, -inf, -0.0, 0.0]) == [nan, 1.0, -1.0, 0.0, 0.0];
        // infinities map to ±1.0, and both signed zeros map to +0.0.
        let a: Tensor<f64, _> = rt::asarray((vec![f64::NAN, f64::INFINITY, f64::NEG_INFINITY, -0.0, 0.0], &device));
        let s = rt::sign(&a).to_vec();
        assert!(s[0].is_nan());
        assert_eq!(s[1], 1.0);
        assert_eq!(s[2], -1.0);
        assert_eq!(s[3], 0.0);
        assert!(!s[3].is_sign_negative());
        assert_eq!(s[4], 0.0);
    }

    #[test]
    fn test_round_ties_to_even() {
        crate::specify_test!("test_round_ties_to_even");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // np.round([2.5, 3.5, -2.5, -3.5]) == [2.0, 4.0, -2.0, -4.0]:
        // halfway cases resolve to the even neighbor (array-api `round`,
        // "the even integer closest to x_i"), not Rust's ties-away `round`.
        let a = rt::tensor_from_nested!([2.5, 3.5, -2.5, -3.5], &device);
        assert_equal(rt::round(&a), rt::tensor_from_nested!([2.0, 4.0, -2.0, -4.0], &device), None);

        // np.round(-0.5) == -0.0 (IEEE roundToIntegralTiesToEven keeps the sign).
        let z = rt::round(&rt::tensor_from_nested!([-0.5], &device));
        assert_eq!(z.to_vec(), vec![-0.0]);

        // non-ties round to nearest; NaN/inf propagate.
        let b: Tensor<f64, _> = rt::asarray((vec![0.4, 2.6, f64::NAN, f64::INFINITY], &device));
        let r = rt::round(&b).to_vec();
        assert_eq!(r[0], 0.0);
        assert_eq!(r[1], 3.0);
        assert!(r[2].is_nan());
        assert!(r[3].is_infinite());
    }
}

#[cfg(test)]
mod custom_math_transcendental {
    use super::*;
    static FUNC: &str = "custom_math_transcendental";

    #[test]
    fn test_exp_log_trig() {
        crate::specify_test!("test_exp_log_trig");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);
        use std::f64::consts::PI;

        // exp([0, 1, 2]) == [1, e, e^2]; log is its inverse.
        let x = rt::tensor_from_nested!([0.0, 1.0, 2.0], &device);
        let ex = rt::exp(&x);
        assert_equal(
            &ex,
            rt::tensor_from_nested!([1.0, std::f64::consts::E, std::f64::consts::E * std::f64::consts::E], &device),
            None,
        );
        // log(exp(x)) == x
        assert_equal(rt::log(&ex), &x, None);

        // sin / cos at 0, pi/2, pi
        let ang = rt::tensor_from_nested!([0.0, PI / 2.0, PI], &device);
        assert_equal(rt::sin(&ang), rt::tensor_from_nested!([0.0, 1.0, 0.0], &device), None);
        assert_equal(rt::cos(&ang), rt::tensor_from_nested!([1.0, 0.0, -1.0], &device), None);

        // tanh([-1, 0, 1]) == [-tanh(1), 0, tanh(1)]
        let t = rt::tensor_from_nested!([-1.0, 0.0, 1.0], &device);
        let th1 = 1.0_f64.tanh();
        assert_equal(rt::tanh(&t), rt::tensor_from_nested!([-th1, 0.0, th1], &device), None);
    }

    #[test]
    fn test_log1p_expm1() {
        crate::specify_test!("test_log1p_expm1");

        use num::Complex;
        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // Near zero, `ln(1 + x)` collapses to 0; log1p must return ~x.
        let tiny = rt::tensor_from_nested!([1e-20_f64, -1e-20], &device);
        let lp = rt::log1p(&tiny).to_vec();
        assert!((lp[0] - 1e-20).abs() < 1e-36, "log1p(1e-20) = {:e}", lp[0]);
        assert!((lp[1] + 1e-20).abs() < 1e-36, "log1p(-1e-20) = {:e}", lp[1]);

        // log1p special values: -1 -> -inf, 0 -> 0, +inf -> +inf, x < -1 -> NaN.
        let sp: Tensor<f64, _> = rt::asarray((vec![-1.0, 0.0, f64::INFINITY, -2.0], &device));
        let ls = rt::log1p(&sp).to_vec();
        assert_eq!(ls[0], f64::NEG_INFINITY);
        assert_eq!(ls[1], 0.0);
        assert_eq!(ls[2], f64::INFINITY);
        assert!(ls[3].is_nan());

        // expm1 near zero, and the real special cases.
        let em = rt::expm1(&tiny).to_vec();
        assert!((em[0] - 1e-20).abs() < 1e-36, "expm1(1e-20) = {:e}", em[0]);
        assert!((em[1] + 1e-20).abs() < 1e-36, "expm1(-1e-20) = {:e}", em[1]);
        let ei: Tensor<f64, _> = rt::asarray((vec![f64::NEG_INFINITY, 0.0, f64::INFINITY], &device));
        let es = rt::expm1(&ei).to_vec();
        assert_eq!(es[0], -1.0);
        assert_eq!(es[1], 0.0);
        assert_eq!(es[2], f64::INFINITY);

        // Complex log1p / expm1 are supported and accurate near zero.
        let z = rt::asarray((vec![Complex::new(1e-20_f64, 1e-20)], &device));
        let lz = rt::log1p(&z).to_vec();
        assert!((lz[0].re - 1e-20).abs() < 1e-36 && (lz[0].im - 1e-20).abs() < 1e-36, "{:?}", lz[0]);
        let ez = rt::expm1(&z).to_vec();
        assert!((ez[0].re - 1e-20).abs() < 1e-36 && (ez[0].im - 1e-20).abs() < 1e-36, "{:?}", ez[0]);

        // Complex special case: log1p(-1 + 0j) == -inf + 0j.
        let neg = rt::asarray((vec![Complex::new(-1.0_f64, 0.0)], &device));
        let ln = rt::log1p(&neg).to_vec();
        assert!(ln[0].re.is_infinite() && ln[0].re < 0.0 && ln[0].im == 0.0, "{:?}", ln[0]);
    }
}

#[cfg(test)]
mod custom_math_classify {
    use super::*;
    static FUNC: &str = "custom_math_classify";

    #[test]
    fn test_is_nan_is_finite_is_inf() {
        crate::specify_test!("test_is_nan_is_finite_is_inf");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // a = [0, nan, inf, -inf]; nan/finite/inf classification (bool -> to_vec).
        let a: Tensor<f64, _> = rt::asarray((vec![0.0, f64::NAN, f64::INFINITY, f64::NEG_INFINITY], &device));
        assert_eq!(rt::is_nan(&a).to_vec(), vec![false, true, false, false]);
        assert_eq!(rt::is_finite(&a).to_vec(), vec![true, false, false, false]);
        assert_eq!(rt::is_inf(&a).to_vec(), vec![false, false, true, true]);
    }

    #[test]
    fn test_signbit() {
        crate::specify_test!("test_signbit");

        let mut device = TESTCFG.device.clone();
        device.set_default_order(RowMajor);

        // sign bit (not `< 0`): set for negative values, -0.0, -inf and -NaN
        let a: Tensor<f64, _> =
            rt::asarray((vec![2.0, -2.0, 0.0, -0.0, f64::INFINITY, f64::NEG_INFINITY, f64::NAN, -f64::NAN], &device));
        assert_eq!(rt::signbit(&a).to_vec(), vec![false, true, false, true, false, true, false, true]);

        let i = rt::tensor_from_nested!([3, -3, 0], &device);
        assert_eq!(rt::signbit(&i).to_vec(), vec![false, true, false]);

        // unsigned: the sign bit is never set
        let u: Tensor<u8, _> = rt::asarray((vec![0u8, 1, 255], &device));
        assert_eq!(rt::signbit(&u).to_vec(), vec![false, false, false]);
    }
}
