//! HDF5 <-> CPU read interface.
//!
//! This interface will use rstsr's layout as the working layout for HDF5 read (and, later, write).
//!
//! The reading primitive ([`h5_read_vec_narrow`]) is an internal, ndarray-free reimplementation of
//! `hdf5-metno`'s `Dataset::read_slice`: a hyperslab built from rstsr basic-index [`Indexer`]s is
//! applied to the dataset's dataspace, and the selected elements are read straight into a
//! C-contiguous `Vec<T>` with a single `H5Dread` call. We depend on `hdf5-metno-sys` directly for
//! that one FFI call, because hdf5-metno's own raw-buffer reader (`read_into_buf`) is private and
//! every public slicing reader returns an `ndarray::Array`, which this project does not use.
//!
//! Most or all contents generated by AI (model glm-5.2).

use crate::prelude_dev::*;
use std::os::raw::c_void;

use hdf5_sys::h5d::H5Dread;
use hdf5_sys::h5p::H5P_DEFAULT;

/// Read a (possibly strided / sub-selected) region of an HDF5 dataset into a freshly allocated
/// `Vec<T>`, described by rstsr basic-index `indexers`.
///
/// This is an **internal** helper: it is not part of the public API and exists to be composed into
/// higher-level, layout-driven readers.
///
/// The dataset's dataspace is narrowed by a hyperslab built from `indexers` (the `Slice`/`Select`
/// subset of [`Layout::dim_slice`]'s semantics), and the selected elements are read in C order into
/// the returned buffer.
///
/// The returned [`Layout<IxD>`] is the C-contiguous layout of the produced `Vec<T>` (offset 0);
/// its shape is the output shape after dropping every `Indexer::Select` (integer-indexed) axis.
///
/// # Limitations
/// - Only `Indexer::Slice` and `Indexer::Select` are supported (`Insert`/`Ellipsis` are rejected).
/// - Slice steps must be positive (`> 0`): HDF5 hyperslabs do not support negative strides.
/// - The on-disk datatype must exactly match `T` (see [`verify_dataset_type`]).
pub fn h5_read_vec_narrow<T>(dataset: &H5Dataset, indexers: &[Indexer]) -> Result<(Vec<T>, Layout<IxD>)>
where
    T: H5Type + Copy,
{
    verify_dataset_type::<T>(dataset)?;

    let dataset_shape: Vec<usize> = dataset.shape();
    let (slab_dims, out_shape) = indexers_to_hyperslab(indexers, &dataset_shape)?;
    let out_size: usize = out_shape.iter().product();

    let mut buf: Vec<T> = Vec::new();
    if out_size > 0 {
        // file space: a copy of the dataset's dataspace with the hyperslab applied.
        let hyperslab = Hyperslab::from(slab_dims);
        let fspace = dataset
            .space()
            .map_err(|e| rstsr_error!(IOError, "Failed to get HDF5 dataspace: {e}"))?
            .select(hyperslab)
            .map_err(|e| rstsr_error!(IOError, "Failed to select HDF5 hyperslab: {e}"))?;
        // memory space: C-contiguous buffer of the output shape.
        let mspace = Dataspace::try_new(&out_shape)
            .map_err(|e| rstsr_error!(IOError, "Failed to create memory dataspace: {e}"))?;
        // `verify_dataset_type` already ensured the on-disk type equals `T`, so the dataset's own
        // dtype id doubles as the in-memory type (a direct byte copy, no conversion).
        // Bind the `Datatype` to a local: its hid_t is ref-counted and would be closed when the
        // temporary is dropped, so `.dtype()?.id()` (a temporary) yields a dangling handle.
        let dtype = dataset.dtype().map_err(|e| rstsr_error!(IOError, "Failed to read HDF5 datatype: {e}"))?;
        let type_id = dtype.id();

        buf = Vec::with_capacity(out_size);
        let status = unsafe {
            H5Dread(dataset.id(), type_id, mspace.id(), fspace.id(), H5P_DEFAULT, buf.as_mut_ptr() as *mut c_void)
        };
        if status < 0 {
            let stack = hdf5_metno::Error::query().map(|e| e.to_string()).unwrap_or_else(|_| "<no stack>".into());
            return Err(rstsr_error!(IOError, "H5Dread failed (status {status}): {stack}"));
        }
        // H5Dread fully initialized the buffer above; safe to set the length.
        unsafe { buf.set_len(out_size) };
    }

    let layout = out_shape.c();
    Ok((buf, layout))
}

/// Convert rstsr basic-index `indexers` into a per-dataset-axis hyperslab description plus the
/// resulting output shape.
///
/// Only `Indexer::Slice` and `Indexer::Select` are supported (`Insert`/`Ellipsis` are rejected).
/// Each indexer consumes one dataset axis, in order; any trailing axes default to full slices, so
/// `&[]` reads the whole dataset.
///
/// Returns `(slab_dims, out_shape)` where:
/// - `slab_dims` holds exactly one [`SliceOrIndex`] per dataset axis;
/// - `out_shape` keeps every `Slice` axis's count and drops every `Select` (integer-indexed) axis,
///   since those become single-point selections.
fn indexers_to_hyperslab(indexers: &[Indexer], dataset_shape: &[usize]) -> Result<(Vec<SliceOrIndex>, Vec<usize>)> {
    rstsr_assert!(
        indexers.len() <= dataset_shape.len(),
        InvalidValue,
        "Too many indexers ({}) for dataset ndim ({})",
        indexers.len(),
        dataset_shape.len(),
    )?;

    let mut slab_dims: Vec<SliceOrIndex> = Vec::with_capacity(dataset_shape.len());
    let mut out_shape: Vec<usize> = Vec::with_capacity(dataset_shape.len());

    // Each indexer consumes exactly one leading dataset axis (no Insert/Ellipsis), so zip pairs
    // them in order.
    for (idx, &axis_len) in indexers.iter().zip(dataset_shape) {
        match idx {
            Indexer::Slice(sl) => {
                let (start, step, count) = resolve_slice_axis(sl, axis_len)?;
                slab_dims.push(SliceOrIndex::SliceCount { start, step, count, block: 1 });
                out_shape.push(count);
            },
            Indexer::Select(i) => {
                let start = resolve_select_index(*i, axis_len)?;
                slab_dims.push(SliceOrIndex::Index(start));
                // Select drops this axis from the output shape.
            },
            // Insert / Ellipsis are out of scope; Indexer is #[non_exhaustive].
            other => {
                return Err(rstsr_error!(
                    InvalidValue,
                    "Unsupported indexer {other:?}: only Slice/Select are allowed for HDF5 reads."
                ));
            },
        }
    }

    // Remaining trailing axes default to full slices (so `&[]` reads the whole dataset).
    for &len in dataset_shape.iter().skip(indexers.len()) {
        slab_dims.push(SliceOrIndex::SliceCount { start: 0, step: 1, count: len, block: 1 });
        out_shape.push(len);
    }

    Ok((slab_dims, out_shape))
}

/// Resolve a rstsr [`SliceI`] against an axis of length `axis_len` into `(start, step, count)`.
///
/// Mirrors the `step > 0` branch of [`Layout::dim_narrow`]. Negative `start`/`stop` are treated
/// Python-style (relative to the end). A non-positive step is rejected, since HDF5 hyperslabs
/// require a positive stride.
fn resolve_slice_axis(sl: &SliceI, axis_len: usize) -> Result<(usize, usize, usize)> {
    let step = sl.step().unwrap_or(1);
    rstsr_assert!(step > 0, InvalidValue, "Slice step must be positive for HDF5 reads, got {step}")?;

    let len = axis_len as isize;
    let mut start = sl.start().unwrap_or(0);
    let mut stop = sl.stop().unwrap_or(len);
    if start < 0 {
        start = (len + start).max(0);
    }
    if stop < 0 {
        stop = (len + stop).max(0);
    }
    if start > len || start > stop {
        // improper start/stop yields an empty selection
        start = 0;
        stop = 0;
    } else if stop > len {
        stop = len;
    }

    let count = if stop > start { ((stop - start + step - 1) / step) as usize } else { 0 };
    Ok((start as usize, step as usize, count))
}

/// Resolve a (possibly negative) `Select` index against an axis of length `axis_len`.
fn resolve_select_index(idx: isize, axis_len: usize) -> Result<usize> {
    let resolved = if idx < 0 { axis_len as isize + idx } else { idx };
    rstsr_assert!(
        (0..axis_len as isize).contains(&resolved),
        ValueOutOfRange,
        "Select index {idx} out of bounds for axis length {axis_len}"
    )?;
    Ok(resolved as usize)
}

/// Parse a selection [`Layout`] into a list of per-axis [`Indexer`]s, relative to a dataset of
/// shape `dataset_shape`.
///
/// Under the strided convention used here, `layout` describes a basic-index view of a row-major
/// (C-contiguous) dataset:
/// - `layout.shape()[i]` is the per-axis **count**;
/// - `layout.stride()[i]` equals `dataset_cstride[i] * step_i`, so the per-axis **step** is
///   `layout.stride()[i] / dataset_cstride[i]` and must be a positive integer;
/// - `layout.offset()` is the flat start offset into the dataset, decomposed into per-axis
///   **starts** via the dataset shape (C-order multi-index).
///
/// Every produced indexer is `Indexer::Slice(start, start + count * step, step)`. The result is
/// exact in the sense that applying it to the dataset's own layout reconstructs the input:
/// ```ignore
/// let indexers = h5_deduce_axis_index_list(&layout, &dataset_shape)?;
/// assert_eq!(layout, dataset_shape.to_vec().c().dim_slice(&indexers)?);
/// ```
/// (shape, stride and offset all match).
pub fn h5_deduce_axis_index_list(layout: &Layout<IxD>, dataset_shape: &[usize]) -> Result<Vec<Indexer>> {
    let ndim = dataset_shape.len();
    rstsr_assert!(
        layout.ndim() == ndim,
        InvalidValue,
        "Layout ndim ({}) must equal dataset ndim ({ndim})",
        layout.ndim(),
    )?;

    let ds = dataset_shape.to_vec().stride_c_contig();
    let mut indexers = Vec::with_capacity(ndim);
    for i in 0..ndim {
        let count = layout.shape()[i];
        let stride = layout.stride()[i];
        let axis_len = dataset_shape[i];

        // step_i = stride / dataset_cstride (must be a positive integer)
        rstsr_assert!(ds[i] > 0, InvalidValue, "Zero dataset c-stride at axis {i} (zero-sized axis?)")?;
        rstsr_assert!(
            stride > 0 && stride % ds[i] == 0,
            InvalidValue,
            "Layout stride ({stride}) at axis {i} is not a positive multiple of the dataset c-stride ({})",
            ds[i],
        )?;
        let step = (stride / ds[i]) as usize;

        // start_i: decompose the flat offset via the dataset shape (C-order multi-index).
        let start = (layout.offset() / (ds[i] as usize)) % axis_len;

        // validate the last selected index is within the axis.
        if count > 0 {
            let last = start + (count - 1) * step;
            rstsr_assert!(
                last < axis_len,
                ValueOutOfRange,
                "Selection at axis {i} runs out of bounds: last index {last} >= length {axis_len}",
            )?;
        }

        let slice = SliceI::new(start as isize, (start + count * step) as isize, step as isize);
        indexers.push(Indexer::Slice(slice));
    }
    Ok(indexers)
}

#[cfg(test)]
mod tests {
    use super::*;
    use hdf5_sys::h5d::H5Dwrite;
    use hdf5_sys::h5s::H5S_ALL;

    /// Create a dataset `name` of the given shape in `file` and fill it row-major with `data`,
    /// without going through ndarray (raw `H5Dwrite`). This is scratch test-only code.
    fn write_dataset<T>(file: &H5File, name: &str, shape: &[usize], data: &[T]) -> Result<H5Dataset>
    where
        T: H5Type + Copy,
    {
        assert_eq!(data.len(), shape.iter().product::<usize>(), "data length must match shape");
        let ds = file
            .new_dataset::<T>()
            .shape(shape.to_vec())
            .create(name)
            .map_err(|e| rstsr_error!(IOError, "Failed to create dataset '{name}': {e}"))?;
        let dtype = ds.dtype().map_err(|e| rstsr_error!(IOError, "Failed to read dtype of '{name}': {e}"))?;
        let type_id = dtype.id(); // `dtype` is kept alive below for the duration of H5Dwrite.
        let status =
            unsafe { H5Dwrite(ds.id(), type_id, H5S_ALL, H5S_ALL, H5P_DEFAULT, data.as_ptr() as *const c_void) };
        if status < 0 {
            let stack = hdf5_metno::Error::query().map(|e| e.to_string()).unwrap_or_else(|_| "<no stack>".into());
            return Err(rstsr_error!(IOError, "H5Dwrite failed for '{name}' (status {status}): {stack}"));
        }
        Ok(ds)
    }

    fn tmp_device() -> DeviceHDF5 {
        let none: Option<&std::path::Path> = None;
        DeviceHDF5::temporary_f(none).rstsr_unwrap()
    }

    // small indexer constructors to avoid depending on macro re-exports in the test module
    fn idx_slice(start: isize, stop: isize, step: isize) -> Indexer {
        Indexer::Slice(SliceI::new(start, stop, step))
    }
    fn idx_select(i: isize) -> Indexer {
        Indexer::Select(i)
    }

    #[test]
    fn read_whole_2d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();

        // empty indexers => read the whole dataset
        let (vec, layout) = h5_read_vec_narrow::<i64>(&ds, &[]).unwrap();
        assert_eq!(vec, data);
        assert_eq!(layout.shape(), &[4, 6]);
        assert!(layout.c_contig());
    }

    #[test]
    fn read_strided_1d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..10).collect();
        let ds = write_dataset(dev.h5file(), "a", &[10], &data).unwrap();

        let (vec, layout) = h5_read_vec_narrow::<i64>(&ds, &[idx_slice(0, 10, 2)]).unwrap();
        assert_eq!(vec, vec![0, 2, 4, 6, 8]);
        assert_eq!(layout.shape(), &[5]);
    }

    #[test]
    fn read_subblock_2d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();

        // rows 1..3, cols 2..5 -> [[8,9,10],[14,15,16]]
        let indexers = [idx_slice(1, 3, 1), idx_slice(2, 5, 1)];
        let (vec, layout) = h5_read_vec_narrow::<i64>(&ds, &indexers).unwrap();
        assert_eq!(vec, vec![8, 9, 10, 14, 15, 16]);
        assert_eq!(layout.shape(), &[2, 3]);
        assert!(layout.c_contig());
    }

    #[test]
    fn read_strided_2d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();

        // rows 0..4:2 (0,2), cols 1..6:2 (1,3,5) -> shape (2,3)
        // row0: cols 1,3,5 -> 1,3,5 ; row2: cols 1,3,5 -> 13,15,17
        let indexers = [idx_slice(0, 4, 2), idx_slice(1, 6, 2)];
        let (vec, layout) = h5_read_vec_narrow::<i64>(&ds, &indexers).unwrap();
        assert_eq!(vec, vec![1, 3, 5, 13, 15, 17]);
        assert_eq!(layout.shape(), &[2, 3]);
    }

    #[test]
    fn read_with_select() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();

        // select row 2, slice cols 1..4 -> flat 13,14,15 (shape (3,))
        let indexers = [idx_select(2), idx_slice(1, 4, 1)];
        let (vec, layout) = h5_read_vec_narrow::<i64>(&ds, &indexers).unwrap();
        assert_eq!(vec, vec![13, 14, 15]);
        assert_eq!(layout.shape(), &[3]);
    }

    #[test]
    fn read_rejects_ellipsis() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();
        let err = h5_read_vec_narrow::<i64>(&ds, &[Indexer::Ellipsis, idx_slice(2, 5, 1)]).unwrap_err();
        assert!(err.to_string().contains("Unsupported indexer"), "got: {err}");
    }

    #[test]
    fn read_rejects_negative_step() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..10).collect();
        let ds = write_dataset(dev.h5file(), "a", &[10], &data).unwrap();
        let err = h5_read_vec_narrow::<i64>(&ds, &[idx_slice(9, -1, -1)]).unwrap_err();
        assert!(err.to_string().contains("positive"), "got: {err}");
    }

    #[test]
    fn read_rejects_insert() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..10).collect();
        let ds = write_dataset(dev.h5file(), "a", &[10], &data).unwrap();
        let err = h5_read_vec_narrow::<i64>(&ds, &[Indexer::Insert]).unwrap_err();
        assert!(err.to_string().contains("Insert"), "got: {err}");
    }

    #[test]
    fn read_rejects_dtype_mismatch() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..10).collect();
        let ds = write_dataset(dev.h5file(), "a", &[10], &data).unwrap();
        // dataset is i64; reading as f64 (same size, different kind) must be rejected.
        let err = h5_read_vec_narrow::<f64>(&ds, &[]).unwrap_err();
        assert!(err.to_string().contains("mismatch"), "got: {err}");
    }

    #[test]
    fn deduce_axis_index_list_roundtrip_2d() {
        // dataset shape (4,6); select rows 1..3, cols 2..5 via a strided selection layout.
        let dataset_shape = vec![4usize, 6];
        // dataset c-strides = [6, 1]; step (1,1) -> strides [6,1]; start (1,2) -> offset 1*6+2 = 8.
        let layout = Layout::<IxD>::new(vec![2, 3], vec![6, 1], 8).unwrap();
        let indexers = h5_deduce_axis_index_list(&layout, &dataset_shape).unwrap();
        let reconstructed = dataset_shape.c().dim_slice(&indexers).unwrap();
        assert_eq!(layout, reconstructed);
    }

    #[test]
    fn deduce_axis_index_list_roundtrip_strided_1d() {
        let dataset_shape = vec![10usize];
        // c-stride [1]; step 2 -> stride [2]; start 0 -> offset 0.
        let layout = Layout::<IxD>::new(vec![5], vec![2], 0).unwrap();
        let indexers = h5_deduce_axis_index_list(&layout, &dataset_shape).unwrap();
        let reconstructed = dataset_shape.c().dim_slice(&indexers).unwrap();
        assert_eq!(layout, reconstructed);
    }

    #[test]
    fn deduce_axis_index_list_rejects_non_multiple_stride() {
        let dataset_shape = vec![4usize, 6];
        // stride 5 on axis 0 is not a multiple of the c-stride 6.
        let layout = Layout::<IxD>::new(vec![2, 3], vec![5, 1], 0).unwrap();
        let err = h5_deduce_axis_index_list(&layout, &dataset_shape).unwrap_err();
        assert!(err.to_string().contains("multiple"), "got: {err}");
    }

    #[test]
    fn deduce_and_read_compose_2d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();
        let dataset_shape = vec![4usize, 6];

        // select rows 1..3, cols 2..5 (step 1): strides [6,1], offset 8.
        let layout = Layout::<IxD>::new(vec![2, 3], vec![6, 1], 8).unwrap();
        let indexers = h5_deduce_axis_index_list(&layout, &dataset_shape).unwrap();
        let (vec, out_layout) = h5_read_vec_narrow::<i64>(&ds, &indexers).unwrap();
        assert_eq!(vec, vec![8, 9, 10, 14, 15, 16]);
        // the produced buffer is C-contiguous with the selection's shape and offset 0.
        assert_eq!(out_layout.shape(), &[2, 3]);
        assert_eq!(out_layout.offset(), 0);
        assert!(out_layout.c_contig());
    }

    #[test]
    fn deduce_and_read_compose_strided_2d() {
        let dev = tmp_device();
        let data: Vec<i64> = (0..24).collect();
        let ds = write_dataset(dev.h5file(), "a", &[4, 6], &data).unwrap();
        let dataset_shape = vec![4usize, 6];

        // rows 0..4:2 (step 2), cols 1..6:2 (step 2): c-strides [6,1] * step [2,2] = [12,2].
        // start (0,1) -> offset 0*6 + 1 = 1; counts [2,3].
        let layout = Layout::<IxD>::new(vec![2, 3], vec![12, 2], 1).unwrap();
        let indexers = h5_deduce_axis_index_list(&layout, &dataset_shape).unwrap();
        // sanity: round-trips against the dataset layout
        assert_eq!(layout, dataset_shape.c().dim_slice(&indexers).unwrap());
        let (vec, out_layout) = h5_read_vec_narrow::<i64>(&ds, &indexers).unwrap();
        assert_eq!(vec, vec![1, 3, 5, 13, 15, 17]);
        assert_eq!(out_layout.shape(), &[2, 3]);
    }
}
